package com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6;

import com.shatteredpixel.shatteredpixeldungeon.actors.hero.Hero;import com.shatteredpixel.shatteredpixeldungeon.actors.hero.Talent;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.dependency.*;import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.identity.DisplayName;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.save.*;import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.spec.ClassBuildSpec;import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.state.ClassRuntimeState;import com.watabou.utils.Bundle;
import org.junit.Test;import static org.junit.Assert.*;

public class CanonicalSaveCoreTest {
	@Test public void buildAndRuntimeRoundtripAreByteCanonicalAndDeepEquivalent(){P01Fixtures f=new P01Fixtures();ClassBuildSpec build=f.build();ClassRuntimeState runtime=f.runtime();CanonicalBuildCodec builds=new CanonicalBuildCodec();CanonicalRuntimeCodec states=new CanonicalRuntimeCodec();String buildJson=builds.serialize(build);String runtimeJson=states.serialize(runtime);CanonicalLoadResult<ClassBuildSpec> loadedBuild=builds.deserialize(buildJson);CanonicalLoadResult<ClassRuntimeState> loadedState=states.deserialize(runtimeJson);assertEquals(DependencyState.RESOLVED,loadedBuild.state());assertEquals(DependencyState.RESOLVED,loadedState.state());assertEquals(buildJson,builds.serialize(loadedBuild.value()));assertEquals(runtimeJson,states.serialize(loadedState.value()));CanonicalDeepEquivalence oracle=new CanonicalDeepEquivalence();assertTrue(oracle.equivalent(build,loadedBuild.value()));assertTrue(oracle.equivalent(runtime,loadedState.value()));assertNotSame(build,loadedBuild.value());assertNotSame(runtime,loadedState.value());}
	@Test public void canonicalOutputCoversEveryP01SectionAndSemanticMutationChangesIt(){P01Fixtures f=new P01Fixtures();CanonicalBuildCodec codec=new CanonicalBuildCodec();ClassBuildSpec source=f.build();String json=codec.serialize(source);for(String key:new String[]{"schema_version","contract_version","build_id","display_name","resources","marks","mode_groups","modes","capacities","entities","entity_type","body","spawn_policy","ownership","relation","persistence","capabilities","capability_kind","slots","maximum_override","ability_pools","properties","recipes","class_components","class_constraints","class_operations","skills","starting_kit","progression","budget_metadata","last_known_display_name","implementation_state"})assertTrue(key,json.contains("\""+key+"\""));ClassBuildSpec renamed=source.toBuilder().displayName(DisplayName.of("另一个构筑")).build();assertNotEquals(json,codec.serialize(renamed));ClassBuildSpec reordered=source.toBuilder().resources(java.util.Arrays.asList(new com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.spec.ResourceSpec(f.ids.nextId("res"),DisplayName.of("Focus"),0,10,0,com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.spec.ResourceSpec.ResourceOverflowPolicy.FAIL,new com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.spec.ResourceSpec.ResourceHudSpec(true,1,"focus")),f.resource)).build();assertNotEquals(json,codec.serialize(reordered));String runtime=new CanonicalRuntimeCodec().serialize(f.runtime());for(String key:new String[]{"resources","reservations","suppressions","modes","marks","entities","capability_states","scheduled_payloads","attachments","cooldowns","uses_this_floor","snapshots","learned_abilities","properties","next_runtime_entity_id","next_payload_instance_id","next_event_id"})assertTrue(key,runtime.contains("\""+key+"\""));}
	@Test public void resolverValidatorAndLoadNeverMutateSpec(){P01Fixtures f=new P01Fixtures();ClassBuildSpec build=f.build();CanonicalBuildCodec codec=new CanonicalBuildCodec();String before=codec.serialize(build);new DependencyResolver().resolve(build);assertEquals(before,codec.serialize(build));new ClassBuildValidator().validate(build);assertEquals(before,codec.serialize(build));CanonicalLoadResult<ClassBuildSpec> loaded=codec.deserialize(before);assertEquals(before,codec.serialize(build));assertEquals(before,codec.serialize(loaded.value()));}
	@Test public void deepOracleIsIndependentAndDetectsNestedSemanticDifferences(){P01Fixtures f=new P01Fixtures();CanonicalDeepEquivalence oracle=new CanonicalDeepEquivalence();assertFalse(oracle.equivalent(f.build(),f.build().toBuilder().displayName(DisplayName.of("语义变化")).build()));assertFalse(oracle.equivalent(f.runtime(),f.runtime().toBuilder().nextEventId(f.runtime().nextEventId()+1).build()));}
	@Test public void unknownSchemaAndVariantFailClosedWithoutDefault(){P01Fixtures f=new P01Fixtures();CanonicalBuildCodec codec=new CanonicalBuildCodec();String json=codec.serialize(f.build());CanonicalLoadResult<ClassBuildSpec> schema=codec.deserialize(json.replace("\"schema_version\":6","\"schema_version\":7"));assertEquals(DependencyState.UNSUPPORTED,schema.state());assertNull(schema.value());CanonicalLoadResult<ClassBuildSpec> variant=codec.deserialize(json.replace("\"entity_type\":\"DEVICE\"","\"entity_type\":\"UNKNOWN_ENTITY\""));assertEquals(DependencyState.UNSUPPORTED,variant.state());assertNull(variant.value());assertTrue(variant.diagnostics().get(0).contains("unknown"));}
	@Test public void realHeroStoreRestoreKeepsBuildAndRuntimeAsSeparateOptionalPayloads(){P01Fixtures f=new P01Fixtures();ClassBuildSpec build=f.build();ClassRuntimeState runtime=f.runtime();Hero original=new Hero();Talent.initClassTalents(original);HeroClassBundleCodec codec=new HeroClassBundleCodec();codec.store(original,build,runtime);Bundle bundle=new Bundle();original.storeInBundle(bundle);assertTrue(bundle.contains(HeroClassBundleCodec.CLASS_BUILD_SPEC));assertTrue(bundle.contains(HeroClassBundleCodec.CLASS_RUNTIME_STATE));assertNotEquals(bundle.getString(HeroClassBundleCodec.CLASS_BUILD_SPEC),bundle.getString(HeroClassBundleCodec.CLASS_RUNTIME_STATE));Hero restored=new Hero();restored.restoreFromBundle(bundle);HeroClassBundleCodec.LoadPair loaded=codec.load(restored);assertEquals(DependencyState.UNSUPPORTED,loaded.state());assertTrue(new CanonicalDeepEquivalence().equivalent(build,loaded.build()));assertTrue(new CanonicalDeepEquivalence().equivalent(runtime,loaded.runtime()));}
	@Test public void realLegacyHeroWithoutV6PayloadStillRestores(){Hero original=new Hero();Talent.initClassTalents(original);Bundle bundle=new Bundle();original.storeInBundle(bundle);Hero restored=new Hero();restored.restoreFromBundle(bundle);assertEquals(DependencyState.UNRESOLVED,new HeroClassBundleCodec().load(restored).state());}
}
