package com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6;

import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.dependency.*;import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.edit.*;import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.identity.*;import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.ref.*;import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.spec.*;
import org.junit.Test;import java.util.ArrayList;import java.util.Arrays;import java.util.Collections;import java.util.List;
import static org.junit.Assert.*;

public class DependencyAndEditSemanticsTest {
	@Test public void everyTypedReferenceSupportsDeleteSameNameAndExplicitRebind(){P01Fixtures f=new P01Fixtures();ContractNodeSpec componentTarget=new ContractNodeSpec(f.ids.nextId("component"),DisplayName.of("组件"),ContractNodeSpec.NodeKind.COMPONENT,"DECLARATION",ImplementationState.DECLARED);ClassBuildSpec build=f.declarationsOnly().toBuilder().addClassComponent(componentTarget).build();List<Case> cases=Arrays.asList(
			new Case(f.resource,new ResourceRef(f.resource.id(),"Rage")),new Case(f.mark,new MarkRef(f.mark.id(),"灼痕")),new Case(f.modeGroup,new ModeGroupRef(f.modeGroup.id(),"姿态")),new Case(f.mode,new ModeRef(f.mode.id(),"防守")),new Case(f.entity,new EntitySpecRef(f.entity.id(),"守卫装置")),new Case(f.capacity,new CapacityRef(f.capacity.id(),"装置容量")),new Case(componentTarget,new ComponentRef(componentTarget.id(),"组件")),new Case(f.abilityPool,new AbilityPoolRef(f.abilityPool.id(),"观察池")),new Case(f.property,new PropertyRef(f.property.id(),"炽热")),new Case(f.recipe,new SynthesisRecipeRef(f.recipe.id(),"炽热合成")));
		BuildEditService edits=new BuildEditService();ReferenceEditService refs=new ReferenceEditService();DependencyResolver resolver=new DependencyResolver();
		for(int i=0;i<cases.size();i++){Case value=cases.get(i);String field="probe["+i+"]";assertState(resolver.resolve(build,Collections.singletonList(new DependencyRequest(build.buildId(),field,value.ref))),field,DependencyState.RESOLVED);ClassBuildSpec duplicated=edits.duplicate(build,value.target.id(),f.ids);StableTarget replacement=findSameNameDifferentId(duplicated,value.target);assertNotNull(replacement);assertNotEquals(value.target.id(),replacement.id());ClassBuildSpec deleted=edits.delete(duplicated,value.target.id());assertState(resolver.resolve(deleted,Collections.singletonList(new DependencyRequest(build.buildId(),field,value.ref))),field,DependencyState.UNRESOLVED);TypedRef rebound=refs.rebind(value.ref,replacement);assertState(resolver.resolve(deleted,Collections.singletonList(new DependencyRequest(build.buildId(),field,rebound))),field,DependencyState.RESOLVED);assertEquals(value.ref.kind(),rebound.kind());assertEquals(replacement.id(),rebound.targetId());}
	}
	@Test public void renameChangesOnlyDisplayNameAndNeverId(){P01Fixtures f=new P01Fixtures();ClassBuildSpec source=f.declarationsOnly();String oldName=f.resource.displayName().text();ClassBuildSpec renamed=new BuildEditService().rename(source,f.resource.id(),DisplayName.of("怒气"));ResourceSpec result=renamed.resources().get(0);assertEquals(f.resource.id(),result.id());assertEquals("怒气",result.displayName().text());assertEquals(oldName,source.resources().get(0).displayName().text());}
	@Test public void duplicateTypeMismatchUnsupportedAndCycleAreDiagnosed(){P01Fixtures f=new P01Fixtures();DependencyResolver resolver=new DependencyResolver();ClassBuildSpec duplicate=f.declarationsOnly().toBuilder().addMark(new MarkSpec(f.resource.id(),DisplayName.of("错误复用"),MarkSpec.MarkKind.FLAG,0,1,0,MarkSpec.MarkDurationPolicy.PERMANENT_UNTIL_REMOVED,0,MarkSpec.MarkRefreshPolicy.KEEP_LONGER,MarkSpec.MarkOverflowPolicy.CLAMP,MarkSpec.MarkProvenancePolicy.NONE)).build();assertTrue(resolver.resolve(duplicate).has(DependencyState.HARD_CONFLICT));
		DependencyReport mismatch=resolver.resolve(f.declarationsOnly(),Collections.singletonList(new DependencyRequest(f.buildId,"wrong_type",new ResourceRef(f.mark.id(),f.mark.displayName().text()))));assertState(mismatch,"wrong_type",DependencyState.HARD_CONFLICT);
		EntitySpec unsupported=new EntitySpec(f.ids.nextId("entity"),DisplayName.of("未支持实体"),EntityType.ACTOR,null,ImplementationState.UNSUPPORTED);ClassBuildSpec unsupportedBuild=f.declarationsOnly().toBuilder().addEntity(unsupported).build();DependencyReport unsupportedReport=resolver.resolve(unsupportedBuild,Collections.singletonList(new DependencyRequest(f.buildId,"unsupported",new EntitySpecRef(unsupported.id(),unsupported.displayName().text()))));assertState(unsupportedReport,"unsupported",DependencyState.UNSUPPORTED);
		SynthesisRecipeSpec r1=new SynthesisRecipeSpec(f.ids.nextId("recipe"),DisplayName.of("R1"),Collections.emptyList(),"P01",ImplementationState.DECLARED);SynthesisRecipeSpec r2=new SynthesisRecipeSpec(f.ids.nextId("recipe"),DisplayName.of("R2"),Collections.emptyList(),"P01",ImplementationState.DECLARED);ClassBuildSpec cycles=f.declarationsOnly().toBuilder().addRecipe(r1).addRecipe(r2).build();List<DependencyRequest> edges=Arrays.asList(new DependencyRequest(r1.id(),"next",new SynthesisRecipeRef(r2.id(),"R2")),new DependencyRequest(r2.id(),"next",new SynthesisRecipeRef(r1.id(),"R1")));assertTrue(resolver.resolve(cycles,edges).diagnostics().stream().anyMatch(d->"dependency.illegal_cycle".equals(d.messageKey())));}
	@Test public void buildLevelRebindOnlyChangesExplicitField(){P01Fixtures f=new P01Fixtures();ModeGroupSpec replacement=new ModeGroupSpec(f.ids.nextId("modegrp"),DisplayName.of("新姿态"),ModeGroupSpec.ModeGroupPolicy.EXCLUSIVE);ClassBuildSpec source=f.declarationsOnly().toBuilder().addModeGroup(replacement).build();ClassBuildSpec rebound=new BuildEditService().rebind(source,f.mode.id(),"group",replacement);assertEquals(f.modeGroup.id(),source.modes().get(0).group().targetId());assertEquals(replacement.id(),rebound.modes().get(0).group().targetId());}
	@Test public void entityResourceSlotNeverFallsBackAndRequiresExplicitRebind(){P01Fixtures f=new P01Fixtures();BuildEditService edits=new BuildEditService();ClassBuildSpec duplicated=edits.duplicate(f.declarationsOnly(),f.resource.id(),f.ids);ResourceSpec replacement=duplicated.resources().get(1);ClassBuildSpec deleted=edits.delete(duplicated,f.resource.id());String path="capabilities[0].slots[0].resource";assertState(new DependencyResolver().resolve(deleted),path,DependencyState.UNRESOLVED);ClassBuildSpec rebound=edits.rebind(deleted,f.entity.id(),path,replacement);assertState(new DependencyResolver().resolve(rebound),path,DependencyState.RESOLVED);ResourceStorageCapability original=(ResourceStorageCapability)f.entity.capabilities().get(0);ResourceStorageCapability changed=(ResourceStorageCapability)rebound.entities().get(0).capabilities().get(0);assertEquals(f.resource.id(),original.slots().get(0).resource().targetId());assertEquals(replacement.id(),changed.slots().get(0).resource().targetId());}
	private static void assertState(DependencyReport report,String field,DependencyState state){assertTrue(report.diagnostics().toString(),report.diagnostics().stream().anyMatch(d->field.equals(d.fieldPath())&&state==d.state()));}
	private static StableTarget findSameNameDifferentId(ClassBuildSpec build,StableTarget source){for(StableTarget target:build.allTargets())if(target.refKind()==source.refKind()&&!target.id().equals(source.id())&&target.displayName().equals(source.displayName()))return target;return null;}
	private static final class Case{final StableTarget target;final TypedRef ref;Case(StableTarget target,TypedRef ref){this.target=target;this.ref=ref;}}
}
