package com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6;

import com.shatteredpixel.shatteredpixeldungeon.actors.Char;
import com.shatteredpixel.shatteredpixeldungeon.actors.mobs.Rat;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.builder.BuilderCommand;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.builder.PlayerBuildSession;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.compile.ClassCompilePlan;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.compile.CompiledSkill;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.compile.SkillCompiler;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.ref.ResourceRef;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.runtime.*;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.state.ResourceState;
import org.junit.Test;

import static org.junit.Assert.*;

public class P04ComponentsAndRecipesTest extends P04RuntimeTestBase {
	@Test public void basicAttackComponentChangesOnlyCompiledBasicAttackContract(){PlayerBuildSession session=PlayerBuildSession.empty(new com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.identity.DeterministicIdGenerator("p04-basic"));session.dispatch(new BuilderCommand.CreateClassComponent("Restricted Attack","BASIC_ATTACK"));String id=session.state().draft().classComponents().get(0).id().value();session.dispatch(new BuilderCommand.SetFieldValue(id,"BASIC_ATTACK","availability","WEAK"));session.dispatch(new BuilderCommand.SetFieldValue(id,"BASIC_ATTACK","damage_numerator","1"));session.dispatch(new BuilderCommand.SetFieldValue(id,"BASIC_ATTACK","damage_denominator","2"));P04TestBuilds.clean(session);V6RuleRuntimeBridge bridge=V6RuleRuntimeBridge.install(hero,session.finalizeOrThrow());assertTrue(bridge.basicAttackAllowed());assertEquals(CompiledSkill.ItemCategory.ANY_WEAPON,bridge.plan().components().get(0).allowedWeapons());assertEquals(5,bridge.basicAttackDamage(10));assertEquals(1f,bridge.basicAttackDelay(1f),0f);}

	@Test public void activeResourceOperationComponentCompilesWithItsLinkedOperationAndRuns(){PlayerBuildSession session=P04TestBuilds.twoResources("p04-active-component");session.dispatch(new BuilderCommand.CreateClassComponent("Manual Charge","ACTIVE_RESOURCE_OPERATION"));String component=session.state().draft().classComponents().get(0).id().value();String operation=session.state().draft().classOperations().get(0).id().value();session.dispatch(new BuilderCommand.SetReference(component,"ACTIVE_RESOURCE_OPERATION","operation.resource",P04TestBuilds.resourceRef(session,0)));session.dispatch(new BuilderCommand.SetReference(operation,"RESOURCE_OPERATION","operation.resource",P04TestBuilds.resourceRef(session,0)));P04TestBuilds.clean(session);ClassCompilePlan plan=compile(session);assertEquals(1,plan.components().size());assertEquals(1,plan.operations().size());assertEquals(plan.operations().get(0).id(),plan.components().get(0).operationId());V6RuleRuntimeBridge bridge=V6RuleRuntimeBridge.install(hero,session.finalizeOrThrow());SkillExecutionResult result=bridge.triggerOperation(hero,operation,50,0,damageGateway());assertEquals(SkillExecutionResult.Status.APPLIED,result.status());assertEquals(6,current(bridge,session,0));}

	@Test public void ammoGunnerRecipeIsCommandBuiltAndRunsWithoutClassLabels(){PlayerBuildSession session=PlayerBuildSession.empty(new com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.identity.DeterministicIdGenerator("p04-recipe-ammo"));session.dispatch(new BuilderCommand.CreateResource("Ammo"));String ammo=P04TestBuilds.resourceId(session,0);session.dispatch(new BuilderCommand.EditResourceField(ammo,"initial_value","3"));session.dispatch(new BuilderCommand.CreateClassComponent("Weapon Profile","BASIC_ATTACK"));session.dispatch(new BuilderCommand.CreateClassComponent("Recover Round","RESOURCE_FLOW"));String flow=session.state().draft().classComponents().get(1).id().value();session.dispatch(new BuilderCommand.SetFieldValue(flow,"RESOURCE_FLOW","event_type","ATTACK_HIT"));session.dispatch(new BuilderCommand.SetReference(flow,"RESOURCE_FLOW","operation.resource",P04TestBuilds.resourceRef(session,0)));String skill=P04TestBuilds.createSkill(session,"Spend Round","DAMAGE","DIRECT_DAMAGE",false);session.dispatch(new BuilderCommand.SetTypedSkillField(skill,"effects.primary","DIRECT_DAMAGE","amount","4"));session.dispatch(new BuilderCommand.SetCost(skill,"RESOURCE"));session.dispatch(new BuilderCommand.SetTypedSkillReference(skill,"cost","RESOURCE","resource",P04TestBuilds.resourceRef(session,0)));P04TestBuilds.clean(session);assertNoFixedLabels(session);V6RuleRuntimeBridge bridge=V6RuleRuntimeBridge.install(hero,session.finalizeOrThrow());Rat target=actor(13,20,Char.Alignment.ENEMY);assertEquals(SkillExecutionResult.Status.APPLIED,bridge.triggerActive(hero,target.pos,skill,60,0,damageGateway()).status());assertEquals(2,current(bridge,session,0));assertEquals(SkillExecutionResult.Status.APPLIED,bridge.triggerResourceFlows(hero,GameplayEventContext.RuleEventType.ATTACK_HIT,61,60,damageGateway()).status());assertEquals(3,current(bridge,session,0));}

	@Test public void bloodBerserkerRecipeUsesHpCostLowHpAndMissingHpScaling(){PlayerBuildSession session=P04TestBuilds.effect("p04-recipe-blood","DAMAGE","MISSING_HP_DAMAGE",false);String skill=session.state().draft().skills().get(0).id().value();session.dispatch(new BuilderCommand.SetTypedSkillField(skill,"effects.primary","MISSING_HP_DAMAGE","base_amount","2"));session.dispatch(new BuilderCommand.SetTypedSkillField(skill,"effects.primary","MISSING_HP_DAMAGE","missing_hp_numerator","1"));session.dispatch(new BuilderCommand.SetTypedSkillField(skill,"effects.primary","MISSING_HP_DAMAGE","missing_hp_denominator","2"));session.dispatch(new BuilderCommand.SelectConditionVariant(skill,"BUILTIN_STAT_COMPARE"));session.dispatch(new BuilderCommand.SetTypedSkillField(skill,"condition.0","BUILTIN_STAT_COMPARE","stat","HP_PERCENT"));session.dispatch(new BuilderCommand.SetTypedSkillField(skill,"condition.0","BUILTIN_STAT_COMPARE","operator","LTE"));session.dispatch(new BuilderCommand.SetTypedSkillField(skill,"condition.0","BUILTIN_STAT_COMPARE","value","50"));session.dispatch(new BuilderCommand.SetCost(skill,"HP"));session.dispatch(new BuilderCommand.SetTypedSkillField(skill,"cost","HP","amount","5"));P04TestBuilds.clean(session);assertNoFixedLabels(session);hero.HP=40;Rat target=actor(13,40,Char.Alignment.ENEMY);target.HT=100;V6RuleRuntimeBridge bridge=V6RuleRuntimeBridge.install(hero,session.finalizeOrThrow());assertEquals(SkillExecutionResult.Status.APPLIED,bridge.triggerActive(hero,target.pos,skill,70,0,damageGateway()).status());assertEquals(35,hero.HP);assertTrue(target.HP<40);assertTrue(session.state().draft().resources().isEmpty());}

	@Test public void areaCasterRecipeUsesRadiusAndHitsThreeOrderedTargets(){PlayerBuildSession session=P04TestBuilds.effect("p04-recipe-area","DAMAGE","DIRECT_DAMAGE",false);String skill=session.state().draft().skills().get(0).id().value();session.dispatch(new BuilderCommand.SetTypedSkillField(skill,"effects.primary","DIRECT_DAMAGE","amount","3"));session.dispatch(new BuilderCommand.SetTargetingCoverage(skill,"RADIUS"));session.dispatch(new BuilderCommand.SetTypedSkillField(skill,"targeting","TARGETING","radius","1"));session.dispatch(new BuilderCommand.SetTypedSkillField(skill,"targeting","TARGETING","maximum_targets","3"));P04TestBuilds.clean(session);assertNoFixedLabels(session);Rat first=actor(18,20,Char.Alignment.ENEMY),center=actor(19,20,Char.Alignment.ENEMY),third=actor(20,20,Char.Alignment.ENEMY);V6RuleRuntimeBridge bridge=V6RuleRuntimeBridge.install(hero,session.finalizeOrThrow());SkillExecutionResult result=bridge.triggerActive(hero,center.pos,skill,80,0,damageGateway());assertEquals(result.trace().serialize(),SkillExecutionResult.Status.APPLIED,result.status());assertEquals(17,first.HP);assertEquals(17,center.HP);assertEquals(17,third.HP);assertTrue(result.trace().serialize(),result.trace().serialize().contains("coverage=RADIUS"));}

	private static ClassCompilePlan compile(PlayerBuildSession session){ClassCompilePlan plan=new SkillCompiler(EffectExecutorRegistry.standard()).compile(session.finalizeOrThrow());assertTrue(plan.diagnostics().toString(),plan.executable());return plan;}
	private static int current(V6RuleRuntimeBridge bridge,PlayerBuildSession session,int index){ResourceState value=bridge.state().resources().get(new ResourceRef(session.state().draft().resources().get(index).id(),""));assertNotNull(value);return value.current();}
	private static void assertNoFixedLabels(PlayerBuildSession session){String canonical=new com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.save.CanonicalBuildCodec().serialize(session.state().draft());assertFalse(canonical,canonical.contains("GUNNER_CORE"));assertFalse(canonical,canonical.contains("Blood Class"));assertFalse(canonical,canonical.contains("MAGE_DOMAIN"));}
}
