package com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6;

import com.shatteredpixel.shatteredpixeldungeon.actors.Char;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.Poison;
import com.shatteredpixel.shatteredpixeldungeon.actors.mobs.Rat;
import com.shatteredpixel.shatteredpixeldungeon.items.potions.PotionOfHealing;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.builder.BuilderCommand;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.builder.PlayerBuildSession;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.compile.ClassCompilePlan;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.compile.CompiledSkill;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.compile.SkillCompiler;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.runtime.*;
import org.junit.Test;

import static org.junit.Assert.*;

public class P04DeliveryModifierCostTest extends P04RuntimeTestBase {
	@Test public void allSixDeliveryVariantsCompileTypedAndEnforceTheirPreflight(){String[] variants={"DIRECT","SELF","CONTACT","PROJECTILE","TRACE","GROUND"};for(String variant:variants){boolean self="SELF".equals(variant);PlayerBuildSession session=P04TestBuilds.effect("p04-delivery-"+variant,self?"RECOVERY_DEFENSE":"DAMAGE",self?"HEAL":"DIRECT_DAMAGE",self);String id=skill(session);session.dispatch(new BuilderCommand.SetDelivery(id,variant));if("GROUND".equals(variant)){session.dispatch(new BuilderCommand.SetTargetingSelector(id,"SELECTED_CELL"));session.dispatch(new BuilderCommand.SetTargetingFilter(id,"RELATION_ENEMY_EXCLUDE_SELF"));}if("TRACE".equals(variant))session.dispatch(new BuilderCommand.SetTypedSkillField(id,"delivery","TRACE","width","2"));P04TestBuilds.clean(session);ClassCompilePlan plan=compile(session);assertEquals(CompiledSkill.DeliveryVariant.valueOf(variant),plan.skills().get(0).delivery().variant());if(self){assertEquals(SkillExecutionResult.Status.APPLIED,run(session,hero.pos,10).status());}else{Rat target=actor(11,30,Char.Alignment.ENEMY);SkillExecutionResult result=run(session,target.pos,10);assertEquals(variant+" "+result.trace().serialize(),SkillExecutionResult.Status.APPLIED,result.status());com.shatteredpixel.shatteredpixeldungeon.actors.Actor.remove(target);level.remove(target);}}}

	@Test public void contactProjectileAndTraceBlockBeforeEffectWhenTheirPathFails(){PlayerBuildSession contact=P04TestBuilds.effect("p04-contact-block","DAMAGE","DIRECT_DAMAGE",false);contact.dispatch(new BuilderCommand.SetDelivery(skill(contact),"CONTACT"));Rat far=actor(24,30,Char.Alignment.ENEMY);assertEquals(SkillExecutionResult.Status.BLOCKED,run(contact,far.pos,20).status());assertEquals(30,far.HP);com.shatteredpixel.shatteredpixeldungeon.actors.Actor.remove(far);level.remove(far);
		for(String variant:new String[]{"PROJECTILE","TRACE"}){PlayerBuildSession session=P04TestBuilds.effect("p04-path-block-"+variant,"DAMAGE","DIRECT_DAMAGE",false);session.dispatch(new BuilderCommand.SetDelivery(skill(session),variant));Rat target=actor(10,30,Char.Alignment.ENEMY);level.wall(11);SkillExecutionResult result=run(session,target.pos,21+variant.length());assertEquals(SkillExecutionResult.Status.BLOCKED,result.status());assertEquals(30,target.HP);com.shatteredpixel.shatteredpixeldungeon.actors.Actor.remove(target);level.remove(target);level.clearWall(11);}}

	@Test public void adjacentRadiusAndLineCoverageCarryTheirOwnParametersAndRuntimeTrace(){for(String coverage:new String[]{"ADJACENT","RADIUS","LINE"}){PlayerBuildSession session=P04TestBuilds.effect("p04-coverage-"+coverage,"DAMAGE","DIRECT_DAMAGE",false);String id=skill(session);session.dispatch(new BuilderCommand.SetTargetingCoverage(id,coverage));session.dispatch(new BuilderCommand.SetTypedSkillField(id,"targeting","TARGETING","maximum_targets","2"));if("RADIUS".equals(coverage))session.dispatch(new BuilderCommand.SetTypedSkillField(id,"targeting","TARGETING","radius","2"));if("LINE".equals(coverage)){session.dispatch(new BuilderCommand.SetTypedSkillField(id,"targeting","TARGETING","line_length","4"));session.dispatch(new BuilderCommand.SetTypedSkillField(id,"targeting","TARGETING","line_width","1"));}P04TestBuilds.clean(session);Rat target=actor(11,20,Char.Alignment.ENEMY);SkillExecutionResult result=run(session,target.pos,30+coverage.length());assertEquals(result.trace().serialize(),SkillExecutionResult.Status.APPLIED,result.status());assertTrue(result.trace().serialize(),result.trace().serialize().contains("coverage="+coverage));CompiledSkill.Targeting compiled=compile(session).skills().get(0).targeting();assertEquals(CompiledSkill.CoverageVariant.valueOf(coverage),compiled.coverage());if("RADIUS".equals(coverage))assertEquals(2,compiled.coverageFirst());if("LINE".equals(coverage)){assertEquals(4,compiled.coverageFirst());assertEquals(1,compiled.coverageSecond());}com.shatteredpixel.shatteredpixeldungeon.actors.Actor.remove(target);level.remove(target);}}

	@Test public void allyAnyAndSelfFiltersAreDistinctAtRuntime(){PlayerBuildSession allyOnly=P04TestBuilds.effect("p04-filter-ally","RECOVERY_DEFENSE","HEAL",false);allyOnly.dispatch(new BuilderCommand.SetTargetingFilter(skill(allyOnly),"RELATION_ALLY_EXCLUDE_SELF"));Rat ally=actor(13,20,hero.alignment);ally.HT=30;assertEquals(SkillExecutionResult.Status.APPLIED,run(allyOnly,ally.pos,40).status());assertEquals(21,ally.HP);assertEquals(SkillExecutionResult.Status.NO_TARGET,run(allyOnly,hero.pos,41).status());com.shatteredpixel.shatteredpixeldungeon.actors.Actor.remove(ally);level.remove(ally);
		PlayerBuildSession allySelf=P04TestBuilds.effect("p04-filter-ally-self","RECOVERY_DEFENSE","HEAL",true);allySelf.dispatch(new BuilderCommand.SetTargetingFilter(skill(allySelf),"RELATION_ALLY_INCLUDE_SELF"));hero.HP=90;assertEquals(SkillExecutionResult.Status.APPLIED,run(allySelf,hero.pos,42).status());assertEquals(91,hero.HP);
		PlayerBuildSession any=P04TestBuilds.effect("p04-filter-any","DAMAGE","DIRECT_DAMAGE",false);any.dispatch(new BuilderCommand.SetTargetingFilter(skill(any),"ANY_ACTOR"));Rat neutral=actor(13,20,Char.Alignment.NEUTRAL);assertEquals(SkillExecutionResult.Status.APPLIED,run(any,neutral.pos,43).status());assertEquals(19,neutral.HP);}

	@Test public void intensityExtendPierceAndBounceHaveParameterSpecificRuntimeEffects(){PlayerBuildSession intensity=P04TestBuilds.effect("p04-mod-intensity","DAMAGE","DIRECT_DAMAGE",false);set(intensity,"effects.primary","DIRECT_DAMAGE","amount","2");intensity.dispatch(new BuilderCommand.SetModifier(skill(intensity),"INTENSITY"));set(intensity,"modifier","INTENSITY","numerator","3");set(intensity,"modifier","INTENSITY","denominator","2");Rat target=actor(13,20,Char.Alignment.ENEMY);assertEquals(SkillExecutionResult.Status.APPLIED,run(intensity,target.pos,50).status());assertEquals(17,target.HP);com.shatteredpixel.shatteredpixeldungeon.actors.Actor.remove(target);level.remove(target);
		PlayerBuildSession extend=P04TestBuilds.effect("p04-mod-extend","STATUS","APPLY_STATUS",false);extend.dispatch(new BuilderCommand.SetModifier(skill(extend),"EXTEND_DURATION"));set(extend,"modifier","EXTEND_DURATION","additional_turns","2");Rat statusTarget=actor(13,20,Char.Alignment.ENEMY);SkillExecutionResult extended=run(extend,statusTarget.pos,51);assertNotNull(statusTarget.buff(Poison.class));assertTrue(extended.trace().serialize(),extended.trace().serialize().contains("turns=5"));com.shatteredpixel.shatteredpixeldungeon.actors.Actor.remove(statusTarget);level.remove(statusTarget);
		for(String modifier:new String[]{"PIERCE","BOUNCE"}){PlayerBuildSession session=P04TestBuilds.effect("p04-mod-"+modifier,"DAMAGE","DIRECT_DAMAGE",false);session.dispatch(new BuilderCommand.SetModifier(skill(session),modifier));if("PIERCE".equals(modifier)){session.dispatch(new BuilderCommand.SetDelivery(skill(session),"PROJECTILE"));set(session,"modifier",modifier,"additional_targets","1");}else{set(session,"modifier",modifier,"bounces","1");set(session,"modifier",modifier,"bounce_range","1");}Rat first=actor(11,20,Char.Alignment.ENEMY),second=actor(10,20,Char.Alignment.ENEMY);SkillExecutionResult result=run(session,first.pos,52+modifier.length());assertEquals(result.trace().serialize(),SkillExecutionResult.Status.APPLIED,result.status());assertEquals(19,first.HP);assertEquals(19,second.HP);com.shatteredpixel.shatteredpixeldungeon.actors.Actor.remove(first);com.shatteredpixel.shatteredpixeldungeon.actors.Actor.remove(second);level.remove(first);level.remove(second);}}

	@Test public void actionCooldownAndItemCostsCommitExactlyOnce(){PlayerBuildSession action=P04TestBuilds.effect("p04-cost-action","RECOVERY_DEFENSE","HEAL",true);action.dispatch(new BuilderCommand.SetCost(skill(action),"ACTION_TIME"));set(action,"cost","ACTION_TIME","turns","2");float before=hero.cooldown();assertEquals(SkillExecutionResult.Status.APPLIED,run(action,hero.pos,60).status());assertEquals(before+2,hero.cooldown(),0f);
		PlayerBuildSession cooldown=P04TestBuilds.effect("p04-cost-cooldown","RECOVERY_DEFENSE","HEAL",true);cooldown.dispatch(new BuilderCommand.SetCost(skill(cooldown),"COOLDOWN"));set(cooldown,"cost","COOLDOWN","turns","3");assertEquals(SkillExecutionResult.Status.APPLIED,run(cooldown,hero.pos,61).status());assertEquals(SkillExecutionResult.Status.BLOCKED,run(cooldown,hero.pos,62).status());
		hero.setGameplayComponentsV6Payloads(null,null);hero.setGameplayComponentsV6RuntimeBridge(null);PlayerBuildSession item=P04TestBuilds.effect("p04-cost-item","RECOVERY_DEFENSE","HEAL",true);item.dispatch(new BuilderCommand.SetCost(skill(item),"ITEM"));set(item,"cost","ITEM","item_category","POTION");PotionOfHealing potion=new PotionOfHealing();assertTrue(potion.collect(hero.belongings.backpack));assertEquals(SkillExecutionResult.Status.APPLIED,run(item,hero.pos,63).status());assertTrue(hero.belongings.getAllItems(PotionOfHealing.class).isEmpty());assertEquals(SkillExecutionResult.Status.BLOCKED,run(item,hero.pos,64).status());}

	private ClassCompilePlan compile(PlayerBuildSession session){ClassCompilePlan plan=new SkillCompiler(EffectExecutorRegistry.standard()).compile(session.finalizeOrThrow());assertTrue(plan.diagnostics().toString(),plan.executable());return plan;}
	private SkillExecutionResult run(PlayerBuildSession session,int cell,long event){V6RuleRuntimeBridge bridge=V6RuleRuntimeBridge.install(hero,session.finalizeOrThrow());return bridge.triggerActive(hero,cell,skill(session),event,0,damageGateway());}
	private static String skill(PlayerBuildSession session){return session.state().draft().skills().get(0).id().value();}
	private static void set(PlayerBuildSession session,String path,String variant,String field,String value){session.dispatch(new BuilderCommand.SetTypedSkillField(skill(session),path,variant,field,value));P04TestBuilds.clean(session);}
}
