package com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6;

import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.catalog.*;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.spec.ImplementationState;
import org.junit.Test;import org.junit.runner.*;
import java.lang.reflect.Method;import java.util.*;
import static org.junit.Assert.*;

/** Gate: every through-P04 exposed variant owns a complete, runnable evidence row. */
public class P04ImplementationEvidenceTest {
	@Test public void everyP04VariantHasExplicitCompleteRunnableEvidence(){Map<String,P04ImplementationEvidence.Row> registry=P04ImplementationEvidence.registry();assertCoverage(registry);assertEquals(66,registry.size());Set<String> executed=new HashSet<>();for(P04ImplementationEvidence.Row row:registry.values()){assertEquals(ImplementationState.IMPLEMENTED,row.state);assertEquals(10,row.testIds().size());for(String id:row.testIds())if(executed.add(id))verifyAndRun(id);}}
	@Test public void missingOrUnknownEvidenceRowsFailClosed(){Map<String,P04ImplementationEvidence.Row> missing=new LinkedHashMap<>(P04ImplementationEvidence.registry());missing.remove("EFFECT.PUSH");assertFails(missing,"missing evidence row EFFECT.PUSH");Map<String,P04ImplementationEvidence.Row> unknown=new LinkedHashMap<>(P04ImplementationEvidence.registry());unknown.put("EFFECT.NOT_REAL",new P04ImplementationEvidence.Row("EFFECT.NOT_REAL","P04CoreEffectRuntimeTest#directDamageUsesTypedAmount"));assertFails(unknown,"unknown evidence variant EFFECT.NOT_REAL");}
	private static void assertCoverage(Map<String,P04ImplementationEvidence.Row> registry){Set<String> known=new HashSet<>(),required=new LinkedHashSet<>();for(VariantDescriptor d:GameplayVariantCatalog.all()){assertTrue("duplicate catalog variant "+d.qualifiedKey(),known.add(d.qualifiedKey()));if(d.state()==ImplementationState.IMPLEMENTED||d.playerExposed()){assertEquals("implemented/exposed mismatch "+d.qualifiedKey(),ImplementationState.IMPLEMENTED,d.state());assertTrue("implemented variant hidden "+d.qualifiedKey(),d.playerExposed());assertFalse("missing price "+d.qualifiedKey(),d.priceKey().isEmpty());required.add(d.qualifiedKey());}else assertFalse("future variant exposed "+d.qualifiedKey(),d.playerExposed());}for(String key:registry.keySet())assertTrue("unknown evidence variant "+key,known.contains(key));for(String key:required)assertTrue("missing evidence row "+key,registry.containsKey(key));assertEquals(required,registry.keySet());}
	private static void assertFails(Map<String,P04ImplementationEvidence.Row> value,String expected){try{assertCoverage(value);fail("invalid evidence accepted");}catch(AssertionError e){assertTrue(e.getMessage(),e.getMessage().contains(expected));}}
	private static void verifyAndRun(String id){int split=id.indexOf('#');assertTrue("invalid evidence id "+id,split>0);String className=P04ImplementationEvidenceTest.class.getPackage().getName()+"."+id.substring(0,split),method=id.substring(split+1);try{Class<?> type=Class.forName(className);Method found=type.getDeclaredMethod(method);assertNotNull("evidence method lacks @Test "+id,found.getAnnotation(Test.class));Result result=new JUnitCore().run(Request.method(type,method));assertEquals("evidence run count "+id,1,result.getRunCount());assertTrue("evidence failed "+id+" "+result.getFailures(),result.wasSuccessful());}catch(ClassNotFoundException e){throw new AssertionError("missing evidence class "+id,e);}catch(NoSuchMethodException e){throw new AssertionError("missing evidence method "+id,e);}}
}
