package com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6;

import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.builder.*;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.catalog.GameplayVariantCatalog;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.catalog.VariantDescriptor;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.compile.*;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.dependency.DependencyResolver;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.dependency.DependencyState;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.form.*;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.format.SkillFormatter;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.identity.DeterministicIdGenerator;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.runtime.EffectExecutorRegistry;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.save.CanonicalBuildCodec;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.save.CanonicalLoadResult;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.spec.ClassBuildSpec;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.spec.resource.ConvertResourceSpec;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.spec.skill.ResourceOperationEffectSpec;
import org.junit.Test;

import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

import static org.junit.Assert.*;

public class P04LayerEvidenceTest {
	@Test public void schemaExposesVariantSpecificTypedFields(){FormSchema skill=V6FormSchemas.require(V6FormSchemas.SKILL);assertOptions(skill,"effect_primary_variant","DIRECT_DAMAGE","PERCENT_MAX_HP_DAMAGE","MISSING_HP_DAMAGE","EXECUTE","APPLY_STATUS","PUSH","PULL","THROW","DASH","TELEPORT","SWAP_POSITION","HEAL","BARRIER","TEMPORARY_HP","MITIGATE","REDIRECT_DAMAGE","CLEANSE","RESOURCE_OPERATION");assertOptions(skill,"delivery_variant","DIRECT","SELF","CONTACT","PROJECTILE","TRACE","GROUND");assertOptions(skill,"targeting_selector","SELECTED_ACTOR","SELF","SELECTED_CELL");assertOptions(skill,"targeting_coverage","SINGLE","ADJACENT","RADIUS","LINE");assertOptions(skill,"targeting_filter","RELATION_ENEMY_EXCLUDE_SELF","RELATION_ALLY_EXCLUDE_SELF","RELATION_ALLY_INCLUDE_SELF","ANY_ACTOR","SELF");assertOptions(skill,"modifier_variant","NONE","REPEAT","INTENSITY","EXTEND_DURATION","PIERCE","BOUNCE");assertOptions(skill,"cost_variant","NO_COST","RESOURCE","HP","ACTION_TIME","COOLDOWN","ITEM");for(String key:new String[]{"effect_primary_percent","effect_primary_missing_hp_numerator","effect_primary_status","effect_primary_distance","effect_primary_duration_turns","effect_primary_operation_source","effect_primary_operation_target","targeting_radius","targeting_line_length","modifier_bounce_range","cost_item_category"})assertNotNull(key,skill.requireField(key));assertOptions(V6FormSchemas.require(V6FormSchemas.BASIC_ATTACK),"allowed_weapons","ANY_WEAPON");for(String form:new String[]{V6FormSchemas.RESOURCE_FLOW,V6FormSchemas.ACTIVE_RESOURCE_OPERATION,V6FormSchemas.RESOURCE_CLASS_OPERATION}){FormSchema schema=V6FormSchemas.require(form);assertOptions(schema,"operation_variant","GAIN","DRAIN","SET","CLEAR","CONVERT","RESERVE","SUPPRESS");assertTrue(schema.requireField("operation.source") instanceof ReferenceFieldSchema);assertTrue(schema.requireField("operation.target") instanceof ReferenceFieldSchema);}}

	@Test public void builderFormsDispatchTypedP04FieldsWithoutNoop(){PlayerBuildSession session=P04TestBuilds.twoResources("p04-form-path");session.dispatch(new BuilderCommand.CreateClassOperation("Convert","RESOURCE_OPERATION"));String operation=session.state().draft().classOperations().get(0).id().value();BuilderFormController form=new BuilderFormController(session);form.dispatchValue(operation,"operation_variant","CONVERT");form.dispatchValue(operation,"operation.source",P04TestBuilds.resourceId(session,0));form.dispatchValue(operation,"operation.target",P04TestBuilds.resourceId(session,1));stepTo(form,operation,"operation.source_amount",2);stepTo(form,operation,"operation.target_amount",5);P04TestBuilds.clean(session);ConvertResourceSpec convert=(ConvertResourceSpec)((com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.spec.component.ResourceClassOperationSpec)session.state().draft().classOperations().get(0)).operation();assertEquals(2,convert.sourceAmount());assertEquals(5,convert.targetAmount());assertEquals(P04TestBuilds.resourceRef(session,0).targetId(),convert.source().targetId());assertEquals(P04TestBuilds.resourceRef(session,1).targetId(),convert.target().targetId());}

	@Test public void dependenciesAndGlobalIdentityFailClosed(){PlayerBuildSession session=P04TestBuilds.classConvert("p04-dependency");String deleted=P04TestBuilds.resourceId(session,0);session.dispatch(new BuilderCommand.DeleteDeclaration(deleted));assertEquals(DependencyState.UNRESOLVED,new DependencyResolver().resolve(session.state().draft()).aggregateState());assertTrue(session.state().draft().resources().stream().noneMatch(r->r.id().value().equals(deleted)));}

	@Test public void bilingualFormatterAndBudgetUseConcreteVariantParameters(){PlayerBuildSession session=P04TestBuilds.resourceSkillConvert("p04-format");ResourceOperationEffectSpec effect=(ResourceOperationEffectSpec)session.state().draft().skills().get(0).effects().primary();SkillFormatter formatter=new SkillFormatter();String en=formatter.format(session.state().draft().skills().get(0),SkillFormatter.Language.ENGLISH),zh=formatter.format(session.state().draft().skills().get(0),SkillFormatter.Language.SIMPLIFIED_CHINESE);assertTrue(en,en.contains("CONVERT Rage -2 -> Focus +5")&&en.contains("no cost"));assertTrue(zh,zh.contains("资源操作 CONVERT Rage -2 -> Focus +5")&&zh.contains("无消耗"));assertTrue(SkillFormatter.resource(effect.operation(),false).contains("EXACT_ATOMIC"));BuilderBudgetLedger ledger=session.state().budget();assertTrue(ledger.entries().stream().anyMatch(e->"skill.effect.resource_operation".equals(e.priceKey())));assertEquals(ledger.spent(),ledger.entries().stream().mapToInt(BuilderBudgetLedger.Entry::amount).sum());}

	@Test public void formatterCoversEveryP04EffectWithBilingualParameterText(){SkillFormatter formatter=new SkillFormatter();for(String variant:new String[]{"DIRECT_DAMAGE","PERCENT_MAX_HP_DAMAGE","MISSING_HP_DAMAGE","EXECUTE","APPLY_STATUS","PUSH","PULL","THROW","DASH","TELEPORT","SWAP_POSITION","HEAL","BARRIER","TEMPORARY_HP","MITIGATE","REDIRECT_DAMAGE","CLEANSE"}){PlayerBuildSession session=P04TestBuilds.effect("p04-format-"+variant,family(variant),variant,selfEffect(variant));String en=formatter.format(session.state().draft().skills().get(0),SkillFormatter.Language.ENGLISH),zh=formatter.format(session.state().draft().skills().get(0),SkillFormatter.Language.SIMPLIFIED_CHINESE);assertTrue(variant+" "+en,en.contains("Active;")&&!en.contains("Unsupported"));assertTrue(variant+" "+zh,zh.contains("主动")&&!zh.contains("不支持"));assertTrue(variant+" lacks concrete parameter text",en.matches(".*[0-9].*")||en.contains("SPD_NATIVE")||en.contains("legality="));}PlayerBuildSession resource=P04TestBuilds.resourceSkillConvert("p04-format-resource");assertTrue(formatter.format(resource.state().draft().skills().get(0),SkillFormatter.Language.ENGLISH).contains("Rage -2 -> Focus +5"));}

	@Test public void everyExposedVariantHasAPriceProducedByItsTypedBuild(){Set<String> produced=new HashSet<>();for(String effect:new String[]{"DIRECT_DAMAGE","PERCENT_MAX_HP_DAMAGE","MISSING_HP_DAMAGE","EXECUTE","APPLY_STATUS","PUSH","PULL","THROW","DASH","TELEPORT","SWAP_POSITION","HEAL","BARRIER","TEMPORARY_HP","MITIGATE","REDIRECT_DAMAGE","CLEANSE","RESOURCE_OPERATION"})prices(produced,"RESOURCE_OPERATION".equals(effect)?P04TestBuilds.resourceSkillConvert("p04-price-effect-resource"):P04TestBuilds.effect("p04-price-effect-"+effect,family(effect),effect,selfEffect(effect)));
		for(String variant:new String[]{"SELF","CONTACT","PROJECTILE","TRACE","GROUND"}){PlayerBuildSession s=P04TestBuilds.effect("p04-price-delivery-"+variant,"DAMAGE","DIRECT_DAMAGE",false);s.dispatch(new BuilderCommand.SetDelivery(s.state().draft().skills().get(0).id().value(),variant));prices(produced,s);}for(String variant:new String[]{"SELF","SELECTED_CELL"}){PlayerBuildSession s=P04TestBuilds.effect("p04-price-selector-"+variant,"DAMAGE","DIRECT_DAMAGE",false);s.dispatch(new BuilderCommand.SetTargetingSelector(s.state().draft().skills().get(0).id().value(),variant));prices(produced,s);}for(String variant:new String[]{"ADJACENT","RADIUS","LINE"}){PlayerBuildSession s=P04TestBuilds.effect("p04-price-coverage-"+variant,"DAMAGE","DIRECT_DAMAGE",false);s.dispatch(new BuilderCommand.SetTargetingCoverage(s.state().draft().skills().get(0).id().value(),variant));prices(produced,s);}for(String variant:new String[]{"RELATION_ALLY_EXCLUDE_SELF","RELATION_ALLY_INCLUDE_SELF","ANY_ACTOR","SELF"}){PlayerBuildSession s=P04TestBuilds.effect("p04-price-filter-"+variant,"RECOVERY_DEFENSE","HEAL",false);s.dispatch(new BuilderCommand.SetTargetingFilter(s.state().draft().skills().get(0).id().value(),variant));prices(produced,s);}for(String variant:new String[]{"REPEAT","INTENSITY","EXTEND_DURATION","PIERCE","BOUNCE"}){PlayerBuildSession s=P04TestBuilds.effect("p04-price-modifier-"+variant,"DAMAGE","DIRECT_DAMAGE",false);s.dispatch(new BuilderCommand.SetModifier(s.state().draft().skills().get(0).id().value(),variant));prices(produced,s);}for(String variant:new String[]{"RESOURCE","HP","ACTION_TIME","COOLDOWN","ITEM"}){PlayerBuildSession s="RESOURCE".equals(variant)?P04TestBuilds.twoResources("p04-price-cost-resource"):P04TestBuilds.effect("p04-price-cost-"+variant,"DAMAGE","DIRECT_DAMAGE",false);if("RESOURCE".equals(variant))P04TestBuilds.createSkill(s,"Cost","DAMAGE","DIRECT_DAMAGE",false);s.dispatch(new BuilderCommand.SetCost(s.state().draft().skills().get(0).id().value(),variant));prices(produced,s);}
		PlayerBuildSession condition=P04TestBuilds.twoResources("p04-price-condition");String conditionSkill=P04TestBuilds.createSkill(condition,"Condition","RECOVERY_DEFENSE","HEAL",true);condition.dispatch(new BuilderCommand.SelectConditionVariant(conditionSkill,"BUILTIN_STAT_COMPARE"));prices(produced,condition);PlayerBuildSession resourceCondition=P04TestBuilds.twoResources("p04-price-resource-condition");String resourceConditionSkill=P04TestBuilds.createSkill(resourceCondition,"Condition","RECOVERY_DEFENSE","HEAL",true);resourceCondition.dispatch(new BuilderCommand.SelectConditionVariant(resourceConditionSkill,"RESOURCE_COMPARE"));prices(produced,resourceCondition);
		PlayerBuildSession secondary=P04TestBuilds.effect("p04-price-secondary","DAMAGE","DIRECT_DAMAGE",false);String secondarySkill=secondary.state().draft().skills().get(0).id().value();secondary.dispatch(new BuilderCommand.SelectEffectFamily(secondarySkill,"IMMEDIATE_SECONDARY","DAMAGE"));secondary.dispatch(new BuilderCommand.SelectEffectVariant(secondarySkill,"IMMEDIATE_SECONDARY","DIRECT_DAMAGE"));prices(produced,secondary);
		for(String variant:new String[]{"GAIN","DRAIN","SET","CLEAR","CONVERT","RESERVE","SUPPRESS"}){PlayerBuildSession s=P04TestBuilds.twoResources("p04-price-operation-"+variant);s.dispatch(new BuilderCommand.CreateClassOperation(variant,"RESOURCE_OPERATION"));s.dispatch(new BuilderCommand.SetFieldValue(s.state().draft().classOperations().get(0).id().value(),"RESOURCE_OPERATION","operation_variant",variant));prices(produced,s);}for(String variant:new String[]{"BASIC_ATTACK","RESOURCE_FLOW","ACTIVE_RESOURCE_OPERATION"}){PlayerBuildSession s=P04TestBuilds.twoResources("p04-price-component-"+variant);s.dispatch(new BuilderCommand.CreateClassComponent("Component",variant));P04TestBuilds.clean(s);assertEquals(variant,1,s.state().draft().classComponents().size());prices(produced,s);}for(VariantDescriptor descriptor:GameplayVariantCatalog.playerExposed())assertTrue(descriptor.qualifiedKey()+" missing "+descriptor.priceKey()+" produced="+produced,produced.contains(descriptor.priceKey()));}

	@Test public void canonicalRoundTripPreservesP04Nodes(){CanonicalBuildCodec codec=new CanonicalBuildCodec();for(ClassBuildSpec build:new ClassBuildSpec[]{P04TestBuilds.resourceSkillConvert("p04-roundtrip-skill").finalizeOrThrow(),P04TestBuilds.classConvert("p04-roundtrip-op").finalizeOrThrow()}){String json=codec.serialize(build);CanonicalLoadResult<ClassBuildSpec> loaded=codec.deserialize(json);assertEquals(loaded.diagnostics().toString(),DependencyState.RESOLVED,loaded.state());assertNotNull(loaded.value());assertEquals(json,codec.serialize(loaded.value()));assertTrue(json,json.contains("\"conversion_policy\":\"EXACT_ATOMIC\""));}}

	@Test public void compilerBuildsIndependentImmutableP04NodesAndAdmissionKeepsFutureClosed(){ClassCompilePlan plan=compile(P04TestBuilds.classConvert("p04-immutable").finalizeOrThrow());assertEquals(2,plan.resources().size());assertEquals(1,plan.operations().size());assertEquals(CompiledSkill.ResourceOperationVariant.CONVERT,plan.operations().get(0).operation().variant());try{plan.resources().clear();fail("compiled resource list was mutable");}catch(UnsupportedOperationException expected){}
		PlayerBuildSession future=PlayerBuildSession.empty(new DeterministicIdGenerator("p04-future-closed"));future.dispatch(new BuilderCommand.CreateMark("Future Mark"));future.dispatch(new BuilderCommand.CreateClassComponent("Attack","BASIC_ATTACK"));ClassCompilePlan rejected=new SkillCompiler(EffectExecutorRegistry.standard()).compile(future.state().draft());assertFalse(rejected.executable());assertTrue(rejected.diagnostics().toString(),rejected.diagnostics().stream().anyMatch(d->d.fieldPath().contains("marks")));}

	@Test public void registryBindsEveryP04EffectToExactTypedExecutor(){EffectExecutorRegistry registry=EffectExecutorRegistry.standard();for(CompiledSkill.EffectVariant variant:CompiledSkill.EffectVariant.values())assertTrue(variant.name(),registry.has(variant));assertEquals(18,CompiledSkill.EffectVariant.values().length);}

	@Test public void deferredFamiliesRemainClosed(){for(String key:new String[]{"EFFECT.ADD_MARK","EFFECT.CREATE_ENTITY","EFFECT.TRANSFER_RESOURCE","COVERAGE.CONE","COST.MARK"}){int dot=key.indexOf('.');assertFalse(key,GameplayVariantCatalog.require(key.substring(0,dot),key.substring(dot+1)).playerExposed());}CanonicalBuildCodec codec=new CanonicalBuildCodec();String json=codec.serialize(P03TestBuilds.directDamage("p04-closed",3,false,false).state().draft());CanonicalLoadResult<ClassBuildSpec> unavailable=codec.deserialize(json.replace("\"variant_key\":\"DIRECT_DAMAGE\"","\"variant_key\":\"ADD_MARK\""));assertEquals(DependencyState.UNSUPPORTED,unavailable.state());assertNull(unavailable.value());}

	private static ClassCompilePlan compile(ClassBuildSpec build){ClassCompilePlan plan=new SkillCompiler(EffectExecutorRegistry.standard()).compile(build);assertTrue(plan.diagnostics().toString(),plan.executable());return plan;}
	private static void assertOptions(FormSchema schema,String field,String... expected){Set<String> actual=new HashSet<>(((EnumFieldSchema)schema.requireField(field)).optionKeys());assertEquals(field,new HashSet<>(Arrays.asList(expected)),actual);}
	private static void stepTo(BuilderFormController form,String id,String field,int wanted){while(Integer.parseInt(form.form(id).requireField(field).currentValue())<wanted){int current=Integer.parseInt(form.form(id).requireField(field).currentValue());form.dispatchValue(id,field,Integer.toString(current+1));}}
	private static void prices(Set<String> out,PlayerBuildSession session){for(BuilderBudgetLedger.Entry entry:session.state().budget().entries())out.add(entry.priceKey());}
	private static boolean selfEffect(String variant){return Arrays.asList("DASH","TELEPORT","HEAL","BARRIER","TEMPORARY_HP","MITIGATE").contains(variant);}
	private static String family(String variant){if(Arrays.asList("DIRECT_DAMAGE","PERCENT_MAX_HP_DAMAGE","MISSING_HP_DAMAGE","EXECUTE").contains(variant))return "DAMAGE";if("APPLY_STATUS".equals(variant))return "STATUS";if(Arrays.asList("PUSH","PULL","THROW","DASH","TELEPORT","SWAP_POSITION").contains(variant))return "MOVEMENT";if("RESOURCE_OPERATION".equals(variant))return "RESOURCE_OPERATION";return "RECOVERY_DEFENSE";}
}
