package com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6;

import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.builder.BuilderCommand;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.builder.PlayerBuildSession;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.compile.ClassCompilePlan;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.compile.SkillCompiler;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.identity.StableId;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.ref.ResourceRef;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.runtime.*;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.save.CanonicalBuildCodec;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.save.CanonicalRuntimeCodec;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.spec.ClassBuildSpec;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.spec.resource.ConvertResourceSpec;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.spec.resource.ResourceOperationSpec;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.state.ClassRuntimeState;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.state.ResourceState;
import com.shatteredpixel.shatteredpixeldungeon.ui.ClassResourceHUD;
import org.junit.Test;

import java.util.LinkedHashMap;
import java.util.Map;

import static org.junit.Assert.*;

public class P04ResourceTransactionTest extends P04RuntimeTestBase {
	@Test public void rageToFocusClassOperationIsExactAtomicAndTraced(){PlayerBuildSession session=P04TestBuilds.classConvert("p04-convert");ClassBuildSpec build=session.finalizeOrThrow();ClassCompilePlan plan=compile(build);StableId operation=plan.operations().get(0).id();ClassRuntimeState initial=ResourceRuntimeStateFactory.initialize(plan);
		SkillExecutionResult success=runOperation(plan,initial,operation,100);assertEquals(SkillExecutionResult.Status.APPLIED,success.status());assertEquals(3,current(lastRuntime.state(),plan.resources().get(0).id()));assertEquals(5,current(lastRuntime.state(),plan.resources().get(1).id()));String committedTrace=success.trace().serialize();assertTrue(committedTrace,committedTrace.contains("transaction_id=tx-100-")&&committedTrace.contains("source_id="+plan.resources().get(0).id().value())&&committedTrace.contains("source_delta=-2")&&committedTrace.contains("target_id="+plan.resources().get(1).id().value())&&committedTrace.contains("target_delta=+5"));
		ClassRuntimeState low=withCurrent(initial,plan.resources().get(0).id(),1);SkillExecutionResult insufficient=runOperation(plan,low,operation,101);assertEquals(SkillExecutionResult.Status.BLOCKED,insufficient.status());assertEquals(1,current(lastRuntime.state(),plan.resources().get(0).id()));assertEquals(0,current(lastRuntime.state(),plan.resources().get(1).id()));
		ClassRuntimeState full=withCurrent(initial,plan.resources().get(1).id(),1);SkillExecutionResult noSpace=runOperation(plan,full,operation,102);assertEquals(SkillExecutionResult.Status.BLOCKED,noSpace.status());assertEquals(5,current(lastRuntime.state(),plan.resources().get(0).id()));assertEquals(1,current(lastRuntime.state(),plan.resources().get(1).id()));}

	@Test public void skillClassOperationAndResourceFlowShareExactConvertSemantics(){PlayerBuildSession skill=P04TestBuilds.resourceSkillConvert("p04-convert-skill");ClassCompilePlan skillPlan=compile(skill.finalizeOrThrow());V6RuleRuntime skillRuntime=new V6RuleRuntime(skillPlan,EffectExecutorRegistry.standard());GameplayEventContext active=event(skillPlan.skills().get(0).skillId(),200);SkillExecutionResult skillResult=skillRuntime.execute(skillPlan.skills().get(0).skillId(),new RuntimeExecutionContext(active,damageGateway()));assertEquals(SkillExecutionResult.Status.APPLIED,skillResult.status());assertPair(skillRuntime.state(),skillPlan,3,5);
		PlayerBuildSession operation=P04TestBuilds.classConvert("p04-convert-operation");ClassCompilePlan operationPlan=compile(operation.finalizeOrThrow());SkillExecutionResult operationResult=runOperation(operationPlan,ResourceRuntimeStateFactory.initialize(operationPlan),operationPlan.operations().get(0).id(),201);assertEquals(SkillExecutionResult.Status.APPLIED,operationResult.status());assertPair(lastRuntime.state(),operationPlan,3,5);
		PlayerBuildSession flow=P04TestBuilds.twoResources("p04-convert-flow");flow.dispatch(new BuilderCommand.CreateClassComponent("Wait Convert","RESOURCE_FLOW"));String component=flow.state().draft().classComponents().get(0).id().value();flow.dispatch(new BuilderCommand.SetFieldValue(component,"RESOURCE_FLOW","operation_variant","CONVERT"));flow.dispatch(new BuilderCommand.SetReference(component,"RESOURCE_FLOW","operation.source",P04TestBuilds.resourceRef(flow,0)));flow.dispatch(new BuilderCommand.SetReference(component,"RESOURCE_FLOW","operation.target",P04TestBuilds.resourceRef(flow,1)));flow.dispatch(new BuilderCommand.SetFieldValue(component,"RESOURCE_FLOW","operation.source_amount","2"));flow.dispatch(new BuilderCommand.SetFieldValue(component,"RESOURCE_FLOW","operation.target_amount","5"));P04TestBuilds.clean(flow);ClassCompilePlan flowPlan=compile(flow.finalizeOrThrow());V6RuleRuntime flowRuntime=new V6RuleRuntime(flowPlan,EffectExecutorRegistry.standard());GameplayEventContext wait=new GameplayEventContext(202,0,GameplayEventContext.RuleEventType.WAIT,hero.id(),hero.id(),hero.id(),hero.pos,hero.pos,hero.pos,flowPlan.buildId());SkillExecutionResult flowResult=flowRuntime.executeResourceFlows(new RuntimeExecutionContext(wait,damageGateway()));assertEquals(SkillExecutionResult.Status.APPLIED,flowResult.status());assertPair(flowRuntime.state(),flowPlan,3,5);}

	@Test public void saveLoadRenameAndHudPreserveStableReferencesAndRuntimeValues(){PlayerBuildSession session=P04TestBuilds.classConvert("p04-convert-persist");StableId rage=session.state().draft().resources().get(0).id();StableId focus=session.state().draft().resources().get(1).id();session.dispatch(new BuilderCommand.SaveDraft("convert"));session.dispatch(new BuilderCommand.LoadDraft("convert"));session.dispatch(new BuilderCommand.RenameDeclaration(rage.value(),"Fury"));P04TestBuilds.clean(session);ConvertResourceSpec operation=(ConvertResourceSpec)((com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.spec.component.ResourceClassOperationSpec)session.state().draft().classOperations().get(0)).operation();assertEquals(rage,operation.source().targetId());assertEquals(focus,operation.target().targetId());
		CanonicalBuildCodec builds=new CanonicalBuildCodec();String json=builds.serialize(session.finalizeOrThrow());ClassBuildSpec loaded=builds.deserialize(json).value();assertNotNull(loaded);ClassCompilePlan plan=compile(loaded);ClassRuntimeState initial=ResourceRuntimeStateFactory.initialize(plan);CanonicalRuntimeCodec states=new CanonicalRuntimeCodec();ClassRuntimeState restored=states.deserialize(states.serialize(initial)).value();assertNotNull(restored);SkillExecutionResult result=runOperation(plan,restored,plan.operations().get(0).id(),203);assertEquals(SkillExecutionResult.Status.APPLIED,result.status());assertPair(lastRuntime.state(),plan,3,5);String hud=ClassResourceHUD.readout(plan,lastRuntime.state());assertTrue(hud,hud.contains("Fury 3/10"));assertTrue(hud,hud.contains("Focus 5/5"));}

	@Test public void allSevenResourceOperationVariantsHaveDistinctStateBehavior(){for(ResourceOperationSpec.Variant variant:ResourceOperationSpec.Variant.values()){PlayerBuildSession session=P04TestBuilds.twoResources("p04-op-"+variant);session.dispatch(new BuilderCommand.CreateClassOperation(variant.name(),"RESOURCE_OPERATION"));String id=session.state().draft().classOperations().get(0).id().value();session.dispatch(new BuilderCommand.SetFieldValue(id,"RESOURCE_OPERATION","operation_variant",variant.name()));if(variant==ResourceOperationSpec.Variant.CONVERT){session.dispatch(new BuilderCommand.SetReference(id,"RESOURCE_OPERATION","operation.source",P04TestBuilds.resourceRef(session,0)));session.dispatch(new BuilderCommand.SetReference(id,"RESOURCE_OPERATION","operation.target",P04TestBuilds.resourceRef(session,1)));}else session.dispatch(new BuilderCommand.SetReference(id,"RESOURCE_OPERATION","operation.resource",P04TestBuilds.resourceRef(session,0)));P04TestBuilds.clean(session);ClassCompilePlan plan=compile(session.finalizeOrThrow());SkillExecutionResult result=runOperation(plan,ResourceRuntimeStateFactory.initialize(plan),plan.operations().get(0).id(),300+variant.ordinal());assertEquals(variant+" "+result.diagnostic(),SkillExecutionResult.Status.APPLIED,result.status());ResourceState rage=state(lastRuntime.state(),plan.resources().get(0).id()),focus=state(lastRuntime.state(),plan.resources().get(1).id());switch(variant){case GAIN:assertEquals(6,rage.current());break;case DRAIN:assertEquals(4,rage.current());break;case SET:assertEquals(1,rage.current());break;case CLEAR:assertEquals(0,rage.current());break;case CONVERT:assertEquals(4,rage.current());assertEquals(1,focus.current());break;case RESERVE:assertEquals(4,rage.current());assertEquals(1,rage.reservations().size());assertEquals(1,rage.reservations().get(0).amount());break;case SUPPRESS:assertEquals(5,rage.current());assertEquals(1,rage.suppressions().size());assertEquals("BLOCK_GAIN",rage.suppressions().get(0).modeKey());break;}String trace=result.trace().serialize();assertTrue(variant+" "+trace,trace.contains("resource_transaction")&&trace.contains("variant="+variant)&&trace.contains("status=COMMITTED"));}}

	@Test public void resourceCompareConditionReadsTheDeclaredRuntimePool(){PlayerBuildSession session=P04TestBuilds.twoResources("p04-resource-condition");String skill=P04TestBuilds.createSkill(session,"Rage Mend","RECOVERY_DEFENSE","HEAL",true);session.dispatch(new BuilderCommand.SelectConditionVariant(skill,"RESOURCE_COMPARE"));session.dispatch(new BuilderCommand.SetTypedSkillReference(skill,"condition.0","RESOURCE_COMPARE","resource",P04TestBuilds.resourceRef(session,0)));session.dispatch(new BuilderCommand.SetTypedSkillField(skill,"condition.0","RESOURCE_COMPARE","operator","GTE"));session.dispatch(new BuilderCommand.SetTypedSkillField(skill,"condition.0","RESOURCE_COMPARE","value","5"));session.dispatch(new BuilderCommand.SetCost(skill,"RESOURCE"));session.dispatch(new BuilderCommand.SetTypedSkillReference(skill,"cost","RESOURCE","resource",P04TestBuilds.resourceRef(session,0)));P04TestBuilds.clean(session);hero.HP=80;V6RuleRuntimeBridge bridge=V6RuleRuntimeBridge.install(hero,session.finalizeOrThrow());assertEquals(SkillExecutionResult.Status.APPLIED,bridge.triggerActive(hero,hero.pos,skill,390,0,damageGateway()).status());assertEquals(4,state(bridge.state(),bridge.plan().resources().get(0).id()).current());assertEquals(SkillExecutionResult.Status.BLOCKED,bridge.triggerActive(hero,hero.pos,skill,391,390,damageGateway()).status());assertEquals(4,state(bridge.state(),bridge.plan().resources().get(0).id()).current());}

	private V6RuleRuntime lastRuntime;
	private SkillExecutionResult runOperation(ClassCompilePlan plan,ClassRuntimeState state,StableId operation,long eventId){lastRuntime=new V6RuleRuntime(plan,EffectExecutorRegistry.standard(),state);return lastRuntime.executeOperation(operation,new RuntimeExecutionContext(event(operation,eventId),damageGateway()));}
	private GameplayEventContext event(StableId origin,long id){return new GameplayEventContext(id,0,GameplayEventContext.RuleEventType.ACTIVE,hero.id(),hero.id(),hero.id(),hero.pos,hero.pos,hero.pos,origin);}
	private static ClassCompilePlan compile(ClassBuildSpec build){ClassCompilePlan plan=new SkillCompiler(EffectExecutorRegistry.standard()).compile(build);assertTrue(plan.diagnostics().toString(),plan.executable());return plan;}
	private static int current(ClassRuntimeState state,StableId id){ResourceState value=state.resources().get(new ResourceRef(id,""));assertNotNull(value);return value.current();}
	private static ResourceState state(ClassRuntimeState state,StableId id){ResourceState value=state.resources().get(new ResourceRef(id,""));assertNotNull(value);return value;}
	private static void assertPair(ClassRuntimeState state,ClassCompilePlan plan,int first,int second){assertEquals(first,current(state,plan.resources().get(0).id()));assertEquals(second,current(state,plan.resources().get(1).id()));}
	private static ClassRuntimeState withCurrent(ClassRuntimeState state,StableId id,int value){Map<ResourceRef,ResourceState> resources=new LinkedHashMap<>(state.resources());ResourceRef key=new ResourceRef(id,"");ResourceState old=resources.get(key);resources.put(old.resource(),new ResourceState(old.resource(),value,old.reservations(),old.suppressions()));return state.toBuilder().resources(resources).build();}
}
