package com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6;

import com.shatteredpixel.shatteredpixeldungeon.actors.Char;
import com.shatteredpixel.shatteredpixeldungeon.actors.mobs.Rat;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.builder.BuilderCommand;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.builder.PlayerBuildSession;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.ref.ResourceRef;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.runtime.SkillExecutionResult;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.runtime.V6RuleRuntimeBridge;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.state.ResourceState;
import org.junit.Test;

import static org.junit.Assert.*;

public class P04TargetingAndTransactionBoundaryTest extends P04RuntimeTestBase {
	@Test public void enemyRelationAcceptsEnemyAndRejectsAllySelfAndNeutral(){PlayerBuildSession session=P04TestBuilds.effect("p04-relations","DAMAGE","DIRECT_DAMAGE",false);set(session,"effects.primary","DIRECT_DAMAGE","amount","3");String id=skill(session);V6RuleRuntimeBridge bridge=V6RuleRuntimeBridge.install(hero,session.finalizeOrThrow());Rat enemy=actor(13,20,Char.Alignment.ENEMY);Rat ally=actor(11,20,hero.alignment);Rat neutral=actor(19,20,Char.Alignment.NEUTRAL);
		assertEquals(SkillExecutionResult.Status.APPLIED,bridge.triggerActive(hero,enemy.pos,id,1,0,damageGateway()).status());assertEquals(17,enemy.HP);
		assertEquals(SkillExecutionResult.Status.NO_TARGET,bridge.triggerActive(hero,ally.pos,id,2,0,damageGateway()).status());assertEquals(20,ally.HP);
		assertEquals(SkillExecutionResult.Status.NO_TARGET,bridge.triggerActive(hero,hero.pos,id,3,0,damageGateway()).status());assertEquals(100,hero.HP);
		assertEquals(SkillExecutionResult.Status.NO_TARGET,bridge.triggerActive(hero,neutral.pos,id,4,0,damageGateway()).status());assertEquals(20,neutral.HP);}

	@Test public void bothEffectsPreflightBeforeHpCostAndBlockedMovementPaysNothing(){PlayerBuildSession session=P04TestBuilds.effect("p04-preflight-chain","DAMAGE","DIRECT_DAMAGE",false);String id=skill(session);set(session,"effects.primary","DIRECT_DAMAGE","amount","6");session.dispatch(new BuilderCommand.SelectEffectFamily(id,"IMMEDIATE_SECONDARY","MOVEMENT"));session.dispatch(new BuilderCommand.SelectEffectVariant(id,"IMMEDIATE_SECONDARY","PUSH"));set(session,"effects.secondary","PUSH","distance","1");session.dispatch(new BuilderCommand.SetCost(id,"HP"));set(session,"cost","HP","amount","9");P04TestBuilds.clean(session);Rat target=actor(13,30,Char.Alignment.ENEMY);level.wall(14);int before=hero.HP;SkillExecutionResult result=run(session,target.pos);assertEquals(SkillExecutionResult.Status.TARGET_UNAVAILABLE,result.status());assertEquals(before,hero.HP);assertEquals(30,target.HP);String trace=result.trace().serialize();assertTrue(trace,trace.contains("slot=primary")&&trace.contains("slot=secondary"));assertFalse(trace,trace.contains("cost_commit"));}

	@Test public void chainAndRepeatPayResourceCostOnceAndTraceEveryActivation(){PlayerBuildSession session=P04TestBuilds.twoResources("p04-chain-once");String id=P04TestBuilds.createSkill(session,"Double Mend","RECOVERY_DEFENSE","HEAL",true);set(session,"effects.primary","HEAL","amount","2");session.dispatch(new BuilderCommand.SelectEffectFamily(id,"IMMEDIATE_SECONDARY","RECOVERY_DEFENSE"));session.dispatch(new BuilderCommand.SelectEffectVariant(id,"IMMEDIATE_SECONDARY","HEAL"));set(session,"effects.secondary","HEAL","amount","1");session.dispatch(new BuilderCommand.SetModifier(id,"REPEAT"));set(session,"modifier","REPEAT","repeat_count","2");session.dispatch(new BuilderCommand.SetCost(id,"RESOURCE"));session.dispatch(new BuilderCommand.SetTypedSkillReference(id,"cost","RESOURCE","resource",P04TestBuilds.resourceRef(session,0)));set(session,"cost","RESOURCE","amount","2");P04TestBuilds.clean(session);hero.HP=80;SkillExecutionResult result=run(session,hero.pos);assertEquals(SkillExecutionResult.Status.APPLIED,result.status());assertEquals(86,hero.HP);ResourceState rage=hero.gameplayComponentsV6RuntimeBridge().state().resources().get(new ResourceRef(session.state().draft().resources().get(0).id(),""));assertEquals(3,rage.current());String trace=result.trace().serialize();assertEquals(1,count(trace,"cost_commit|variant=RESOURCE"));assertEquals(2,count(trace,"slot=primary status=APPLIED"));assertEquals(2,count(trace,"slot=secondary activation_policy=IMMEDIATE_ON_PRIMARY_SUCCESS status=APPLIED"));}

	@Test public void postPaymentPrimaryFailureIsVisibleNotRefundedAndSkipsSecondary(){PlayerBuildSession session=P04TestBuilds.twoResources("p04-post-pay");String id=P04TestBuilds.createSkill(session,"Overdraw","RESOURCE_OPERATION","RESOURCE_OPERATION",true);set(session,"effects.primary","RESOURCE_OPERATION","operation_variant","DRAIN");session.dispatch(new BuilderCommand.SetTypedSkillReference(id,"effects.primary","RESOURCE_OPERATION","resource",P04TestBuilds.resourceRef(session,0)));set(session,"effects.primary","RESOURCE_OPERATION","amount","2");session.dispatch(new BuilderCommand.SelectEffectFamily(id,"IMMEDIATE_SECONDARY","RESOURCE_OPERATION"));session.dispatch(new BuilderCommand.SelectEffectVariant(id,"IMMEDIATE_SECONDARY","RESOURCE_OPERATION"));session.dispatch(new BuilderCommand.SetTypedSkillReference(id,"effects.secondary","RESOURCE_OPERATION","resource",P04TestBuilds.resourceRef(session,1)));set(session,"effects.secondary","RESOURCE_OPERATION","amount","1");session.dispatch(new BuilderCommand.SetCost(id,"RESOURCE"));session.dispatch(new BuilderCommand.SetTypedSkillReference(id,"cost","RESOURCE","resource",P04TestBuilds.resourceRef(session,0)));set(session,"cost","RESOURCE","amount","4");P04TestBuilds.clean(session);SkillExecutionResult result=run(session,hero.pos);assertEquals(SkillExecutionResult.Status.UNSUPPORTED_PARAMETERS,result.status());ResourceState rage=hero.gameplayComponentsV6RuntimeBridge().state().resources().get(new ResourceRef(session.state().draft().resources().get(0).id(),""));ResourceState focus=hero.gameplayComponentsV6RuntimeBridge().state().resources().get(new ResourceRef(session.state().draft().resources().get(1).id(),""));assertEquals(1,rage.current());assertEquals(0,focus.current());String trace=result.trace().serialize();assertTrue(trace,trace.contains("post_commit_failure|refund=false slot=primary"));assertFalse(trace,trace.contains("slot=secondary activation_policy"));}

	private SkillExecutionResult run(PlayerBuildSession session,int selected){V6RuleRuntimeBridge bridge=V6RuleRuntimeBridge.install(hero,session.finalizeOrThrow());return bridge.triggerActive(hero,selected,skill(session),800,0,damageGateway());}
	private static String skill(PlayerBuildSession session){return session.state().draft().skills().get(0).id().value();}
	private static void set(PlayerBuildSession session,String path,String variant,String field,String value){session.dispatch(new BuilderCommand.SetTypedSkillField(skill(session),path,variant,field,value));}
	private static int count(String text,String token){int count=0,index=0;while((index=text.indexOf(token,index))>=0){count++;index+=token.length();}return count;}
}
