package com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6;

import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.builder.BuilderCommand;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.builder.PlayerBuildSession;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.identity.DeterministicIdGenerator;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.ref.ResourceRef;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.spec.ResourceSpec;

/** Command-only P04 fixtures. No completed authoring node is injected into a build. */
final class P04TestBuilds {
	private P04TestBuilds(){}
	static PlayerBuildSession twoResources(String seed){PlayerBuildSession session=PlayerBuildSession.empty(new DeterministicIdGenerator(seed));session.dispatch(new BuilderCommand.CreateResource("Rage"));String rage=resourceId(session,0);session.dispatch(new BuilderCommand.EditResourceField(rage,"initial_value","5"));session.dispatch(new BuilderCommand.EditResourceField(rage,"hud.presentation_key","rage"));session.dispatch(new BuilderCommand.CreateResource("Focus"));String focus=resourceId(session,1);session.dispatch(new BuilderCommand.EditResourceField(focus,"maximum","5"));session.dispatch(new BuilderCommand.EditResourceField(focus,"hud.order","1"));session.dispatch(new BuilderCommand.EditResourceField(focus,"hud.presentation_key","focus"));clean(session);return session;}
	static PlayerBuildSession classConvert(String seed){PlayerBuildSession session=twoResources(seed);String rage=resourceId(session,0),focus=resourceId(session,1);session.dispatch(new BuilderCommand.CreateClassOperation("Rage to Focus","RESOURCE_OPERATION"));String operation=session.state().draft().classOperations().get(0).id().value();session.dispatch(new BuilderCommand.SetFieldValue(operation,"RESOURCE_OPERATION","operation_variant","CONVERT"));session.dispatch(new BuilderCommand.SetReference(operation,"RESOURCE_OPERATION","operation.source",new ResourceRef(session.state().draft().resources().get(0).id(),"Rage")));session.dispatch(new BuilderCommand.SetReference(operation,"RESOURCE_OPERATION","operation.target",new ResourceRef(session.state().draft().resources().get(1).id(),"Focus")));session.dispatch(new BuilderCommand.SetFieldValue(operation,"RESOURCE_OPERATION","operation.source_amount","2"));session.dispatch(new BuilderCommand.SetFieldValue(operation,"RESOURCE_OPERATION","operation.target_amount","5"));clean(session);return session;}
	static PlayerBuildSession resourceSkillConvert(String seed){PlayerBuildSession session=twoResources(seed);String id=createSkill(session,"Convert Skill","RESOURCE_OPERATION","RESOURCE_OPERATION",true);session.dispatch(new BuilderCommand.SetTypedSkillField(id,"effects.primary","RESOURCE_OPERATION","operation_variant","CONVERT"));session.dispatch(new BuilderCommand.SetTypedSkillReference(id,"effects.primary","RESOURCE_OPERATION","source",new ResourceRef(session.state().draft().resources().get(0).id(),"Rage")));session.dispatch(new BuilderCommand.SetTypedSkillReference(id,"effects.primary","RESOURCE_OPERATION","target",new ResourceRef(session.state().draft().resources().get(1).id(),"Focus")));session.dispatch(new BuilderCommand.SetTypedSkillField(id,"effects.primary","RESOURCE_OPERATION","source_amount","2"));session.dispatch(new BuilderCommand.SetTypedSkillField(id,"effects.primary","RESOURCE_OPERATION","target_amount","5"));clean(session);return session;}
	static PlayerBuildSession effect(String seed,String family,String variant,boolean self){PlayerBuildSession session=PlayerBuildSession.empty(new DeterministicIdGenerator(seed));createSkill(session,variant,family,variant,self);clean(session);return session;}
	static String createSkill(PlayerBuildSession session,String name,String family,String variant,boolean self){session.dispatch(new BuilderCommand.CreateSkill(name));String id=session.state().draft().skills().get(session.state().draft().skills().size()-1).id().value();session.dispatch(new BuilderCommand.SelectTriggerVariant(id,"ACTIVE"));session.dispatch(new BuilderCommand.SelectConditionVariant(id,"ALWAYS"));session.dispatch(new BuilderCommand.SelectEffectFamily(id,"PRIMARY",family));session.dispatch(new BuilderCommand.SelectEffectVariant(id,"PRIMARY",variant));session.dispatch(new BuilderCommand.SetDelivery(id,self?"SELF":"DIRECT"));session.dispatch(new BuilderCommand.SetTargetingSelector(id,self?"SELF":"SELECTED_ACTOR"));session.dispatch(new BuilderCommand.SetTargetingCoverage(id,"SINGLE"));session.dispatch(new BuilderCommand.SetTargetingFilter(id,self?"SELF":"RELATION_ENEMY_EXCLUDE_SELF"));session.dispatch(new BuilderCommand.SetTypedSkillField(id,"targeting","TARGETING","range","5"));session.dispatch(new BuilderCommand.SetModifier(id,"NONE"));session.dispatch(new BuilderCommand.SetCost(id,"NO_COST"));session.dispatch(new BuilderCommand.SetSkillConstraint(id,"NONE"));return id;}
	static String resourceId(PlayerBuildSession session,int index){return session.state().draft().resources().get(index).id().value();}
	static ResourceRef resourceRef(PlayerBuildSession session,int index){ResourceSpec value=session.state().draft().resources().get(index);return new ResourceRef(value.id(),value.displayName().fallback());}
	static void clean(PlayerBuildSession session){if(!session.state().commandDiagnostics().isEmpty())throw new AssertionError(session.state().commandDiagnostics());}
}
