package com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6;

import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.identity.*;import org.junit.Test;
import java.util.HashSet;import java.util.Set;
import static org.junit.Assert.*;

public class StableIdentityAndDisplayNameTest {
	@Test public void generatedIdsAreCanonicalUniqueAndDeterministic(){DeterministicIdGenerator first=new DeterministicIdGenerator("same");DeterministicIdGenerator second=new DeterministicIdGenerator("same");Set<StableId> unique=new HashSet<>();for(int i=0;i<64;i++){StableId a=first.nextId("res");StableId b=second.nextId("res");assertEquals(a,b);assertTrue(StableId.isCanonical(a.value()));assertEquals("res",a.prefix());assertTrue(unique.add(a));}}
	@Test public void migrationIdsArePathAddressedAndReplayable(){MigrationIdGenerator first=new MigrationIdGenerator("build-a");MigrationIdGenerator second=new MigrationIdGenerator("build-a");assertEquals(first.idFor("mark","skills[2].mark"),second.idFor("mark","skills[2].mark"));assertNotEquals(first.idFor("mark","skills[2].mark"),first.idFor("mark","skills[3].mark"));}
	@Test public void storedLegacyIdentityIsBytePreserving(){assertEquals("legacy_mana",StableId.fromStored("legacy_mana").value());}
	@Test public void duplicateRetriesGeneratorCollisionAndMigrationIdentityRemainsValid(){P01Fixtures fixture=new P01Fixtures();IdGenerator collisionThenUnique=new IdGenerator(){private int calls;@Override public StableId nextId(String prefix){return calls++==0?fixture.resource.id():StableId.of("res_00000000000000000000000000000000");}};com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.spec.ClassBuildSpec duplicated=new com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.edit.BuildEditService().duplicate(fixture.declarationsOnly(),fixture.resource.id(),collisionThenUnique);assertEquals(2,duplicated.resources().size());assertEquals("res_00000000000000000000000000000000",duplicated.resources().get(1).id().value());com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.spec.ClassBuildSpec migratedIdentity=fixture.declarationsOnly().toBuilder().resources(java.util.Collections.singletonList(new com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.spec.ResourceSpec(StableId.fromStored("legacy_rage"),DisplayName.of("Legacy"),0,10,0,com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.spec.ResourceSpec.ResourceOverflowPolicy.FAIL,new com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.spec.ResourceSpec.ResourceHudSpec(true,0,"legacy")))).build();assertFalse(new com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.dependency.ClassBuildValidator().validate(migratedIdentity).diagnostics().stream().anyMatch(d->"identity.prefix_mismatch".equals(d.messageKey())));}
	@Test public void displayNameNormalizesTrimsAndCountsCodePoints(){assertEquals("é",DisplayName.of("  e\u0301  ").text());assertEquals("😀",DisplayName.of("😀").text());assertEquals(DisplayName.of("同名"),DisplayName.of("同名"));}
	@Test(expected=IllegalArgumentException.class)public void displayNameRejectsControlCharacters(){DisplayName.of("bad\nname");}
	@Test(expected=IllegalArgumentException.class)public void displayNameRejectsMoreThanTwentyFourCodePoints(){DisplayName.of("1234567890123456789012345");}
}
