package com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6;

import com.shatteredpixel.shatteredpixeldungeon.rules.ClassBuild;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.migration.MigrationResult;import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.save.CanonicalBuildCodec;import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.save.CanonicalRuntimeCodec;import com.shatteredpixel.shatteredpixeldungeon.rules.migration.v5.V5ToV6Migration;
import org.junit.Test;import static org.junit.Assert.*;

public class V5MigrationSkeletonTest {
	@Test public void resourceDeclarationAndCurrentStateAreSeparatedAndReplayable(){ClassBuild legacy=new ClassBuild();legacy.name="Legacy Build";legacy.resources.clear();com.shatteredpixel.shatteredpixeldungeon.rules.ResourceSpec resource=legacyResource("legacy_rage","Rage");resource.initialValue=5;resource.current=3;legacy.resources.add(resource);V5ToV6Migration migration=new V5ToV6Migration();MigrationResult first=migration.migrate(legacy,"migration-fixture");MigrationResult second=migration.migrate(legacy,"migration-fixture");assertEquals(6,first.build().schemaVersion());assertEquals("legacy_rage",first.build().resources().get(0).id().value());assertEquals(5,first.build().resources().get(0).initialValue());assertEquals(3,first.runtime().resources().values().iterator().next().current());assertEquals(first.build().buildId(),first.runtime().buildId());assertEquals(new CanonicalBuildCodec().serialize(first.build()),new CanonicalBuildCodec().serialize(second.build()));assertEquals(new CanonicalRuntimeCodec().serialize(first.runtime()),new CanonicalRuntimeCodec().serialize(second.runtime()));assertTrue(first.report().changes().stream().anyMatch(c->"MOVED_TO_RUNTIME_STATE".equals(c.kind())));}
	@Test public void emptyAndDuplicateIdsReceiveDeterministicNewIdsAndReportThem(){ClassBuild legacy=new ClassBuild();legacy.resources.clear();for(int i=0;i<3;i++)legacy.resources.add(legacyResource(i==0?"":"same","R"+i));MigrationResult result=new V5ToV6Migration().migrate(legacy,"duplicate-fixture");assertEquals(3,result.build().resources().stream().map(v->v.id()).distinct().count());assertEquals(2,result.report().warnings().stream().filter(w->w.code().endsWith("ID_REPLACED")).count());}
	@Test public void everyPresentUnmigratedLegacyCategoryIsReportedAndNotClaimedPreserved(){ClassBuild legacy=new ClassBuild();legacy.skills.add(new com.shatteredpixel.shatteredpixeldungeon.rules.SkillSpec());legacy.laws.add(com.shatteredpixel.shatteredpixeldungeon.rules.ClassLaw.HEALING_TO_SHIELD);legacy.traits.add(new com.shatteredpixel.shatteredpixeldungeon.rules.TraitSpec());legacy.restrictions.add(com.shatteredpixel.shatteredpixeldungeon.rules.Restriction.FRAIL);legacy.operations.add(new com.shatteredpixel.shatteredpixeldungeon.rules.ClassOperationSpec());MigrationResult result=new V5ToV6Migration().migrate(legacy,"unmigrated-semantics");assertFalse(result.report().behaviorPreserved());String[] paths={"gameplayComponents","skills","laws","traits","restrictions","operations","startingKit","progression","baseBudget"};for(String path:paths){assertTrue(path,result.report().changes().stream().anyMatch(c->path.equals(c.path())&&"DEFERRED".equals(c.kind())));assertTrue(path,result.report().warnings().stream().anyMatch(w->path.equals(w.path())&&"UNMIGRATED_SEMANTICS".equals(w.code())));}}
	@Test public void defaultBasicAttackAlonePreventsFalsePreservationClaim(){ClassBuild legacy=new ClassBuild();legacy.resources.clear();MigrationResult result=new V5ToV6Migration().migrate(legacy,"default-basic-attack");assertFalse(result.report().behaviorPreserved());assertTrue(result.report().changes().stream().anyMatch(c->"gameplayComponents".equals(c.path())&&"DEFERRED".equals(c.kind())));}
	@Test(expected=IllegalArgumentException.class)public void unknownLegacySchemaIsNotGuessed(){ClassBuild legacy=new ClassBuild();legacy.schemaVersion=99;new V5ToV6Migration().migrate(legacy,"bad-schema");}
	private static com.shatteredpixel.shatteredpixeldungeon.rules.ResourceSpec legacyResource(String id,String name){com.shatteredpixel.shatteredpixeldungeon.rules.ResourceSpec resource=new com.shatteredpixel.shatteredpixeldungeon.rules.ResourceSpec();resource.id=id;resource.name=name;resource.minimum=0;resource.capacity=10;resource.initialValue=0;resource.current=0;return resource;}
}
