package com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.builder;

import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.catalog.GameplayVariantCatalog;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.identity.StableId;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.ref.*;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.spec.ClassBuildSpec;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.spec.ResourceSpec;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.spec.resource.*;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.spec.skill.*;
import java.util.ArrayList;import java.util.List;

/** Exact typed edit functions for the P04 SkillSpec surface. No reflective payload mutation. */
final class SkillDraftEditor {
	static final String PRIMARY="PRIMARY",IMMEDIATE_SECONDARY="IMMEDIATE_SECONDARY";
	ClassBuildSpec selectTrigger(ClassBuildSpec build,String skillId,String variant){exposed("TRIGGER",variant);if(!ActiveTriggerSpec.VARIANT.equals(variant))throw unsupported("trigger",variant);SkillSpec s=require(build,skillId);return replace(build,s.withActivation(new ActiveTriggerSpec(s.activation().nodeId())));}
	ClassBuildSpec selectCondition(ClassBuildSpec build,String skillId,String variant,StableId conditionId,StableId unresolvedResource){SkillSpec s=require(build,skillId);if(AlwaysCondition.VARIANT.equals(variant)){exposed("CONDITION",variant);return replace(build,s.withCondition(AllOfCondition.always()));}exposed("CONDITION",variant);if("BUILTIN_STAT_COMPARE".equals(variant))return replace(build,s.withCondition(new AllOfCondition(java.util.Collections.<ConditionExpr>singletonList(new BuiltinStatCompareCondition(conditionId,SubjectSelector.CLASS_OWNER,BuiltinStatRef.HP_PERCENT,ComparisonOperator.LTE,new FixedValueSpec(50))))));if("RESOURCE_COMPARE".equals(variant))return replace(build,s.withCondition(new AllOfCondition(java.util.Collections.<ConditionExpr>singletonList(new ResourceCompareCondition(conditionId,ResourceHolderSelector.CLASS_OWNER,new ResourceRef(unresolvedResource,""),ComparisonOperator.GTE,1)))));throw unsupported("condition",variant);}
	ClassBuildSpec selectEffectFamily(ClassBuildSpec build,String skillId,String slot,String family,StableId newEffectId){if(IMMEDIATE_SECONDARY.equals(slot)&&"NONE".equals(family)){SkillSpec s=require(build,skillId);return replace(build,s.withEffects(s.effects().withSecondary(null)));}EffectFamily selected=en(EffectFamily.class,family);if(!(selected==EffectFamily.DAMAGE||selected==EffectFamily.STATUS||selected==EffectFamily.MOVEMENT||selected==EffectFamily.RECOVERY_DEFENSE||selected==EffectFamily.RESOURCE_OPERATION))throw unsupported("effect family",family);SkillSpec s=require(build,skillId);if(PRIMARY.equals(slot))return replace(build,s.withEffects(s.effects().withPrimary(new UnconfiguredEffectSpec(s.effects().primary().effectId(),selected))));if(IMMEDIATE_SECONDARY.equals(slot)){StableId id=s.effects().secondary()==null?newEffectId:s.effects().secondary().effect().effectId();return replace(build,s.withEffects(s.effects().withSecondary(new SecondaryEffectSpec(new UnconfiguredEffectSpec(id,selected),new ImmediateOnPrimarySuccess()))));}throw new IllegalArgumentException("unknown effect slot "+slot);}
	ClassBuildSpec selectEffectVariant(ClassBuildSpec build,String skillId,String slot,String variant,StableId operationId,StableId firstRef,StableId secondRef){exposed("EFFECT",variant);SkillSpec s=require(build,skillId);EffectSpec old=effect(s,slot);if(!(old instanceof UnconfiguredEffectSpec))throw new IllegalArgumentException("select effect family before variant");EffectVariantKey key=en(EffectVariantKey.class,variant);if(((UnconfiguredEffectSpec)old).selectedFamily()!=family(key))throw new IllegalArgumentException("effect family/variant mismatch");EffectSpec next=defaultEffect(old.effectId(),key,operationId,firstRef,secondRef);return replace(build,s.withEffects(withEffect(s.effects(),slot,next)));}
	ClassBuildSpec setTargetingSelector(ClassBuildSpec build,String skillId,String variant){exposed("SELECTOR",variant);SkillSpec s=require(build,skillId);SelectorSpec value;if(SelectedActorSelector.VARIANT.equals(variant))value=new SelectedActorSelector();else if("SELF".equals(variant))value=new SelfSelector();else if("SELECTED_CELL".equals(variant))value=new SelectedCellSelector();else throw unsupported("selector",variant);return replace(build,s.withTargeting(s.targeting().withSelector(value)));}
	ClassBuildSpec setTargetingCoverage(ClassBuildSpec build,String skillId,String variant){exposed("COVERAGE",variant);SkillSpec s=require(build,skillId);CoverageSpec value;if(SingleCoverageSpec.VARIANT.equals(variant))value=new SingleCoverageSpec();else if("ADJACENT".equals(variant))value=new AdjacentCoverageSpec();else if("RADIUS".equals(variant))value=new RadiusCoverageSpec(1);else if("LINE".equals(variant))value=new LineCoverageSpec(3,1);else throw unsupported("coverage",variant);TargetingSpec target=s.targeting().withCoverage(value);if(value instanceof SingleCoverageSpec)target=target.withMaximumTargets(1);return replace(build,s.withTargeting(target));}
	ClassBuildSpec setTargetingFilter(ClassBuildSpec build,String skillId,String variant){exposed("FILTER",variant);SkillSpec s=require(build,skillId);EntityFilterExpr value;if("RELATION_ENEMY_EXCLUDE_SELF".equals(variant))value=new RelationFilterSpec(RelationFilterSpec.RelationAlignment.ENEMY,false);else if("RELATION_ALLY_EXCLUDE_SELF".equals(variant))value=new RelationFilterSpec(RelationFilterSpec.RelationAlignment.ALLY,false);else if("RELATION_ALLY_INCLUDE_SELF".equals(variant))value=new RelationFilterSpec(RelationFilterSpec.RelationAlignment.ALLY,true);else if("ANY_ACTOR".equals(variant))value=new AnyActorFilterSpec();else if("SELF".equals(variant))value=new SelfFilterSpec();else throw unsupported("filter",variant);return replace(build,s.withTargeting(s.targeting().withFilter(value)));}
	ClassBuildSpec setDelivery(ClassBuildSpec build,String skillId,String variant){exposed("DELIVERY",variant);SkillSpec s=require(build,skillId);StableId id=s.delivery().nodeId();DeliverySpec value;if("DIRECT".equals(variant))value=new DirectDeliverySpec(id,false);else if("SELF".equals(variant))value=new SelfDeliverySpec(id);else if("CONTACT".equals(variant))value=new ContactDeliverySpec(id);else if("PROJECTILE".equals(variant))value=new ProjectileDeliverySpec(id,ProjectileDeliverySpec.ProjectilePathPolicy.REQUIRE_CLEAR_BALLISTIC_PATH,1,"projectile.default");else if("TRACE".equals(variant))value=new TraceDeliverySpec(id,1,true);else if("GROUND".equals(variant))value=new GroundDeliverySpec(id,true);else throw unsupported("delivery",variant);return replace(build,s.withDelivery(value));}
	ClassBuildSpec setModifier(ClassBuildSpec build,String skillId,String variant,StableId newModifierId){SkillSpec s=require(build,skillId);if("NONE".equals(variant))return replace(build,s.withModifier(null));exposed("MODIFIER",variant);StableId id=s.modifier()==null?newModifierId:s.modifier().nodeId();ModifierSpec value;if("REPEAT".equals(variant))value=new RepeatModifierSpec(id,1,RepeatModifierSpec.RepeatTargetPolicy.SAME_TARGET);else if("INTENSITY".equals(variant))value=new IntensityModifierSpec(id,2,1);else if("EXTEND_DURATION".equals(variant))value=new ExtendDurationModifierSpec(id,1);else if("PIERCE".equals(variant))value=new PierceModifierSpec(id,1);else if("BOUNCE".equals(variant))value=new BounceModifierSpec(id,1,2);else throw unsupported("modifier",variant);return replace(build,s.withModifier(value));}
	ClassBuildSpec setCost(ClassBuildSpec build,String skillId,String variant,StableId unresolvedResource){exposed("COST",variant);SkillSpec s=require(build,skillId);StableId id=s.cost().nodeId();CostSpec value;if("NO_COST".equals(variant))value=new NoCostSpec(id);else if("RESOURCE".equals(variant))value=new ResourceCostSpec(id,ResourceHolderSelector.CLASS_OWNER,new ResourceRef(unresolvedResource,""),1);else if("HP".equals(variant))value=HpCostSpec.safeDefault(id,1);else if("ACTION_TIME".equals(variant))value=new ActionTimeCostSpec(id,1);else if("COOLDOWN".equals(variant))value=new CooldownCostSpec(id,1);else if("ITEM".equals(variant))value=new ItemCostSpec(id,new ItemFilterSpec(ItemFilterSpec.ItemCategory.ANY_CONSUMABLE),1);else throw unsupported("cost",variant);return replace(build,s.withCost(value));}
	ClassBuildSpec setConstraint(ClassBuildSpec build,String skillId,String variant){if(!"NONE".equals(variant))throw unsupported("skill constraint",variant);return replace(build,require(build,skillId).withConstraint(null));}

	ClassBuildSpec setField(ClassBuildSpec build,String skillId,String ownerPath,String variant,String field,String raw){SkillSpec s=require(build,skillId);
		if(ownerPath.startsWith("effects.")){String slot="effects.primary".equals(ownerPath)?PRIMARY:IMMEDIATE_SECONDARY;EffectSpec e=effect(s,slot);EffectSpec changed=setEffectField(e,variant,field,raw);return replace(build,s.withEffects(withEffect(s.effects(),slot,changed)));}
		if("delivery".equals(ownerPath)){DeliverySpec d=s.delivery();if(d instanceof DirectDeliverySpec&&"requires_line_of_sight".equals(field))d=((DirectDeliverySpec)d).withRequiresLineOfSight(bool(raw));else if(d instanceof TraceDeliverySpec&&"width".equals(field))d=new TraceDeliverySpec(d.nodeId(),integer(raw),((TraceDeliverySpec)d).stopsAtFirstBlockingCell());else if(d instanceof TraceDeliverySpec&&"stops_at_first_blocking_cell".equals(field))d=new TraceDeliverySpec(d.nodeId(),((TraceDeliverySpec)d).width(),bool(raw));else if(d instanceof GroundDeliverySpec&&"requires_visible_cell".equals(field))d=new GroundDeliverySpec(d.nodeId(),bool(raw));else throw new IllegalArgumentException("unknown delivery field");return replace(build,s.withDelivery(d));}
		if("targeting".equals(ownerPath)){TargetingSpec t=s.targeting();if("range".equals(field))t=t.withRange(integer(raw));else if("maximum_targets".equals(field))t=t.withMaximumTargets(integer(raw));else if("radius".equals(field))t=t.withCoverage(new RadiusCoverageSpec(integer(raw)));else if("line_length".equals(field))t=t.withCoverage(new LineCoverageSpec(integer(raw),t.coverage() instanceof LineCoverageSpec?((LineCoverageSpec)t.coverage()).width():1));else if("line_width".equals(field))t=t.withCoverage(new LineCoverageSpec(t.coverage() instanceof LineCoverageSpec?((LineCoverageSpec)t.coverage()).length():3,integer(raw)));else throw new IllegalArgumentException("unknown targeting field "+field);return replace(build,s.withTargeting(t));}
		if("modifier".equals(ownerPath)){ModifierSpec m=s.modifier();if(m==null)throw new IllegalArgumentException("modifier absent");if(m instanceof RepeatModifierSpec&&"repeat_count".equals(field))m=new RepeatModifierSpec(m.nodeId(),integer(raw),RepeatModifierSpec.RepeatTargetPolicy.SAME_TARGET);else if(m instanceof IntensityModifierSpec&&"numerator".equals(field))m=new IntensityModifierSpec(m.nodeId(),integer(raw),((IntensityModifierSpec)m).denominator());else if(m instanceof IntensityModifierSpec&&"denominator".equals(field))m=new IntensityModifierSpec(m.nodeId(),((IntensityModifierSpec)m).numerator(),integer(raw));else if(m instanceof ExtendDurationModifierSpec&&"additional_turns".equals(field))m=new ExtendDurationModifierSpec(m.nodeId(),integer(raw));else if(m instanceof PierceModifierSpec&&"additional_targets".equals(field))m=new PierceModifierSpec(m.nodeId(),integer(raw));else if(m instanceof BounceModifierSpec&&"bounces".equals(field))m=new BounceModifierSpec(m.nodeId(),integer(raw),((BounceModifierSpec)m).bounceRange());else if(m instanceof BounceModifierSpec&&"bounce_range".equals(field))m=new BounceModifierSpec(m.nodeId(),((BounceModifierSpec)m).bounces(),integer(raw));else throw new IllegalArgumentException("unknown modifier field");return replace(build,s.withModifier(m));}
		if("cost".equals(ownerPath)){CostSpec c=s.cost();if(c instanceof ItemCostSpec&&"item_category".equals(field))c=new ItemCostSpec(c.nodeId(),new ItemFilterSpec(en(ItemFilterSpec.ItemCategory.class,raw)),((ItemCostSpec)c).count());else{int n=integer(raw);if(c instanceof ResourceCostSpec&&"amount".equals(field))c=new ResourceCostSpec(c.nodeId(),ResourceHolderSelector.CLASS_OWNER,((ResourceCostSpec)c).resource(),n);else if(c instanceof HpCostSpec&&"amount".equals(field))c=HpCostSpec.safeDefault(c.nodeId(),n);else if(c instanceof ActionTimeCostSpec&&"turns".equals(field))c=new ActionTimeCostSpec(c.nodeId(),n);else if(c instanceof CooldownCostSpec&&"turns".equals(field))c=new CooldownCostSpec(c.nodeId(),n);else if(c instanceof ItemCostSpec&&"count".equals(field))c=new ItemCostSpec(c.nodeId(),((ItemCostSpec)c).itemFilter(),n);else throw new IllegalArgumentException("unknown cost field");}return replace(build,s.withCost(c));}
		if("condition.0".equals(ownerPath)){ConditionExpr leaf=((AllOfCondition)s.condition()).children().get(0);ConditionExpr changed;if(leaf instanceof BuiltinStatCompareCondition){BuiltinStatCompareCondition x=(BuiltinStatCompareCondition)leaf;changed=new BuiltinStatCompareCondition(x.nodeId(),"subject".equals(field)?en(SubjectSelector.class,raw):x.subject(),"stat".equals(field)?en(BuiltinStatRef.class,raw):x.stat(),"operator".equals(field)?en(ComparisonOperator.class,raw):x.operator(),"value".equals(field)?new FixedValueSpec(integer(raw)):x.value());}else{ResourceCompareCondition x=(ResourceCompareCondition)leaf;changed=new ResourceCompareCondition(x.nodeId(),x.holder(),x.resource(),"operator".equals(field)?en(ComparisonOperator.class,raw):x.operator(),"value".equals(field)?integer(raw):x.value());}return replace(build,s.withCondition(new AllOfCondition(java.util.Collections.singletonList(changed))));}
		throw new IllegalArgumentException("unknown typed owner path "+ownerPath);
	}
	ClassBuildSpec setReference(ClassBuildSpec build,String skillId,String ownerPath,String variant,String field,TypedRef reference){SkillSpec s=require(build,skillId);if(reference.kind()!=RefKind.RESOURCE)throw new IllegalArgumentException("P04 skill reference requires RESOURCE");ResourceRef ref=new ResourceRef(reference.targetId(),reference.lastKnownDisplayName());
		if(ownerPath.startsWith("effects.")){String slot="effects.primary".equals(ownerPath)?PRIMARY:IMMEDIATE_SECONDARY;EffectSpec e=effect(s,slot);if(!(e instanceof ResourceOperationEffectSpec))throw new IllegalArgumentException("resource operation effect required");ResourceOperationEffectSpec ro=(ResourceOperationEffectSpec)e;ResourceOperationSpec changed=rebind(ro.operation(),field,ref);return replace(build,s.withEffects(withEffect(s.effects(),slot,new ResourceOperationEffectSpec(ro.effectId(),changed))));}
		if("cost".equals(ownerPath)&&s.cost() instanceof ResourceCostSpec&&"resource".equals(field)){ResourceCostSpec x=(ResourceCostSpec)s.cost();return replace(build,s.withCost(new ResourceCostSpec(x.nodeId(),x.holder(),ref,x.amount())));}
		if("condition.0".equals(ownerPath)&&((AllOfCondition)s.condition()).children().get(0) instanceof ResourceCompareCondition&&"resource".equals(field)){ResourceCompareCondition x=(ResourceCompareCondition)((AllOfCondition)s.condition()).children().get(0);return replace(build,s.withCondition(new AllOfCondition(java.util.Collections.<ConditionExpr>singletonList(new ResourceCompareCondition(x.nodeId(),x.holder(),ref,x.operator(),x.value())))));}
		throw new IllegalArgumentException("unknown P04 reference field "+ownerPath+"."+field);
	}

	private static EffectSpec setEffectField(EffectSpec e,String variant,String field,String raw){if(!e.variantKey().name().equals(variant))throw new IllegalArgumentException("effect variant mismatch");
		if(e instanceof DirectDamageEffectSpec){DirectDamageEffectSpec x=(DirectDamageEffectSpec)e;if("amount".equals(field))return x.withAmount(new FixedValueSpec(integer(raw)));if("damage_type".equals(field)){DirectDamageEffectSpec.DamageType t=en(DirectDamageEffectSpec.DamageType.class,raw);if(t!=DirectDamageEffectSpec.DamageType.UNTYPED)throw unsupported("damage type",raw);return x.withDamageType(t);}if("defense_policy".equals(field))return x.withDefensePolicy(en(DirectDamageEffectSpec.NativeDefensePolicy.class,raw));}
		if(e instanceof PercentMaxHpDamageEffectSpec){PercentMaxHpDamageEffectSpec x=(PercentMaxHpDamageEffectSpec)e;return new PercentMaxHpDamageEffectSpec(x.effectId(),"percent".equals(field)?integer(raw):x.percent(),"absolute_cap".equals(field)?integer(raw):x.absoluteCap(),x.protectedTargetPolicy());}
		if(e instanceof MissingHpDamageEffectSpec){MissingHpDamageEffectSpec x=(MissingHpDamageEffectSpec)e;return new MissingHpDamageEffectSpec(x.effectId(),"base_amount".equals(field)?new FixedValueSpec(integer(raw)):x.baseAmount(),"missing_hp_numerator".equals(field)?integer(raw):x.missingHpNumerator(),"missing_hp_denominator".equals(field)?integer(raw):x.missingHpDenominator(),"absolute_cap".equals(field)?integer(raw):x.absoluteCap(),x.damageType());}
		if(e instanceof ExecuteEffectSpec){ExecuteEffectSpec x=(ExecuteEffectSpec)e;return new ExecuteEffectSpec(x.effectId(),"hp_percent_threshold".equals(field)?integer(raw):x.hpPercentThreshold(),x.fallbackDamage(),x.protectedTargetPolicy());}
		if(e instanceof ApplyStatusEffectSpec){ApplyStatusEffectSpec x=(ApplyStatusEffectSpec)e;return new ApplyStatusEffectSpec(x.effectId(),"status".equals(field)?en(StatusRef.class,raw):x.status(),"intensity".equals(field)?new FixedValueSpec(integer(raw)):x.intensity(),"duration_turns".equals(field)?DurationSpec.turns(integer(raw)):x.duration(),x.stacking());}
		if(e instanceof PushEffectSpec){PushEffectSpec x=(PushEffectSpec)e;return new PushEffectSpec(x.effectId(),integer(raw),x.collisionPolicy());}if(e instanceof PullEffectSpec){PullEffectSpec x=(PullEffectSpec)e;return new PullEffectSpec(x.effectId(),integer(raw),x.collisionPolicy());}if(e instanceof ThrowEffectSpec){ThrowEffectSpec x=(ThrowEffectSpec)e;return new ThrowEffectSpec(x.effectId(),integer(raw),x.collisionPolicy());}
		if(e instanceof DashEffectSpec){DashEffectSpec x=(DashEffectSpec)e;return new DashEffectSpec(x.effectId(),integer(raw),x.pathPolicy());}if(e instanceof TeleportEffectSpec){TeleportEffectSpec x=(TeleportEffectSpec)e;return new TeleportEffectSpec(x.effectId(),integer(raw),x.destinationPolicy());}
		if(e instanceof HealEffectSpec)return new HealEffectSpec(e.effectId(),new FixedValueSpec(integer(raw)));if(e instanceof BarrierEffectSpec)return new BarrierEffectSpec(e.effectId(),new FixedValueSpec(integer(raw)),((BarrierEffectSpec)e).overflowPolicy());if(e instanceof TemporaryHpEffectSpec){TemporaryHpEffectSpec x=(TemporaryHpEffectSpec)e;return new TemporaryHpEffectSpec(x.effectId(),"amount".equals(field)?new FixedValueSpec(integer(raw)):x.amount(),"duration_turns".equals(field)?DurationSpec.turns(integer(raw)):x.duration(),x.stacking());}if(e instanceof MitigateEffectSpec){MitigateEffectSpec x=(MitigateEffectSpec)e;return new MitigateEffectSpec(x.effectId(),"percent".equals(field)?integer(raw):x.percent(),"duration_turns".equals(field)?DurationSpec.turns(integer(raw)):x.duration(),x.stacking());}if(e instanceof RedirectDamageEffectSpec){RedirectDamageEffectSpec x=(RedirectDamageEffectSpec)e;return new RedirectDamageEffectSpec(x.effectId(),"percent".equals(field)?integer(raw):x.percent(),"recipient".equals(field)?en(SubjectSelector.class,raw):x.recipient(),"duration_turns".equals(field)?DurationSpec.turns(integer(raw)):x.duration());}if(e instanceof CleanseEffectSpec)return new CleanseEffectSpec(e.effectId(),((CleanseEffectSpec)e).filter(),integer(raw));
		if(e instanceof ResourceOperationEffectSpec){ResourceOperationEffectSpec x=(ResourceOperationEffectSpec)e;return new ResourceOperationEffectSpec(x.effectId(),editOperation(x.operation(),field,raw));}
		throw new IllegalArgumentException("unknown effect field "+field);
	}
	private static ResourceOperationSpec editOperation(ResourceOperationSpec op,String field,String raw){if("operation_variant".equals(field)){ResourceOperationSpec.Variant v=en(ResourceOperationSpec.Variant.class,raw);ResourceRef first=op.referencedResources().get(0),second=op.referencedResources().size()>1?op.referencedResources().get(1):new ResourceRef(StableId.fromStored("unresolved_resource_secondary"),"");return defaultOperation(op.operationId(),v,first,second);}if(op instanceof GainResourceSpec){GainResourceSpec x=(GainResourceSpec)op;return new GainResourceSpec(x.operationId(),x.holder(),x.resource(),"amount".equals(field)?new FixedValueSpec(integer(raw)):x.amount(),"overflow_policy".equals(field)?en(ResourceSpec.ResourceOverflowPolicy.class,raw):x.overflowPolicy());}if(op instanceof DrainResourceSpec){DrainResourceSpec x=(DrainResourceSpec)op;return new DrainResourceSpec(x.operationId(),x.holder(),x.resource(),"amount".equals(field)?new FixedValueSpec(integer(raw)):x.amount(),"insufficient_policy".equals(field)?en(DrainResourceSpec.InsufficientResourcePolicy.class,raw):x.insufficientPolicy());}if(op instanceof SetResourceSpec){SetResourceSpec x=(SetResourceSpec)op;return new SetResourceSpec(x.operationId(),x.holder(),x.resource(),new FixedValueSpec(integer(raw)));}if(op instanceof ConvertResourceSpec){ConvertResourceSpec x=(ConvertResourceSpec)op;return new ConvertResourceSpec(x.operationId(),x.holder(),x.source(),"source_amount".equals(field)?integer(raw):x.sourceAmount(),x.target(),"target_amount".equals(field)?integer(raw):x.targetAmount(),ConvertResourceSpec.ConversionPolicy.EXACT_ATOMIC,ResourceSpec.ResourceOverflowPolicy.FAIL);}if(op instanceof ReserveResourceSpec){ReserveResourceSpec x=(ReserveResourceSpec)op;return new ReserveResourceSpec(x.operationId(),x.holder(),x.resource(),"amount".equals(field)?integer(raw):x.amount(),"duration_turns".equals(field)?integer(raw):x.durationTurns(),x.expiryPolicy());}if(op instanceof SuppressResourceSpec){SuppressResourceSpec x=(SuppressResourceSpec)op;return new SuppressResourceSpec(x.operationId(),x.holder(),x.resource(),integer(raw),x.mode());}throw new IllegalArgumentException("operation has no field "+field);}
	private static ResourceOperationSpec rebind(ResourceOperationSpec op,String field,ResourceRef ref){if(op instanceof GainResourceSpec){GainResourceSpec x=(GainResourceSpec)op;return new GainResourceSpec(x.operationId(),x.holder(),ref,x.amount(),x.overflowPolicy());}if(op instanceof DrainResourceSpec){DrainResourceSpec x=(DrainResourceSpec)op;return new DrainResourceSpec(x.operationId(),x.holder(),ref,x.amount(),x.insufficientPolicy());}if(op instanceof SetResourceSpec){SetResourceSpec x=(SetResourceSpec)op;return new SetResourceSpec(x.operationId(),x.holder(),ref,x.value());}if(op instanceof ClearResourceSpec){ClearResourceSpec x=(ClearResourceSpec)op;return new ClearResourceSpec(x.operationId(),x.holder(),ref);}if(op instanceof ReserveResourceSpec){ReserveResourceSpec x=(ReserveResourceSpec)op;return new ReserveResourceSpec(x.operationId(),x.holder(),ref,x.amount(),x.durationTurns(),x.expiryPolicy());}if(op instanceof SuppressResourceSpec){SuppressResourceSpec x=(SuppressResourceSpec)op;return new SuppressResourceSpec(x.operationId(),x.holder(),ref,x.durationTurns(),x.mode());}ConvertResourceSpec x=(ConvertResourceSpec)op;return new ConvertResourceSpec(x.operationId(),x.holder(),"source".equals(field)?ref:x.source(),x.sourceAmount(),"target".equals(field)?ref:x.target(),x.targetAmount(),x.conversionPolicy(),x.targetOverflowPolicy());}
	private static EffectSpec defaultEffect(StableId id,EffectVariantKey key,StableId opId,StableId first,StableId second){switch(key){case DIRECT_DAMAGE:return new DirectDamageEffectSpec(id,new FixedValueSpec(1),DirectDamageEffectSpec.DamageType.UNTYPED,DirectDamageEffectSpec.NativeDefensePolicy.SPD_NATIVE);case PERCENT_MAX_HP_DAMAGE:return new PercentMaxHpDamageEffectSpec(id,10,10,PercentMaxHpDamageEffectSpec.ProtectedTargetPolicy.APPLY_CAPPED_DAMAGE);case MISSING_HP_DAMAGE:return new MissingHpDamageEffectSpec(id,new FixedValueSpec(1),1,2,20,DirectDamageEffectSpec.DamageType.UNTYPED);case EXECUTE:return new ExecuteEffectSpec(id,20,null,ExecuteEffectSpec.ProtectedTargetPolicy.BLOCK);case APPLY_STATUS:return new ApplyStatusEffectSpec(id,StatusRef.POISON,new FixedValueSpec(1),DurationSpec.turns(3),ApplyStatusEffectSpec.StatusStackingPolicy.SPD_NATIVE);case PUSH:return new PushEffectSpec(id,1,MovementPolicies.CollisionPolicy.STOP_BEFORE_BLOCKED);case PULL:return new PullEffectSpec(id,1,MovementPolicies.CollisionPolicy.STOP_BEFORE_BLOCKED);case THROW:return new ThrowEffectSpec(id,1,MovementPolicies.CollisionPolicy.SPD_NATIVE_COLLISION);case DASH:return new DashEffectSpec(id,3,MovementPolicies.PathPolicy.REQUIRE_CLEAR_PATH);case TELEPORT:return new TeleportEffectSpec(id,3,MovementPolicies.DestinationPolicy.EXACT_CELL_OR_FAIL);case SWAP_POSITION:return new SwapPositionEffectSpec(id,MovementPolicies.SwapLegalityPolicy.BOTH_CELLS_PASSABLE);case HEAL:return new HealEffectSpec(id,new FixedValueSpec(1));case BARRIER:return new BarrierEffectSpec(id,new FixedValueSpec(1),BarrierEffectSpec.BarrierOverflowPolicy.CLAMP_TO_MAX_HP);case TEMPORARY_HP:return new TemporaryHpEffectSpec(id,new FixedValueSpec(1),DurationSpec.turns(3),TemporaryHpEffectSpec.TemporaryHpStackingPolicy.MAX);case MITIGATE:return new MitigateEffectSpec(id,10,DurationSpec.turns(3),MitigateEffectSpec.MitigationStackingPolicy.KEEP_STRONGER);case REDIRECT_DAMAGE:return new RedirectDamageEffectSpec(id,10,SubjectSelector.CLASS_OWNER,DurationSpec.turns(3));case CLEANSE:return new CleanseEffectSpec(id,StatusFilterSpec.anyNegative(),1);case RESOURCE_OPERATION:return new ResourceOperationEffectSpec(id,defaultOperation(opId,ResourceOperationSpec.Variant.GAIN,new ResourceRef(first,""),new ResourceRef(second,"")));default:throw unsupported("effect",key.name());}}
	private static ResourceOperationSpec defaultOperation(StableId id,ResourceOperationSpec.Variant variant,ResourceRef first,ResourceRef second){switch(variant){case GAIN:return new GainResourceSpec(id,ResourceHolderSelector.CLASS_OWNER,first,new FixedValueSpec(1),ResourceSpec.ResourceOverflowPolicy.FAIL);case DRAIN:return new DrainResourceSpec(id,ResourceHolderSelector.CLASS_OWNER,first,new FixedValueSpec(1),DrainResourceSpec.InsufficientResourcePolicy.FAIL);case SET:return new SetResourceSpec(id,ResourceHolderSelector.CLASS_OWNER,first,new FixedValueSpec(1));case CLEAR:return new ClearResourceSpec(id,ResourceHolderSelector.CLASS_OWNER,first);case CONVERT:return new ConvertResourceSpec(id,ResourceHolderSelector.CLASS_OWNER,first,1,second,1,ConvertResourceSpec.ConversionPolicy.EXACT_ATOMIC,ResourceSpec.ResourceOverflowPolicy.FAIL);case RESERVE:return new ReserveResourceSpec(id,ResourceHolderSelector.CLASS_OWNER,first,1,1,ReserveResourceSpec.ReservationExpiryPolicy.RETURN_TO_HOLDER);case SUPPRESS:return new SuppressResourceSpec(id,ResourceHolderSelector.CLASS_OWNER,first,1,SuppressResourceSpec.ResourceSuppressionMode.BLOCK_GAIN);default:throw new AssertionError(variant);}}
	private static EffectFamily family(EffectVariantKey key){switch(key){case DIRECT_DAMAGE:case PERCENT_MAX_HP_DAMAGE:case MISSING_HP_DAMAGE:case EXECUTE:return EffectFamily.DAMAGE;case APPLY_STATUS:return EffectFamily.STATUS;case PUSH:case PULL:case THROW:case DASH:case TELEPORT:case SWAP_POSITION:return EffectFamily.MOVEMENT;case HEAL:case BARRIER:case TEMPORARY_HP:case MITIGATE:case REDIRECT_DAMAGE:case CLEANSE:return EffectFamily.RECOVERY_DEFENSE;case RESOURCE_OPERATION:return EffectFamily.RESOURCE_OPERATION;default:return null;}}
	private static EffectSpec effect(SkillSpec s,String slot){if(PRIMARY.equals(slot))return s.effects().primary();if(IMMEDIATE_SECONDARY.equals(slot)&&s.effects().secondary()!=null)return s.effects().secondary().effect();throw new IllegalArgumentException("effect slot is not configured: "+slot);}private static EffectChainSpec withEffect(EffectChainSpec chain,String slot,EffectSpec effect){if(PRIMARY.equals(slot))return chain.withPrimary(effect);if(IMMEDIATE_SECONDARY.equals(slot)&&chain.secondary()!=null)return chain.withSecondary(new SecondaryEffectSpec(effect,chain.secondary().activation()));throw new IllegalArgumentException("effect slot is not configured: "+slot);}
	private static SkillSpec require(ClassBuildSpec build,String id){StableId wanted=StableId.fromStored(id);for(SkillSpec s:build.skills())if(s.id().equals(wanted)){if(!s.typed())throw new IllegalArgumentException("legacy skill envelope is not editable");return s;}throw new IllegalArgumentException("skill not found: "+id);}private static ClassBuildSpec replace(ClassBuildSpec build,SkillSpec replacement){List<SkillSpec> values=new ArrayList<>();boolean found=false;for(SkillSpec s:build.skills()){if(s.id().equals(replacement.id())){values.add(replacement);found=true;}else values.add(s);}if(!found)throw new IllegalArgumentException("skill not found");return build.toBuilder().skills(values).build();}
	private static void exposed(String family,String variant){if(!GameplayVariantCatalog.require(family,variant).playerExposed())throw unsupported(family,variant);}private static IllegalArgumentException unsupported(String kind,String variant){return new IllegalArgumentException("unsupported P04 "+kind+" variant "+variant);}private static int integer(String value){try{return Integer.parseInt(value);}catch(NumberFormatException e){throw new IllegalArgumentException("integer required: "+value,e);}}private static boolean bool(String v){if("true".equals(v))return true;if("false".equals(v))return false;throw new IllegalArgumentException("boolean required: "+v);}private static<E extends Enum<E>>E en(Class<E> type,String value){try{return Enum.valueOf(type,value);}catch(IllegalArgumentException e){throw new IllegalArgumentException("unknown "+type.getSimpleName()+" "+value,e);}}
}
