package com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.save;

import com.badlogic.gdx.utils.JsonReader;import com.badlogic.gdx.utils.JsonValue;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.dependency.DependencyState;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.identity.DisplayName;import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.identity.StableId;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.ref.*;import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.spec.*;
import java.util.ArrayList;import java.util.EnumSet;import java.util.List;

/** Canonical every-field codec for the P01 ClassBuildSpec surface. */
public final class CanonicalBuildCodec {
	private static final String FORMAT="CLASS_BUILD_V6";
	public String serialize(ClassBuildSpec build){CanonicalJsonWriter j=new CanonicalJsonWriter();j.beginObject();
		j.name("format").value(FORMAT);j.name("schema_version").value(build.schemaVersion());j.name("contract_version").value(build.contractVersion());
		j.name("build_id").value(build.buildId().value());j.name("display_name").value(build.displayName().text());
		j.name("resources").beginArray();for(ResourceSpec v:build.resources())resource(j,v);j.endArray();
		j.name("marks").beginArray();for(MarkSpec v:build.marks())mark(j,v);j.endArray();
		j.name("mode_groups").beginArray();for(ModeGroupSpec v:build.modeGroups())modeGroup(j,v);j.endArray();
		j.name("modes").beginArray();for(ModeSpec v:build.modes())mode(j,v);j.endArray();
		j.name("capacities").beginArray();for(EntityCapacitySpec v:build.capacities())capacity(j,v);j.endArray();
		j.name("entities").beginArray();for(EntitySpec v:build.entities())entity(j,v);j.endArray();
		j.name("ability_pools").beginArray();for(AbilityPoolSpec v:build.abilityPools())abilityPool(j,v);j.endArray();
		j.name("properties").beginArray();for(PropertySpec v:build.properties())property(j,v);j.endArray();
		j.name("recipes").beginArray();for(SynthesisRecipeSpec v:build.recipes())recipe(j,v);j.endArray();
		nodes(j,"class_components",build.classComponents());nodes(j,"class_constraints",build.classConstraints());nodes(j,"class_operations",build.classOperations());nodes(j,"skills",build.skills());
		j.name("starting_kit");section(j,build.startingKit());j.name("progression");section(j,build.progression());
		j.name("budget_metadata").beginObject().name("price_version").value(build.budgetMetadata().priceVersion()).name("base_budget").value(build.budgetMetadata().baseBudget()).endObject();
		j.endObject();return j.toString();}

	public CanonicalLoadResult<ClassBuildSpec> deserialize(String json){try{JsonValue root=new JsonReader().parse(json);if(!FORMAT.equals(reqString(root,"format")))return CanonicalLoadResult.failed(DependencyState.UNSUPPORTED,"unknown class build format");int schema=reqInt(root,"schema_version");if(schema!=ClassBuildSpec.SCHEMA_VERSION)return CanonicalLoadResult.failed(DependencyState.UNSUPPORTED,"unsupported class build schema "+schema);String contract=reqString(root,"contract_version");if(!ClassBuildSpec.CONTRACT_VERSION.equals(contract))return CanonicalLoadResult.failed(DependencyState.UNSUPPORTED,"unsupported contract version "+contract);
		ClassBuildSpec.Builder b=ClassBuildSpec.builder(id(root,"build_id"),name(root,"display_name")).schemaVersion(schema).contractVersion(contract);
		for(JsonValue v:array(root,"resources"))b.addResource(readResource(v));for(JsonValue v:array(root,"marks"))b.addMark(readMark(v));
		for(JsonValue v:array(root,"mode_groups"))b.addModeGroup(readModeGroup(v));for(JsonValue v:array(root,"modes"))b.addMode(readMode(v));
		for(JsonValue v:array(root,"capacities"))b.addCapacity(readCapacity(v));for(JsonValue v:array(root,"entities"))b.addEntity(readEntity(v));
		for(JsonValue v:array(root,"ability_pools"))b.addAbilityPool(readAbilityPool(v));for(JsonValue v:array(root,"properties"))b.addProperty(readProperty(v));
		for(JsonValue v:array(root,"recipes"))b.addRecipe(readRecipe(v));for(JsonValue v:array(root,"class_components"))b.addClassComponent(readNode(v,ContractNodeSpec.NodeKind.COMPONENT));
		for(JsonValue v:array(root,"class_constraints"))b.addClassConstraint(readNode(v,ContractNodeSpec.NodeKind.CONSTRAINT));for(JsonValue v:array(root,"class_operations"))b.addClassOperation(readNode(v,ContractNodeSpec.NodeKind.OPERATION));
		for(JsonValue v:array(root,"skills"))b.addSkill(readNode(v,ContractNodeSpec.NodeKind.SKILL));b.startingKit(readSection(req(root,"starting_kit"))).progression(readSection(req(root,"progression")));
		JsonValue budget=req(root,"budget_metadata");b.budgetMetadata(new BudgetMetadata(reqString(budget,"price_version"),reqInt(budget,"base_budget")));return CanonicalLoadResult.resolved(b.build());
	}catch(UnsupportedValue error){return CanonicalLoadResult.failed(DependencyState.UNSUPPORTED,error.getMessage());}catch(RuntimeException error){return CanonicalLoadResult.failed(DependencyState.HARD_CONFLICT,"malformed canonical class build: "+error.getMessage());}}

	private static void identity(CanonicalJsonWriter j,String variant,StableTarget v){j.name("variant").value(variant);j.name("id").value(v.id().value());j.name("display_name").value(v.displayName().text());j.name("implementation_state").value(v.implementationState().name());}
	private static void resource(CanonicalJsonWriter j,ResourceSpec v){j.beginObject();identity(j,"RESOURCE",v);j.name("minimum").value(v.minimum()).name("maximum").value(v.maximum()).name("initial_value").value(v.initialValue()).name("default_overflow_policy").value(v.defaultOverflowPolicy().name());j.name("hud").beginObject().name("visible").value(v.hud().visible()).name("order").value(v.hud().order()).name("presentation_key").value(v.hud().presentationKey()).endObject();j.endObject();}
	private static void mark(CanonicalJsonWriter j,MarkSpec v){j.beginObject();identity(j,"MARK",v);j.name("kind").value(v.kind().name()).name("minimum").value(v.minimum()).name("maximum").value(v.maximum()).name("initial_value").value(v.initialValue()).name("duration_policy").value(v.durationPolicy().name()).name("default_duration_turns").value(v.defaultDurationTurns()).name("refresh_policy").value(v.refreshPolicy().name()).name("overflow_policy").value(v.overflowPolicy().name()).name("provenance_policy").value(v.provenancePolicy().name());j.endObject();}
	private static void modeGroup(CanonicalJsonWriter j,ModeGroupSpec v){j.beginObject();identity(j,"MODE_GROUP",v);j.name("policy").value(v.policy().name());j.endObject();}
	private static void mode(CanonicalJsonWriter j,ModeSpec v){j.beginObject();identity(j,"MODE",v);j.name("group");ref(j,v.group());j.name("initial").value(v.initial()).name("duration_policy").value(v.durationPolicy().name()).name("default_duration_turns").value(v.defaultDurationTurns());j.endObject();}
	private static void capacity(CanonicalJsonWriter j,EntityCapacitySpec v){j.beginObject();identity(j,"ENTITY_CAPACITY",v);j.name("entity_types").beginArray();for(EntityType type:EntityType.values())if(v.entityTypes().contains(type))j.value(type.name());j.endArray();j.name("maximum").value(v.maximum()).name("overflow_policy").value(v.overflowPolicy().name());j.endObject();}
	private static void entity(CanonicalJsonWriter j,EntitySpec v){j.beginObject();identity(j,"ENTITY",v);j.name("entity_type").value(v.type().name());j.name("body");facet(j,v.body());j.name("spawn_policy");facet(j,v.spawnPolicy());j.name("ownership");facet(j,v.ownership());j.name("relation");facet(j,v.relation());j.name("capacity");if(v.capacity()==null)j.value((String)null);else ref(j,v.capacity());j.name("persistence");facet(j,v.persistence());j.name("capabilities").beginArray();for(EntityCapabilitySpec capability:v.capabilities())capability(j,capability);j.endArray();j.endObject();}
	private static void facet(CanonicalJsonWriter j,EntityFacetSpec v){j.beginObject().name("facet_kind").value(v.facetKind().name()).name("variant_key").value(v.variantKey()).name("implementation_state").value(v.implementationState().name()).endObject();}
	private static void capability(CanonicalJsonWriter j,EntityCapabilitySpec v){j.beginObject();if(v instanceof ResourceStorageCapability){j.name("capability_kind").value("RESOURCE_STORAGE").name("variant_key").value(v.variantKey()).name("implementation_state").value(v.implementationState().name()).name("slots").beginArray();for(EntityResourceSlotSpec slot:((ResourceStorageCapability)v).slots()){j.beginObject().name("resource");ref(j,slot.resource());j.name("initial_value").value(slot.initialValue()).name("maximum_override").value(slot.maximumOverride()).endObject();}j.endArray();}else if(v instanceof DeferredEntityCapabilitySpec){j.name("capability_kind").value("DEFERRED_CAPABILITY").name("variant_key").value(v.variantKey()).name("implementation_state").value(v.implementationState().name());}else throw new IllegalArgumentException("unsupported P01 entity capability envelope "+v.getClass().getName());j.endObject();}
	private static void abilityPool(CanonicalJsonWriter j,AbilityPoolSpec v){j.beginObject();identity(j,"ABILITY_POOL",v);j.name("capacity").value(v.capacity()).name("overflow_policy").value(v.overflowPolicy().name());j.endObject();}
	private static void property(CanonicalJsonWriter j,PropertySpec v){j.beginObject();identity(j,"PROPERTY",v);j.name("value_kind").value(v.valueKind().name()).name("maximum_stack").value(v.maximumStack());j.endObject();}
	private static void recipe(CanonicalJsonWriter j,SynthesisRecipeSpec v){j.beginObject();identity(j,"RECIPE",v);j.name("inputs").beginArray();for(SynthesisRecipeSpec.PropertyInput input:v.inputs()){j.beginObject().name("property");ref(j,input.property());j.name("amount").value(input.amount()).endObject();}j.endArray();j.name("output_variant").value(v.outputVariantKey());j.endObject();}
	private static void nodes(CanonicalJsonWriter j,String name,List<ContractNodeSpec> values){j.name(name).beginArray();for(ContractNodeSpec v:values){j.beginObject();identity(j,"CONTRACT_NODE",v);j.name("node_kind").value(v.nodeKind().name()).name("variant_key").value(v.variantKey());j.endObject();}j.endArray();}
	private static void section(CanonicalJsonWriter j,DeferredSectionSpec v){j.beginObject().name("section_key").value(v.sectionKey()).name("implementation_state").value(v.state().name()).endObject();}
	private static void ref(CanonicalJsonWriter j,TypedRef v){j.beginObject().name("ref_kind").value(v.kind().name()).name("target_id").value(v.targetId().value()).name("last_known_display_name").value(v.lastKnownDisplayName()).endObject();}

	private static ResourceSpec readResource(JsonValue v){variant(v,"RESOURCE");state(v,ImplementationState.DECLARED);JsonValue hud=req(v,"hud");return new ResourceSpec(id(v,"id"),name(v,"display_name"),reqInt(v,"minimum"),reqInt(v,"maximum"),reqInt(v,"initial_value"),en(ResourceSpec.ResourceOverflowPolicy.class,v,"default_overflow_policy"),new ResourceSpec.ResourceHudSpec(reqBool(hud,"visible"),reqInt(hud,"order"),reqString(hud,"presentation_key")));}
	private static MarkSpec readMark(JsonValue v){variant(v,"MARK");state(v,ImplementationState.DECLARED);return new MarkSpec(id(v,"id"),name(v,"display_name"),en(MarkSpec.MarkKind.class,v,"kind"),reqInt(v,"minimum"),reqInt(v,"maximum"),reqInt(v,"initial_value"),en(MarkSpec.MarkDurationPolicy.class,v,"duration_policy"),reqInt(v,"default_duration_turns"),en(MarkSpec.MarkRefreshPolicy.class,v,"refresh_policy"),en(MarkSpec.MarkOverflowPolicy.class,v,"overflow_policy"),en(MarkSpec.MarkProvenancePolicy.class,v,"provenance_policy"));}
	private static ModeGroupSpec readModeGroup(JsonValue v){variant(v,"MODE_GROUP");state(v,ImplementationState.DECLARED);return new ModeGroupSpec(id(v,"id"),name(v,"display_name"),en(ModeGroupSpec.ModeGroupPolicy.class,v,"policy"));}
	private static ModeSpec readMode(JsonValue v){variant(v,"MODE");state(v,ImplementationState.DECLARED);return new ModeSpec(id(v,"id"),name(v,"display_name"),(ModeGroupRef)readRef(req(v,"group"),RefKind.MODE_GROUP),reqBool(v,"initial"),en(ModeSpec.ModeDurationPolicy.class,v,"duration_policy"),reqInt(v,"default_duration_turns"));}
	private static EntityCapacitySpec readCapacity(JsonValue v){variant(v,"ENTITY_CAPACITY");state(v,ImplementationState.DECLARED);EnumSet<EntityType> types=EnumSet.noneOf(EntityType.class);for(JsonValue item:array(v,"entity_types"))types.add(en(EntityType.class,item.asString()));return new EntityCapacitySpec(id(v,"id"),name(v,"display_name"),types,reqInt(v,"maximum"),en(EntityCapacitySpec.CapacityOverflowPolicy.class,v,"overflow_policy"));}
	private static EntitySpec readEntity(JsonValue v){variant(v,"ENTITY");ImplementationState state=state(v,null);JsonValue cap=req(v,"capacity");CapacityRef ref=cap.isNull()?null:(CapacityRef)readRef(cap,RefKind.CAPACITY);DeferredEntityFacetSpec body=readFacet(req(v,"body"),EntityFacetKind.BODY);DeferredEntityFacetSpec spawn=readFacet(req(v,"spawn_policy"),EntityFacetKind.SPAWN_POLICY);DeferredEntityFacetSpec ownership=readFacet(req(v,"ownership"),EntityFacetKind.OWNERSHIP);DeferredEntityFacetSpec relation=readFacet(req(v,"relation"),EntityFacetKind.RELATION);DeferredEntityFacetSpec persistence=readFacet(req(v,"persistence"),EntityFacetKind.PERSISTENCE);List<EntityCapabilitySpec> capabilities=new ArrayList<>();for(JsonValue capability:array(v,"capabilities"))capabilities.add(readCapability(capability));return new EntitySpec(id(v,"id"),name(v,"display_name"),en(EntityType.class,v,"entity_type"),body,spawn,ownership,relation,ref,persistence,capabilities,state);}
	private static DeferredEntityFacetSpec readFacet(JsonValue v,EntityFacetKind expected){EntityFacetKind kind=en(EntityFacetKind.class,v,"facet_kind");if(kind!=expected)throw new UnsupportedValue("entity facet kind mismatch: expected "+expected+" got "+kind);ImplementationState state=en(ImplementationState.class,v,"implementation_state");return new DeferredEntityFacetSpec(kind,reqString(v,"variant_key"),state);}
	private static EntityCapabilitySpec readCapability(JsonValue v){String kind=reqString(v,"capability_kind");String variant=reqString(v,"variant_key");ImplementationState state=en(ImplementationState.class,v,"implementation_state");if("RESOURCE_STORAGE".equals(kind)){if(!ResourceStorageCapability.VARIANT.equals(variant)||state!=ImplementationState.DEFERRED)throw new UnsupportedValue("unsupported resource storage capability variant/state");List<EntityResourceSlotSpec> slots=new ArrayList<>();for(JsonValue slot:array(v,"slots"))slots.add(new EntityResourceSlotSpec((ResourceRef)readRef(req(slot,"resource"),RefKind.RESOURCE),reqInt(slot,"initial_value"),reqInt(slot,"maximum_override")));return new ResourceStorageCapability(slots);}if("DEFERRED_CAPABILITY".equals(kind))return new DeferredEntityCapabilitySpec(variant,state);throw new UnsupportedValue("unknown entity capability variant "+kind);}
	private static AbilityPoolSpec readAbilityPool(JsonValue v){variant(v,"ABILITY_POOL");state(v,ImplementationState.DECLARED);return new AbilityPoolSpec(id(v,"id"),name(v,"display_name"),reqInt(v,"capacity"),en(AbilityPoolSpec.AbilityOverflowPolicy.class,v,"overflow_policy"));}
	private static PropertySpec readProperty(JsonValue v){variant(v,"PROPERTY");state(v,ImplementationState.DECLARED);return new PropertySpec(id(v,"id"),name(v,"display_name"),en(PropertySpec.PropertyValueKind.class,v,"value_kind"),reqInt(v,"maximum_stack"));}
	private static SynthesisRecipeSpec readRecipe(JsonValue v){variant(v,"RECIPE");ImplementationState state=state(v,null);List<SynthesisRecipeSpec.PropertyInput> inputs=new ArrayList<>();for(JsonValue item:array(v,"inputs"))inputs.add(new SynthesisRecipeSpec.PropertyInput((PropertyRef)readRef(req(item,"property"),RefKind.PROPERTY),reqInt(item,"amount")));return new SynthesisRecipeSpec(id(v,"id"),name(v,"display_name"),inputs,reqString(v,"output_variant"),state);}
	private static ContractNodeSpec readNode(JsonValue v,ContractNodeSpec.NodeKind expected){variant(v,"CONTRACT_NODE");ContractNodeSpec.NodeKind kind=en(ContractNodeSpec.NodeKind.class,v,"node_kind");if(kind!=expected)throw new UnsupportedValue("node kind does not match list: "+kind);ImplementationState state=state(v,null);if(state!=ImplementationState.UNSUPPORTED&&state!=ImplementationState.DEFERRED)throw new UnsupportedValue("P01 cannot load executable node variant "+reqString(v,"variant_key"));return new ContractNodeSpec(id(v,"id"),name(v,"display_name"),kind,reqString(v,"variant_key"),state);}
	private static DeferredSectionSpec readSection(JsonValue v){ImplementationState state=en(ImplementationState.class,v,"implementation_state");return new DeferredSectionSpec(reqString(v,"section_key"),state);}
	private static TypedRef readRef(JsonValue v,RefKind expected){RefKind kind=en(RefKind.class,v,"ref_kind");if(kind!=expected)throw new UnsupportedValue("reference kind mismatch: expected "+expected+" got "+kind);StableId id=id(v,"target_id");String name=reqString(v,"last_known_display_name");switch(kind){case RESOURCE:return new ResourceRef(id,name);case MARK:return new MarkRef(id,name);case MODE_GROUP:return new ModeGroupRef(id,name);case MODE:return new ModeRef(id,name);case ENTITY:return new EntitySpecRef(id,name);case CAPACITY:return new CapacityRef(id,name);case COMPONENT:return new ComponentRef(id,name);case ABILITY_POOL:return new AbilityPoolRef(id,name);case PROPERTY:return new PropertyRef(id,name);case RECIPE:return new SynthesisRecipeRef(id,name);default:throw new UnsupportedValue("unknown reference kind "+kind);}}
	private static void variant(JsonValue v,String expected){String actual=reqString(v,"variant");if(!expected.equals(actual))throw new UnsupportedValue("unknown declaration variant "+actual+", expected "+expected);}
	private static ImplementationState state(JsonValue v,ImplementationState expected){ImplementationState actual=en(ImplementationState.class,v,"implementation_state");if(expected!=null&&actual!=expected)throw new UnsupportedValue("unexpected implementation state "+actual);return actual;}
	private static StableId id(JsonValue v,String key){return StableId.fromStored(reqString(v,key));}private static DisplayName name(JsonValue v,String key){return DisplayName.of(reqString(v,key));}
	private static JsonValue req(JsonValue v,String key){JsonValue result=v.get(key);if(result==null)throw new IllegalArgumentException("missing field "+key);return result;}
	private static String reqString(JsonValue v,String key){return req(v,key).asString();}private static int reqInt(JsonValue v,String key){return req(v,key).asInt();}private static boolean reqBool(JsonValue v,String key){return req(v,key).asBoolean();}
	private static<T extends Enum<T>>T en(Class<T> type,JsonValue v,String key){return en(type,reqString(v,key));}private static<T extends Enum<T>>T en(Class<T> type,String value){try{return Enum.valueOf(type,value);}catch(IllegalArgumentException error){throw new UnsupportedValue("unknown "+type.getSimpleName()+" variant "+value);}}
	private static List<JsonValue> array(JsonValue v,String key){JsonValue a=req(v,key);if(!a.isArray())throw new IllegalArgumentException(key+" is not an array");List<JsonValue> result=new ArrayList<>();for(JsonValue item=a.child;item!=null;item=item.next)result.add(item);return result;}
	private static final class UnsupportedValue extends RuntimeException{UnsupportedValue(String message){super(message);}}
}
