package com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.save;

import com.badlogic.gdx.utils.JsonReader;import com.badlogic.gdx.utils.JsonValue;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.dependency.DependencyState;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.identity.StableId;import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.ref.*;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.spec.ClassBuildSpec;import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.spec.ImplementationState;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.state.*;
import java.util.ArrayList;import java.util.Collections;import java.util.LinkedHashMap;import java.util.List;import java.util.Map;

/** Canonical every-field codec for the P01 ClassRuntimeState surface. */
public final class CanonicalRuntimeCodec {
	private static final String FORMAT="CLASS_RUNTIME_STATE_V6";
	public String serialize(ClassRuntimeState state){CanonicalJsonWriter j=new CanonicalJsonWriter();j.beginObject().name("format").value(FORMAT).name("schema_version").value(ClassBuildSpec.SCHEMA_VERSION).name("build_id").value(state.buildId().value());
		j.name("resources").beginArray();for(ResourceState v:state.resources())resource(j,v);j.endArray();j.name("modes").beginArray();for(ModeState v:state.modes())mode(j,v);j.endArray();
		j.name("marks").beginArray();for(MarkState v:state.marks())mark(j,v);j.endArray();j.name("entities").beginArray();for(EntityInstanceState v:state.entities())entity(j,v);j.endArray();
		opaque(j,"scheduled_payloads",state.scheduledPayloads());opaque(j,"attachments",state.attachments());map(j,"cooldowns",state.cooldowns());map(j,"uses_this_floor",state.usesThisFloor());
		opaque(j,"snapshots",state.snapshots());opaque(j,"learned_abilities",state.learnedAbilities());j.name("properties").beginArray();for(PropertyInventoryState v:state.properties())property(j,v);j.endArray();
		j.name("next_runtime_entity_id").value(state.nextRuntimeEntityId()).name("next_payload_instance_id").value(state.nextPayloadInstanceId()).name("next_event_id").value(state.nextEventId()).endObject();return j.toString();}

	public CanonicalLoadResult<ClassRuntimeState> deserialize(String json){try{JsonValue root=new JsonReader().parse(json);if(!FORMAT.equals(reqString(root,"format")))return CanonicalLoadResult.failed(DependencyState.UNSUPPORTED,"unknown runtime format");int schema=req(root,"schema_version").asInt();if(schema!=ClassBuildSpec.SCHEMA_VERSION)return CanonicalLoadResult.failed(DependencyState.UNSUPPORTED,"unsupported runtime schema "+schema);ClassRuntimeState.Builder b=ClassRuntimeState.builder(id(root,"build_id"));
		for(JsonValue v:array(root,"resources"))b.addResource(readResource(v));for(JsonValue v:array(root,"modes"))b.addMode(readMode(v));for(JsonValue v:array(root,"marks"))b.addMark(readMark(v));for(JsonValue v:array(root,"entities"))b.addEntity(readEntity(v));
		b.scheduledPayloads(readOpaque(root,"scheduled_payloads")).attachments(readOpaque(root,"attachments")).cooldowns(readMap(root,"cooldowns")).usesThisFloor(readMap(root,"uses_this_floor")).snapshots(readOpaque(root,"snapshots")).learnedAbilities(readOpaque(root,"learned_abilities"));
		List<PropertyInventoryState> properties=new ArrayList<>();for(JsonValue v:array(root,"properties"))properties.add(readProperty(v));b.properties(properties).nextRuntimeEntityId(req(root,"next_runtime_entity_id").asLong()).nextPayloadInstanceId(req(root,"next_payload_instance_id").asLong()).nextEventId(req(root,"next_event_id").asLong());return CanonicalLoadResult.resolved(b.build());
	}catch(UnsupportedValue error){return CanonicalLoadResult.failed(DependencyState.UNSUPPORTED,error.getMessage());}catch(RuntimeException error){return CanonicalLoadResult.failed(DependencyState.HARD_CONFLICT,"malformed canonical runtime state: "+error.getMessage());}}

	private static void resource(CanonicalJsonWriter j,ResourceState v){j.beginObject().name("resource");ref(j,v.resource());j.name("current").value(v.current()).name("reservations").beginArray();for(ResourceState.Reservation x:v.reservations())j.beginObject().name("reservation_id").value(x.reservationId()).name("amount").value(x.amount()).name("remaining_turns").value(x.remainingTurns()).endObject();j.endArray().name("suppressions").beginArray();for(ResourceState.Suppression x:v.suppressions())j.beginObject().name("suppression_id").value(x.suppressionId()).name("remaining_turns").value(x.remainingTurns()).name("mode_key").value(x.modeKey()).endObject();j.endArray().endObject();}
	private static void mode(CanonicalJsonWriter j,ModeState v){j.beginObject().name("mode");ref(j,v.mode());j.name("subject_actor_id").value(v.subjectActorId()).name("remaining_turns").value(v.remainingTurns()).endObject();}
	private static void mark(CanonicalJsonWriter j,MarkState v){j.beginObject().name("mark");ref(j,v.mark());j.name("subject_actor_id").value(v.subjectActorId()).name("source_actor_id").value(v.sourceActorId()).name("value").value(v.value()).name("remaining_turns").value(v.remainingTurns()).name("transfer_depth").value(v.transferDepth()).endObject();}
	private static void entity(CanonicalJsonWriter j,EntityInstanceState v){j.beginObject().name("instance_id").value(v.instanceId()).name("blueprint");ref(j,v.blueprint());j.name("owner_actor_id").value(v.ownerActorId()).name("source_actor_id").value(v.sourceActorId()).name("cell").value(v.cell()).name("remaining_turns").value(v.remainingTurns()).name("created_order").value(v.createdOrder()).name("capability_states").beginArray();for(OpaqueRuntimeState state:v.capabilityStates())opaqueValue(j,state);j.endArray().endObject();}
	private static void opaque(CanonicalJsonWriter j,String name,List<OpaqueRuntimeState> values){j.name(name).beginArray();for(OpaqueRuntimeState v:values)j.beginObject().name("state_id").value(v.stateId().value()).name("variant_key").value(v.variantKey()).name("implementation_state").value(v.implementationState().name()).endObject();j.endArray();}
	private static void opaqueValue(CanonicalJsonWriter j,OpaqueRuntimeState v){j.beginObject().name("state_id").value(v.stateId().value()).name("variant_key").value(v.variantKey()).name("implementation_state").value(v.implementationState().name()).endObject();}
	private static void map(CanonicalJsonWriter j,String name,Map<StableId,Integer> values){List<StableId> keys=new ArrayList<>(values.keySet());Collections.sort(keys);j.name(name).beginArray();for(StableId key:keys)j.beginObject().name("node_id").value(key.value()).name("value").value(values.get(key)).endObject();j.endArray();}
	private static void property(CanonicalJsonWriter j,PropertyInventoryState v){j.beginObject().name("property");ref(j,v.property());j.name("amount").value(v.amount()).name("provenance").beginArray();for(String x:v.provenance())j.value(x);j.endArray().endObject();}
	private static void ref(CanonicalJsonWriter j,TypedRef v){j.beginObject().name("ref_kind").value(v.kind().name()).name("target_id").value(v.targetId().value()).name("last_known_display_name").value(v.lastKnownDisplayName()).endObject();}

	private static ResourceState readResource(JsonValue v){List<ResourceState.Reservation> reservations=new ArrayList<>();for(JsonValue x:array(v,"reservations"))reservations.add(new ResourceState.Reservation(req(x,"reservation_id").asLong(),req(x,"amount").asInt(),req(x,"remaining_turns").asInt()));List<ResourceState.Suppression> suppressions=new ArrayList<>();for(JsonValue x:array(v,"suppressions"))suppressions.add(new ResourceState.Suppression(req(x,"suppression_id").asLong(),req(x,"remaining_turns").asInt(),reqString(x,"mode_key")));return new ResourceState((ResourceRef)readRef(req(v,"resource"),RefKind.RESOURCE),req(v,"current").asInt(),reservations,suppressions);}
	private static ModeState readMode(JsonValue v){return new ModeState((ModeRef)readRef(req(v,"mode"),RefKind.MODE),req(v,"subject_actor_id").asLong(),req(v,"remaining_turns").asInt());}
	private static MarkState readMark(JsonValue v){return new MarkState((MarkRef)readRef(req(v,"mark"),RefKind.MARK),req(v,"subject_actor_id").asLong(),req(v,"source_actor_id").asLong(),req(v,"value").asInt(),req(v,"remaining_turns").asInt(),req(v,"transfer_depth").asInt());}
	private static EntityInstanceState readEntity(JsonValue v){return new EntityInstanceState(req(v,"instance_id").asLong(),(EntitySpecRef)readRef(req(v,"blueprint"),RefKind.ENTITY),req(v,"owner_actor_id").asLong(),req(v,"source_actor_id").asLong(),req(v,"cell").asInt(),req(v,"remaining_turns").asInt(),req(v,"created_order").asInt(),readOpaque(v,"capability_states"));}
	private static List<OpaqueRuntimeState> readOpaque(JsonValue root,String key){List<OpaqueRuntimeState> result=new ArrayList<>();for(JsonValue v:array(root,key)){ImplementationState state=en(ImplementationState.class,reqString(v,"implementation_state"));if(state!=ImplementationState.UNSUPPORTED&&state!=ImplementationState.DEFERRED)throw new UnsupportedValue("opaque runtime variant cannot be executable in P01: "+reqString(v,"variant_key"));result.add(new OpaqueRuntimeState(id(v,"state_id"),reqString(v,"variant_key"),state));}return result;}
	private static Map<StableId,Integer> readMap(JsonValue root,String key){Map<StableId,Integer> result=new LinkedHashMap<>();for(JsonValue v:array(root,key)){StableId id=id(v,"node_id");if(result.put(id,req(v,"value").asInt())!=null)throw new IllegalArgumentException("duplicate map id "+id);}return result;}
	private static PropertyInventoryState readProperty(JsonValue v){List<String> provenance=new ArrayList<>();for(JsonValue x:array(v,"provenance"))provenance.add(x.asString());return new PropertyInventoryState((PropertyRef)readRef(req(v,"property"),RefKind.PROPERTY),req(v,"amount").asInt(),provenance);}
	private static TypedRef readRef(JsonValue v,RefKind expected){RefKind kind=en(RefKind.class,reqString(v,"ref_kind"));if(kind!=expected)throw new UnsupportedValue("reference kind mismatch: expected "+expected+" got "+kind);StableId id=id(v,"target_id");String name=reqString(v,"last_known_display_name");switch(kind){case RESOURCE:return new ResourceRef(id,name);case MARK:return new MarkRef(id,name);case MODE:return new ModeRef(id,name);case ENTITY:return new EntitySpecRef(id,name);case PROPERTY:return new PropertyRef(id,name);default:throw new UnsupportedValue("runtime reference kind is not supported in P01: "+kind);}}
	private static JsonValue req(JsonValue v,String key){JsonValue result=v.get(key);if(result==null)throw new IllegalArgumentException("missing field "+key);return result;}private static String reqString(JsonValue v,String key){return req(v,key).asString();}private static StableId id(JsonValue v,String key){return StableId.fromStored(reqString(v,key));}
	private static<T extends Enum<T>>T en(Class<T> type,String value){try{return Enum.valueOf(type,value);}catch(IllegalArgumentException error){throw new UnsupportedValue("unknown "+type.getSimpleName()+" variant "+value);}}
	private static List<JsonValue> array(JsonValue v,String key){JsonValue a=req(v,key);if(!a.isArray())throw new IllegalArgumentException(key+" is not an array");List<JsonValue> result=new ArrayList<>();for(JsonValue item=a.child;item!=null;item=item.next)result.add(item);return result;}
	private static final class UnsupportedValue extends RuntimeException{UnsupportedValue(String message){super(message);}}
}
