package com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.save;

import com.badlogic.gdx.utils.JsonReader;import com.badlogic.gdx.utils.JsonValue;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.dependency.DependencyState;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.identity.DisplayName;import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.identity.StableId;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.ref.*;import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.spec.*;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.spec.skill.*;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.spec.component.*;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.spec.resource.*;
import java.util.ArrayList;import java.util.EnumSet;import java.util.List;

/** Canonical every-field codec for the P01 ClassBuildSpec surface. */
public final class CanonicalBuildCodec {
	private static final String FORMAT="CLASS_BUILD_V6";
	public String serialize(ClassBuildSpec build){CanonicalJsonWriter j=new CanonicalJsonWriter();j.beginObject();
		j.name("format").value(FORMAT);j.name("schema_version").value(build.schemaVersion());j.name("contract_version").value(build.contractVersion());
		j.name("build_id").value(build.buildId().value());j.name("display_name").value(build.displayName().text());
		j.name("resources").beginArray();for(ResourceSpec v:build.resources())resource(j,v);j.endArray();
		j.name("marks").beginArray();for(MarkSpec v:build.marks())mark(j,v);j.endArray();
		j.name("mode_groups").beginArray();for(ModeGroupSpec v:build.modeGroups())modeGroup(j,v);j.endArray();
		j.name("modes").beginArray();for(ModeSpec v:build.modes())mode(j,v);j.endArray();
		j.name("capacities").beginArray();for(EntityCapacitySpec v:build.capacities())capacity(j,v);j.endArray();
		j.name("entities").beginArray();for(EntitySpec v:build.entities())entity(j,v);j.endArray();
		j.name("ability_pools").beginArray();for(AbilityPoolSpec v:build.abilityPools())abilityPool(j,v);j.endArray();
		j.name("properties").beginArray();for(PropertySpec v:build.properties())property(j,v);j.endArray();
		j.name("recipes").beginArray();for(SynthesisRecipeSpec v:build.recipes())recipe(j,v);j.endArray();
		nodes(j,"class_components",build.classComponents());nodes(j,"class_constraints",build.classConstraints());nodes(j,"class_operations",build.classOperations());skills(j,build.skills());
		j.name("starting_kit");section(j,build.startingKit());j.name("progression");section(j,build.progression());
		j.name("budget_metadata").beginObject().name("price_version").value(build.budgetMetadata().priceVersion()).name("base_budget").value(build.budgetMetadata().baseBudget()).endObject();
		j.endObject();return j.toString();}

	public CanonicalLoadResult<ClassBuildSpec> deserialize(String json){try{JsonValue root=new JsonReader().parse(json);if(!FORMAT.equals(reqString(root,"format")))return CanonicalLoadResult.failed(DependencyState.UNSUPPORTED,"unknown class build format");int schema=reqInt(root,"schema_version");if(schema!=ClassBuildSpec.SCHEMA_VERSION)return CanonicalLoadResult.failed(DependencyState.UNSUPPORTED,"unsupported class build schema "+schema);String contract=reqString(root,"contract_version");if(!ClassBuildSpec.CONTRACT_VERSION.equals(contract))return CanonicalLoadResult.failed(DependencyState.UNSUPPORTED,"unsupported contract version "+contract);
		ClassBuildSpec.Builder b=ClassBuildSpec.builder(id(root,"build_id"),name(root,"display_name")).schemaVersion(schema).contractVersion(contract);
		for(JsonValue v:array(root,"resources"))b.addResource(readResource(v));for(JsonValue v:array(root,"marks"))b.addMark(readMark(v));
		for(JsonValue v:array(root,"mode_groups"))b.addModeGroup(readModeGroup(v));for(JsonValue v:array(root,"modes"))b.addMode(readMode(v));
		for(JsonValue v:array(root,"capacities"))b.addCapacity(readCapacity(v));for(JsonValue v:array(root,"entities"))b.addEntity(readEntity(v));
		for(JsonValue v:array(root,"ability_pools"))b.addAbilityPool(readAbilityPool(v));for(JsonValue v:array(root,"properties"))b.addProperty(readProperty(v));
		for(JsonValue v:array(root,"recipes"))b.addRecipe(readRecipe(v));for(JsonValue v:array(root,"class_components"))b.addClassComponent(readNode(v,ContractNodeSpec.NodeKind.COMPONENT));
		for(JsonValue v:array(root,"class_constraints"))b.addClassConstraint(readNode(v,ContractNodeSpec.NodeKind.CONSTRAINT));for(JsonValue v:array(root,"class_operations"))b.addClassOperation(readNode(v,ContractNodeSpec.NodeKind.OPERATION));
		for(JsonValue v:array(root,"skills"))b.addSkill(readSkill(v));b.startingKit(readSection(req(root,"starting_kit"))).progression(readSection(req(root,"progression")));
		JsonValue budget=req(root,"budget_metadata");b.budgetMetadata(new BudgetMetadata(reqString(budget,"price_version"),reqInt(budget,"base_budget")));return CanonicalLoadResult.resolved(b.build());
	}catch(UnsupportedValue error){return CanonicalLoadResult.failed(DependencyState.UNSUPPORTED,error.getMessage());}catch(RuntimeException error){return CanonicalLoadResult.failed(DependencyState.HARD_CONFLICT,"malformed canonical class build: "+error.getMessage());}}

	private static void identity(CanonicalJsonWriter j,String variant,StableTarget v){j.name("variant").value(variant);j.name("id").value(v.id().value());j.name("display_name").value(v.displayName().text());j.name("implementation_state").value(v.implementationState().name());}
	private static void resource(CanonicalJsonWriter j,ResourceSpec v){j.beginObject();identity(j,"RESOURCE",v);j.name("minimum").value(v.minimum()).name("maximum").value(v.maximum()).name("initial_value").value(v.initialValue()).name("default_overflow_policy").value(v.defaultOverflowPolicy().name());j.name("hud").beginObject().name("visible").value(v.hud().visible()).name("order").value(v.hud().order()).name("presentation_key").value(v.hud().presentationKey()).endObject();j.endObject();}
	private static void mark(CanonicalJsonWriter j,MarkSpec v){j.beginObject();identity(j,"MARK",v);j.name("kind").value(v.kind().name()).name("minimum").value(v.minimum()).name("maximum").value(v.maximum()).name("initial_value").value(v.initialValue()).name("duration_policy").value(v.durationPolicy().name()).name("default_duration_turns").value(v.defaultDurationTurns()).name("refresh_policy").value(v.refreshPolicy().name()).name("overflow_policy").value(v.overflowPolicy().name()).name("provenance_policy").value(v.provenancePolicy().name());j.endObject();}
	private static void modeGroup(CanonicalJsonWriter j,ModeGroupSpec v){j.beginObject();identity(j,"MODE_GROUP",v);j.name("policy").value(v.policy().name());j.endObject();}
	private static void mode(CanonicalJsonWriter j,ModeSpec v){j.beginObject();identity(j,"MODE",v);j.name("group");ref(j,v.group());j.name("initial").value(v.initial()).name("duration_policy").value(v.durationPolicy().name()).name("default_duration_turns").value(v.defaultDurationTurns());j.endObject();}
	private static void capacity(CanonicalJsonWriter j,EntityCapacitySpec v){j.beginObject();identity(j,"ENTITY_CAPACITY",v);j.name("entity_types").beginArray();for(EntityType type:EntityType.values())if(v.entityTypes().contains(type))j.value(type.name());j.endArray();j.name("maximum").value(v.maximum()).name("overflow_policy").value(v.overflowPolicy().name());j.endObject();}
	private static void entity(CanonicalJsonWriter j,EntitySpec v){j.beginObject();identity(j,"ENTITY",v);j.name("entity_type").value(v.type().name());j.name("body");facet(j,v.body());j.name("spawn_policy");facet(j,v.spawnPolicy());j.name("ownership");facet(j,v.ownership());j.name("relation");facet(j,v.relation());j.name("capacity");if(v.capacity()==null)j.value((String)null);else ref(j,v.capacity());j.name("persistence");facet(j,v.persistence());j.name("capabilities").beginArray();for(EntityCapabilitySpec capability:v.capabilities())capability(j,capability);j.endArray();j.endObject();}
	private static void facet(CanonicalJsonWriter j,EntityFacetSpec v){j.beginObject().name("facet_kind").value(v.facetKind().name()).name("variant_key").value(v.variantKey()).name("implementation_state").value(v.implementationState().name()).endObject();}
	private static void capability(CanonicalJsonWriter j,EntityCapabilitySpec v){j.beginObject();if(v instanceof ResourceStorageCapability){j.name("capability_kind").value("RESOURCE_STORAGE").name("variant_key").value(v.variantKey()).name("implementation_state").value(v.implementationState().name()).name("slots").beginArray();for(EntityResourceSlotSpec slot:((ResourceStorageCapability)v).slots()){j.beginObject().name("resource");ref(j,slot.resource());j.name("initial_value").value(slot.initialValue()).name("maximum_override").value(slot.maximumOverride()).endObject();}j.endArray();}else if(v instanceof DeferredEntityCapabilitySpec){j.name("capability_kind").value("DEFERRED_CAPABILITY").name("variant_key").value(v.variantKey()).name("implementation_state").value(v.implementationState().name());}else throw new IllegalArgumentException("unsupported P01 entity capability envelope "+v.getClass().getName());j.endObject();}
	private static void abilityPool(CanonicalJsonWriter j,AbilityPoolSpec v){j.beginObject();identity(j,"ABILITY_POOL",v);j.name("capacity").value(v.capacity()).name("overflow_policy").value(v.overflowPolicy().name());j.endObject();}
	private static void property(CanonicalJsonWriter j,PropertySpec v){j.beginObject();identity(j,"PROPERTY",v);j.name("value_kind").value(v.valueKind().name()).name("maximum_stack").value(v.maximumStack());j.endObject();}
	private static void recipe(CanonicalJsonWriter j,SynthesisRecipeSpec v){j.beginObject();identity(j,"RECIPE",v);j.name("inputs").beginArray();for(SynthesisRecipeSpec.PropertyInput input:v.inputs()){j.beginObject().name("property");ref(j,input.property());j.name("amount").value(input.amount()).endObject();}j.endArray();j.name("output_variant").value(v.outputVariantKey());j.endObject();}
	private static void nodes(CanonicalJsonWriter j,String name,List<ContractNodeSpec> values){j.name(name).beginArray();for(ContractNodeSpec v:values){j.beginObject();identity(j,"CONTRACT_NODE",v);j.name("node_kind").value(v.nodeKind().name()).name("variant_key").value(v.variantKey());
		if(v instanceof BasicAttackComponentSpec){BasicAttackComponentSpec x=(BasicAttackComponentSpec)v;j.name("availability").value(x.availability().name()).name("damage_numerator").value(x.damageNumerator()).name("damage_denominator").value(x.damageDenominator()).name("allowed_weapons").value(x.allowedWeapons().category().name()).name("action_time_turns").value(x.actionTimeTurns());}
		else if(v instanceof ResourceFlowComponentSpec){ResourceFlowComponentSpec x=(ResourceFlowComponentSpec)v;j.name("trigger");trigger(j,x.trigger());j.name("condition");condition(j,x.condition());j.name("operation");resourceOperation(j,x.operation());}
		else if(v instanceof ActiveResourceOperationComponentSpec){ActiveResourceOperationComponentSpec x=(ActiveResourceOperationComponentSpec)v;j.name("operation_display_name").value(x.operationDisplayName().text()).name("class_operation_id").value(x.classOperationId().value());j.name("operation");resourceOperation(j,x.operation());j.name("cost");cost(j,x.cost());j.name("action_time_turns").value(x.actionTimeTurns());}
		else if(v instanceof ResourceClassOperationSpec){ResourceClassOperationSpec x=(ResourceClassOperationSpec)v;j.name("source_component");if(x.sourceComponent()==null)j.value((String)null);else ref(j,x.sourceComponent());j.name("activation");trigger(j,x.activation());j.name("condition");condition(j,x.condition());j.name("cost");cost(j,x.cost());j.name("action_time_turns").value(x.actionTimeTurns());j.name("operation");resourceOperation(j,x.operation());j.name("hud_visible").value(x.hudVisible()).name("hud_order").value(x.hudOrder());}
		j.endObject();}j.endArray();}
	private static void skills(CanonicalJsonWriter j,List<SkillSpec> values){j.name("skills").beginArray();for(SkillSpec v:values)skill(j,v);j.endArray();}
	private static void skill(CanonicalJsonWriter j,SkillSpec v){j.beginObject();if(!v.typed()){identity(j,"CONTRACT_NODE",v);j.name("node_kind").value("SKILL").name("variant_key").value(v.variantKey());j.endObject();return;}identity(j,"SKILL",v);j.name("skill_version").value(SkillSpec.VERSION);j.name("activation");trigger(j,v.activation());j.name("condition");condition(j,v.condition());j.name("effects");chain(j,v.effects());j.name("delivery");delivery(j,v.delivery());j.name("targeting");targeting(j,v.targeting());j.name("modifier");modifier(j,v.modifier());j.name("cost");cost(j,v.cost());j.name("constraint");constraint(j,v.constraint());j.endObject();}
	private static void trigger(CanonicalJsonWriter j,TriggerSpec v){j.beginObject().name("node_id").value(v.nodeId().value()).name("variant_key").value(v.variantKey());if(v instanceof EventTriggerSpec)j.name("event").value(((EventTriggerSpec)v).event().name());j.endObject();}
	private static void condition(CanonicalJsonWriter j,ConditionExpr v){j.beginObject().name("variant_key").value(v.variantKey());if(v instanceof AllOfCondition){j.name("children").beginArray();for(ConditionExpr child:((AllOfCondition)v).children())condition(j,child);j.endArray();}else if(v instanceof BuiltinStatCompareCondition){BuiltinStatCompareCondition x=(BuiltinStatCompareCondition)v;j.name("node_id").value(x.nodeId().value()).name("subject").value(x.subject().name()).name("stat").value(x.stat().name()).name("operator").value(x.operator().name());j.name("value");value(j,x.value());}else if(v instanceof ResourceCompareCondition){ResourceCompareCondition x=(ResourceCompareCondition)v;j.name("node_id").value(x.nodeId().value()).name("holder").value(x.holder().name());j.name("resource");ref(j,x.resource());j.name("operator").value(x.operator().name()).name("value").value(x.value());}else if(!(v instanceof AlwaysCondition)&&!(v instanceof UnconfiguredConditionExpr))throw new IllegalArgumentException("unsupported condition class "+v.getClass().getName());j.endObject();}
	private static void chain(CanonicalJsonWriter j,EffectChainSpec v){j.beginObject().name("chain_id").value(v.chainId().value()).name("primary");effect(j,v.primary());j.name("secondary");if(v.secondary()==null)j.value((String)null);else{j.beginObject().name("activation").value(v.secondary().activation().variantKey()).name("effect");effect(j,v.secondary().effect());j.endObject();}j.endObject();}
	private static void effect(CanonicalJsonWriter j,EffectSpec v){j.beginObject().name("effect_id").value(v.effectId().value()).name("family");if(v.family()==null)j.value((String)null);else j.value(v.family().name());j.name("variant_key").value(v.variantKey().name());
		if(v instanceof UnconfiguredEffectSpec){}
		else if(v instanceof DirectDamageEffectSpec){DirectDamageEffectSpec x=(DirectDamageEffectSpec)v;j.name("amount");value(j,x.amount());j.name("damage_type").value(x.damageType().name()).name("defense_policy").value(x.defensePolicy().name());}
		else if(v instanceof PercentMaxHpDamageEffectSpec){PercentMaxHpDamageEffectSpec x=(PercentMaxHpDamageEffectSpec)v;j.name("percent").value(x.percent()).name("absolute_cap").value(x.absoluteCap()).name("protected_target_policy").value(x.protectedTargetPolicy().name());}
		else if(v instanceof MissingHpDamageEffectSpec){MissingHpDamageEffectSpec x=(MissingHpDamageEffectSpec)v;j.name("base_amount");value(j,x.baseAmount());j.name("missing_hp_numerator").value(x.missingHpNumerator()).name("missing_hp_denominator").value(x.missingHpDenominator()).name("absolute_cap").value(x.absoluteCap()).name("damage_type").value(x.damageType().name());}
		else if(v instanceof ExecuteEffectSpec){ExecuteEffectSpec x=(ExecuteEffectSpec)v;j.name("hp_percent_threshold").value(x.hpPercentThreshold()).name("fallback_damage");if(x.fallbackDamage()==null)j.value((String)null);else value(j,x.fallbackDamage());j.name("protected_target_policy").value(x.protectedTargetPolicy().name());}
		else if(v instanceof ApplyStatusEffectSpec){ApplyStatusEffectSpec x=(ApplyStatusEffectSpec)v;j.name("status").value(x.status().name()).name("intensity");value(j,x.intensity());j.name("duration");duration(j,x.duration());j.name("stacking").value(x.stacking().name());}
		else if(v instanceof PushEffectSpec){PushEffectSpec x=(PushEffectSpec)v;j.name("distance").value(x.distance()).name("collision_policy").value(x.collisionPolicy().name());}
		else if(v instanceof PullEffectSpec){PullEffectSpec x=(PullEffectSpec)v;j.name("distance").value(x.distance()).name("collision_policy").value(x.collisionPolicy().name());}
		else if(v instanceof ThrowEffectSpec){ThrowEffectSpec x=(ThrowEffectSpec)v;j.name("distance").value(x.distance()).name("collision_policy").value(x.collisionPolicy().name());}
		else if(v instanceof DashEffectSpec){DashEffectSpec x=(DashEffectSpec)v;j.name("maximum_distance").value(x.maximumDistance()).name("path_policy").value(x.pathPolicy().name());}
		else if(v instanceof TeleportEffectSpec){TeleportEffectSpec x=(TeleportEffectSpec)v;j.name("maximum_range").value(x.maximumRange()).name("destination_policy").value(x.destinationPolicy().name());}
		else if(v instanceof SwapPositionEffectSpec){j.name("legality_policy").value(((SwapPositionEffectSpec)v).legalityPolicy().name());}
		else if(v instanceof HealEffectSpec){j.name("amount");value(j,((HealEffectSpec)v).amount());}
		else if(v instanceof BarrierEffectSpec){BarrierEffectSpec x=(BarrierEffectSpec)v;j.name("amount");value(j,x.amount());j.name("overflow_policy").value(x.overflowPolicy().name());}
		else if(v instanceof TemporaryHpEffectSpec){TemporaryHpEffectSpec x=(TemporaryHpEffectSpec)v;j.name("amount");value(j,x.amount());j.name("duration");duration(j,x.duration());j.name("stacking").value(x.stacking().name());}
		else if(v instanceof MitigateEffectSpec){MitigateEffectSpec x=(MitigateEffectSpec)v;j.name("percent").value(x.percent()).name("duration");duration(j,x.duration());j.name("stacking").value(x.stacking().name());}
		else if(v instanceof RedirectDamageEffectSpec){RedirectDamageEffectSpec x=(RedirectDamageEffectSpec)v;j.name("percent").value(x.percent()).name("recipient").value(x.recipient().name()).name("duration");duration(j,x.duration());}
		else if(v instanceof CleanseEffectSpec){CleanseEffectSpec x=(CleanseEffectSpec)v;j.name("filter_kind").value(x.filter().kind().name()).name("status");if(x.filter().status()==null)j.value((String)null);else j.value(x.filter().status().name());j.name("maximum_count").value(x.maximumCount());}
		else if(v instanceof ResourceOperationEffectSpec){j.name("operation");resourceOperation(j,((ResourceOperationEffectSpec)v).operation());}
		else throw new IllegalArgumentException("unsupported typed effect class "+v.getClass().getName());j.endObject();}
	private static void value(CanonicalJsonWriter j,ValueSpec v){if(v instanceof FixedValueSpec)j.beginObject().name("variant_key").value(v.variantKey()).name("value").value(((FixedValueSpec)v).value()).endObject();else if(v instanceof ScaledValueSpec){ScaledValueSpec x=(ScaledValueSpec)v;j.beginObject().name("variant_key").value(v.variantKey()).name("base").value(x.base()).name("numerator").value(x.numerator()).name("denominator").value(x.denominator()).name("minimum").value(x.minimum()).name("maximum").value(x.maximum()).name("rounding").value(x.rounding().name()).name("source").beginObject().name("variant_key").value(x.source().variantKey());if(x.source() instanceof BuiltinStatSource){BuiltinStatSource s=(BuiltinStatSource)x.source();j.name("subject").value(s.subject().name()).name("stat").value(s.stat().name());}else{ResourceValueSource s=(ResourceValueSource)x.source();j.name("holder").value(s.holder().name()).name("resource");ref(j,s.resource());}j.endObject().endObject();}else throw new IllegalArgumentException("unsupported value class "+v.getClass().getName());}
	private static void duration(CanonicalJsonWriter j,DurationSpec v){j.beginObject().name("kind").value(v.kind().name()).name("turns").value(v.turns()).endObject();}
	private static void delivery(CanonicalJsonWriter j,DeliverySpec v){j.beginObject().name("node_id").value(v.nodeId().value()).name("variant_key").value(v.variantKey());if(v instanceof DirectDeliverySpec)j.name("requires_line_of_sight").value(((DirectDeliverySpec)v).requiresLineOfSight());else if(v instanceof ProjectileDeliverySpec){ProjectileDeliverySpec x=(ProjectileDeliverySpec)v;j.name("path_policy").value(x.pathPolicy().name()).name("speed_class").value(x.speedClass()).name("presentation_key").value(x.presentationKey());}else if(v instanceof TraceDeliverySpec){TraceDeliverySpec x=(TraceDeliverySpec)v;j.name("width").value(x.width()).name("stops_at_first_blocking_cell").value(x.stopsAtFirstBlockingCell());}else if(v instanceof GroundDeliverySpec)j.name("requires_visible_cell").value(((GroundDeliverySpec)v).requiresVisibleCell());else if(!(v instanceof UnconfiguredDeliverySpec)&&!(v instanceof SelfDeliverySpec)&&!(v instanceof ContactDeliverySpec))throw new IllegalArgumentException("unsupported delivery class "+v.getClass().getName());j.endObject();}
	private static void targeting(CanonicalJsonWriter j,TargetingSpec v){j.beginObject().name("node_id").value(v.nodeId().value()).name("selector").value(v.selector().variantKey()).name("coverage").value(v.coverage().variantKey()).name("filter").value(v.filter().variantKey());if(v.coverage() instanceof RadiusCoverageSpec)j.name("coverage_radius").value(((RadiusCoverageSpec)v.coverage()).radius());else if(v.coverage() instanceof LineCoverageSpec)j.name("coverage_length").value(((LineCoverageSpec)v.coverage()).length()).name("coverage_width").value(((LineCoverageSpec)v.coverage()).width());if(v.filter() instanceof RelationFilterSpec){RelationFilterSpec f=(RelationFilterSpec)v.filter();j.name("filter_relation").value(f.relationToClassOwner().name()).name("filter_include_self").value(f.includeSelf());}j.name("range").value(v.range()).name("maximum_targets").value(v.maximumTargets()).name("line_of_sight").value(v.lineOfSight().name()).name("ordering").value(v.ordering().name()).endObject();}
	private static void modifier(CanonicalJsonWriter j,ModifierSpec v){if(v==null){j.value((String)null);return;}j.beginObject().name("node_id").value(v.nodeId().value()).name("variant_key").value(v.variantKey());if(v instanceof RepeatModifierSpec)j.name("repeat_count").value(((RepeatModifierSpec)v).repeatCount()).name("target_policy").value(((RepeatModifierSpec)v).targetPolicy().name());else if(v instanceof IntensityModifierSpec)j.name("numerator").value(((IntensityModifierSpec)v).numerator()).name("denominator").value(((IntensityModifierSpec)v).denominator());else if(v instanceof ExtendDurationModifierSpec)j.name("additional_turns").value(((ExtendDurationModifierSpec)v).additionalTurns());else if(v instanceof PierceModifierSpec)j.name("additional_targets").value(((PierceModifierSpec)v).additionalTargets());else if(v instanceof BounceModifierSpec)j.name("bounces").value(((BounceModifierSpec)v).bounces()).name("bounce_range").value(((BounceModifierSpec)v).bounceRange());else if(!(v instanceof UnconfiguredModifierSpec))throw new IllegalArgumentException("unsupported modifier class "+v.getClass().getName());j.endObject();}
	private static void cost(CanonicalJsonWriter j,CostSpec v){j.beginObject().name("node_id").value(v.nodeId().value()).name("variant_key").value(v.variantKey());if(v instanceof ResourceCostSpec){ResourceCostSpec x=(ResourceCostSpec)v;j.name("holder").value(x.holder().name()).name("resource");ref(j,x.resource());j.name("amount").value(x.amount());}else if(v instanceof HpCostSpec){HpCostSpec x=(HpCostSpec)v;j.name("amount").value(x.amount()).name("lethal_policy").value(x.lethalPolicy().name()).name("minimum_remaining_hp").value(x.minimumRemainingHp());}else if(v instanceof ActionTimeCostSpec)j.name("turns").value(((ActionTimeCostSpec)v).turns());else if(v instanceof CooldownCostSpec)j.name("turns").value(((CooldownCostSpec)v).turns());else if(v instanceof ItemCostSpec){ItemCostSpec x=(ItemCostSpec)v;j.name("item_category").value(x.itemFilter().category().name()).name("count").value(x.count());}else if(!(v instanceof NoCostSpec)&&!(v instanceof UnconfiguredCostSpec))throw new IllegalArgumentException("unsupported cost class "+v.getClass().getName());j.endObject();}
	private static void resourceOperation(CanonicalJsonWriter j,ResourceOperationSpec v){j.beginObject().name("operation_id").value(v.operationId().value()).name("variant_key").value(v.variant().name());if(v instanceof GainResourceSpec){GainResourceSpec x=(GainResourceSpec)v;j.name("holder").value(x.holder().name()).name("resource");ref(j,x.resource());j.name("amount");value(j,x.amount());j.name("overflow_policy").value(x.overflowPolicy().name());}else if(v instanceof DrainResourceSpec){DrainResourceSpec x=(DrainResourceSpec)v;j.name("holder").value(x.holder().name()).name("resource");ref(j,x.resource());j.name("amount");value(j,x.amount());j.name("insufficient_policy").value(x.insufficientPolicy().name());}else if(v instanceof SetResourceSpec){SetResourceSpec x=(SetResourceSpec)v;j.name("holder").value(x.holder().name()).name("resource");ref(j,x.resource());j.name("value");value(j,x.value());}else if(v instanceof ClearResourceSpec){ClearResourceSpec x=(ClearResourceSpec)v;j.name("holder").value(x.holder().name()).name("resource");ref(j,x.resource());}else if(v instanceof ConvertResourceSpec){ConvertResourceSpec x=(ConvertResourceSpec)v;j.name("holder").value(x.holder().name()).name("source");ref(j,x.source());j.name("source_amount").value(x.sourceAmount()).name("target");ref(j,x.target());j.name("target_amount").value(x.targetAmount()).name("conversion_policy").value(x.conversionPolicy().name()).name("target_overflow_policy").value(x.targetOverflowPolicy().name());}else if(v instanceof ReserveResourceSpec){ReserveResourceSpec x=(ReserveResourceSpec)v;j.name("holder").value(x.holder().name()).name("resource");ref(j,x.resource());j.name("amount").value(x.amount()).name("duration_turns").value(x.durationTurns()).name("expiry_policy").value(x.expiryPolicy().name());}else if(v instanceof SuppressResourceSpec){SuppressResourceSpec x=(SuppressResourceSpec)v;j.name("holder").value(x.holder().name()).name("resource");ref(j,x.resource());j.name("duration_turns").value(x.durationTurns()).name("mode").value(x.mode().name());}else throw new IllegalArgumentException("unsupported resource operation "+v.getClass().getName());j.endObject();}
	private static void constraint(CanonicalJsonWriter j,SkillConstraintSpec v){if(v==null){j.value((String)null);return;}if(!(v instanceof UnconfiguredSkillConstraintSpec))throw new IllegalArgumentException("unsupported constraint class "+v.getClass().getName());j.beginObject().name("node_id").value(v.constraintId().value()).name("variant_key").value(v.variantKey()).endObject();}
	private static void section(CanonicalJsonWriter j,DeferredSectionSpec v){j.beginObject().name("section_key").value(v.sectionKey()).name("implementation_state").value(v.state().name()).endObject();}
	private static void ref(CanonicalJsonWriter j,TypedRef v){j.beginObject().name("ref_kind").value(v.kind().name()).name("target_id").value(v.targetId().value()).name("last_known_display_name").value(v.lastKnownDisplayName()).endObject();}

	private static ResourceSpec readResource(JsonValue v){variant(v,"RESOURCE");state(v,ImplementationState.DECLARED);JsonValue hud=req(v,"hud");return new ResourceSpec(id(v,"id"),name(v,"display_name"),reqInt(v,"minimum"),reqInt(v,"maximum"),reqInt(v,"initial_value"),en(ResourceSpec.ResourceOverflowPolicy.class,v,"default_overflow_policy"),new ResourceSpec.ResourceHudSpec(reqBool(hud,"visible"),reqInt(hud,"order"),reqString(hud,"presentation_key")));}
	private static MarkSpec readMark(JsonValue v){variant(v,"MARK");state(v,ImplementationState.DECLARED);return new MarkSpec(id(v,"id"),name(v,"display_name"),en(MarkSpec.MarkKind.class,v,"kind"),reqInt(v,"minimum"),reqInt(v,"maximum"),reqInt(v,"initial_value"),en(MarkSpec.MarkDurationPolicy.class,v,"duration_policy"),reqInt(v,"default_duration_turns"),en(MarkSpec.MarkRefreshPolicy.class,v,"refresh_policy"),en(MarkSpec.MarkOverflowPolicy.class,v,"overflow_policy"),en(MarkSpec.MarkProvenancePolicy.class,v,"provenance_policy"));}
	private static ModeGroupSpec readModeGroup(JsonValue v){variant(v,"MODE_GROUP");state(v,ImplementationState.DECLARED);return new ModeGroupSpec(id(v,"id"),name(v,"display_name"),en(ModeGroupSpec.ModeGroupPolicy.class,v,"policy"));}
	private static ModeSpec readMode(JsonValue v){variant(v,"MODE");state(v,ImplementationState.DECLARED);return new ModeSpec(id(v,"id"),name(v,"display_name"),(ModeGroupRef)readRef(req(v,"group"),RefKind.MODE_GROUP),reqBool(v,"initial"),en(ModeSpec.ModeDurationPolicy.class,v,"duration_policy"),reqInt(v,"default_duration_turns"));}
	private static EntityCapacitySpec readCapacity(JsonValue v){variant(v,"ENTITY_CAPACITY");state(v,ImplementationState.DECLARED);EnumSet<EntityType> types=EnumSet.noneOf(EntityType.class);for(JsonValue item:array(v,"entity_types"))types.add(en(EntityType.class,item.asString()));return new EntityCapacitySpec(id(v,"id"),name(v,"display_name"),types,reqInt(v,"maximum"),en(EntityCapacitySpec.CapacityOverflowPolicy.class,v,"overflow_policy"));}
	private static EntitySpec readEntity(JsonValue v){variant(v,"ENTITY");ImplementationState state=state(v,null);JsonValue cap=req(v,"capacity");CapacityRef ref=cap.isNull()?null:(CapacityRef)readRef(cap,RefKind.CAPACITY);DeferredEntityFacetSpec body=readFacet(req(v,"body"),EntityFacetKind.BODY);DeferredEntityFacetSpec spawn=readFacet(req(v,"spawn_policy"),EntityFacetKind.SPAWN_POLICY);DeferredEntityFacetSpec ownership=readFacet(req(v,"ownership"),EntityFacetKind.OWNERSHIP);DeferredEntityFacetSpec relation=readFacet(req(v,"relation"),EntityFacetKind.RELATION);DeferredEntityFacetSpec persistence=readFacet(req(v,"persistence"),EntityFacetKind.PERSISTENCE);List<EntityCapabilitySpec> capabilities=new ArrayList<>();for(JsonValue capability:array(v,"capabilities"))capabilities.add(readCapability(capability));return new EntitySpec(id(v,"id"),name(v,"display_name"),en(EntityType.class,v,"entity_type"),body,spawn,ownership,relation,ref,persistence,capabilities,state);}
	private static DeferredEntityFacetSpec readFacet(JsonValue v,EntityFacetKind expected){EntityFacetKind kind=en(EntityFacetKind.class,v,"facet_kind");if(kind!=expected)throw new UnsupportedValue("entity facet kind mismatch: expected "+expected+" got "+kind);ImplementationState state=en(ImplementationState.class,v,"implementation_state");return new DeferredEntityFacetSpec(kind,reqString(v,"variant_key"),state);}
	private static EntityCapabilitySpec readCapability(JsonValue v){String kind=reqString(v,"capability_kind");String variant=reqString(v,"variant_key");ImplementationState state=en(ImplementationState.class,v,"implementation_state");if("RESOURCE_STORAGE".equals(kind)){if(!ResourceStorageCapability.VARIANT.equals(variant)||state!=ImplementationState.DEFERRED)throw new UnsupportedValue("unsupported resource storage capability variant/state");List<EntityResourceSlotSpec> slots=new ArrayList<>();for(JsonValue slot:array(v,"slots"))slots.add(new EntityResourceSlotSpec((ResourceRef)readRef(req(slot,"resource"),RefKind.RESOURCE),reqInt(slot,"initial_value"),reqInt(slot,"maximum_override")));return new ResourceStorageCapability(slots);}if("DEFERRED_CAPABILITY".equals(kind))return new DeferredEntityCapabilitySpec(variant,state);throw new UnsupportedValue("unknown entity capability variant "+kind);}
	private static AbilityPoolSpec readAbilityPool(JsonValue v){variant(v,"ABILITY_POOL");state(v,ImplementationState.DECLARED);return new AbilityPoolSpec(id(v,"id"),name(v,"display_name"),reqInt(v,"capacity"),en(AbilityPoolSpec.AbilityOverflowPolicy.class,v,"overflow_policy"));}
	private static PropertySpec readProperty(JsonValue v){variant(v,"PROPERTY");state(v,ImplementationState.DECLARED);return new PropertySpec(id(v,"id"),name(v,"display_name"),en(PropertySpec.PropertyValueKind.class,v,"value_kind"),reqInt(v,"maximum_stack"));}
	private static SynthesisRecipeSpec readRecipe(JsonValue v){variant(v,"RECIPE");ImplementationState state=state(v,null);List<SynthesisRecipeSpec.PropertyInput> inputs=new ArrayList<>();for(JsonValue item:array(v,"inputs"))inputs.add(new SynthesisRecipeSpec.PropertyInput((PropertyRef)readRef(req(item,"property"),RefKind.PROPERTY),reqInt(item,"amount")));return new SynthesisRecipeSpec(id(v,"id"),name(v,"display_name"),inputs,reqString(v,"output_variant"),state);}
	private static ContractNodeSpec readNode(JsonValue v,ContractNodeSpec.NodeKind expected){variant(v,"CONTRACT_NODE");ContractNodeSpec.NodeKind kind=en(ContractNodeSpec.NodeKind.class,v,"node_kind");if(kind!=expected)throw new UnsupportedValue("node kind does not match list: "+kind);ImplementationState stored=state(v,null);String key=reqString(v,"variant_key");StableId id=id(v,"id");DisplayName name=name(v,"display_name");ContractNodeSpec result;
		if(kind==ContractNodeSpec.NodeKind.COMPONENT&&BasicAttackComponentSpec.VARIANT.equals(key))result=new BasicAttackComponentSpec(id,name,en(BasicAttackComponentSpec.BasicAttackAvailability.class,v,"availability"),reqInt(v,"damage_numerator"),reqInt(v,"damage_denominator"),new ItemFilterSpec(en(ItemFilterSpec.ItemCategory.class,v,"allowed_weapons")),reqInt(v,"action_time_turns"));
		else if(kind==ContractNodeSpec.NodeKind.COMPONENT&&ResourceFlowComponentSpec.VARIANT.equals(key))result=new ResourceFlowComponentSpec(id,name,readTrigger(req(v,"trigger")),readCondition(req(v,"condition")),readResourceOperation(req(v,"operation")));
		else if(kind==ContractNodeSpec.NodeKind.COMPONENT&&ActiveResourceOperationComponentSpec.VARIANT.equals(key))result=new ActiveResourceOperationComponentSpec(id,name,name(v,"operation_display_name"),id(v,"class_operation_id"),readResourceOperation(req(v,"operation")),readCost(req(v,"cost")),reqInt(v,"action_time_turns"));
		else if(kind==ContractNodeSpec.NodeKind.OPERATION&&ResourceClassOperationSpec.VARIANT.equals(key)){JsonValue source=req(v,"source_component");result=new ResourceClassOperationSpec(id,name,source.isNull()?null:(ComponentRef)readRef(source,RefKind.COMPONENT),readTrigger(req(v,"activation")),readCondition(req(v,"condition")),readCost(req(v,"cost")),reqInt(v,"action_time_turns"),readResourceOperation(req(v,"operation")),reqBool(v,"hud_visible"),reqInt(v,"hud_order"));}
		else{if(stored!=ImplementationState.UNSUPPORTED&&stored!=ImplementationState.DEFERRED)throw new UnsupportedValue("unknown executable node variant "+key);result=new ContractNodeSpec(id,name,kind,key,stored);}
		if(stored!=result.implementationState())throw new UnsupportedValue("node implementation state mismatch: "+key);return result;}
	private static SkillSpec readSkill(JsonValue v){String variant=reqString(v,"variant");if("CONTRACT_NODE".equals(variant)){ContractNodeSpec node=readNode(v,ContractNodeSpec.NodeKind.SKILL);return SkillSpec.fromLegacyEnvelope(node);}if(!"SKILL".equals(variant))throw new UnsupportedValue("unknown skill variant "+variant);if(!SkillSpec.VERSION.equals(reqString(v,"skill_version")))throw new UnsupportedValue("unsupported skill version "+reqString(v,"skill_version"));ImplementationState stored=state(v,null);SkillSpec skill=new SkillSpec(id(v,"id"),name(v,"display_name"),readTrigger(req(v,"activation")),readCondition(req(v,"condition")),readChain(req(v,"effects")),readDelivery(req(v,"delivery")),readTargeting(req(v,"targeting")),readModifier(req(v,"modifier")),readCost(req(v,"cost")),readConstraint(req(v,"constraint")));if(stored!=skill.implementationState())throw new UnsupportedValue("skill implementation state mismatch: stored="+stored+" calculated="+skill.implementationState());return skill;}
	private static TriggerSpec readTrigger(JsonValue v){StableId id=id(v,"node_id");String key=reqString(v,"variant_key");if(ActiveTriggerSpec.VARIANT.equals(key))return new ActiveTriggerSpec(id);if("EVENT".equals(key))return new EventTriggerSpec(id,en(com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.runtime.GameplayEventContext.RuleEventType.class,v,"event"));if(UnconfiguredTriggerSpec.VARIANT.equals(key))return new UnconfiguredTriggerSpec(id);throw new UnsupportedValue("unknown trigger variant "+key);}
	private static ConditionExpr readCondition(JsonValue v){String key=reqString(v,"variant_key");if(UnconfiguredConditionExpr.VARIANT.equals(key))return new UnconfiguredConditionExpr();if(AlwaysCondition.VARIANT.equals(key))return new AlwaysCondition();if(AllOfCondition.VARIANT.equals(key)){List<ConditionExpr> children=new ArrayList<>();for(JsonValue child:array(v,"children"))children.add(readCondition(child));return new AllOfCondition(children);}if("BUILTIN_STAT_COMPARE".equals(key))return new BuiltinStatCompareCondition(id(v,"node_id"),en(SubjectSelector.class,v,"subject"),en(BuiltinStatRef.class,v,"stat"),en(ComparisonOperator.class,v,"operator"),readValue(req(v,"value")));if("RESOURCE_COMPARE".equals(key))return new ResourceCompareCondition(id(v,"node_id"),en(ResourceHolderSelector.class,v,"holder"),(ResourceRef)readRef(req(v,"resource"),RefKind.RESOURCE),en(ComparisonOperator.class,v,"operator"),reqInt(v,"value"));throw new UnsupportedValue("unknown condition variant "+key);}
	private static EffectChainSpec readChain(JsonValue v){StableId id=id(v,"chain_id");EffectSpec primary=readEffect(req(v,"primary"));JsonValue secondary=req(v,"secondary");SecondaryEffectSpec value=null;if(!secondary.isNull()){String activation=reqString(secondary,"activation");if(!ImmediateOnPrimarySuccess.VARIANT.equals(activation))throw new UnsupportedValue("unsupported secondary activation "+activation);value=new SecondaryEffectSpec(readEffect(req(secondary,"effect")),new ImmediateOnPrimarySuccess());}return new EffectChainSpec(id,primary,value);}
	private static EffectSpec readEffect(JsonValue v){StableId id=id(v,"effect_id");JsonValue familyValue=req(v,"family");EffectFamily family=familyValue.isNull()?null:en(EffectFamily.class,familyValue.asString());EffectVariantKey key=en(EffectVariantKey.class,v,"variant_key");if(key==EffectVariantKey.UNCONFIGURED)return new UnconfiguredEffectSpec(id,family);EffectSpec result;switch(key){
		case DIRECT_DAMAGE:result=new DirectDamageEffectSpec(id,readValue(req(v,"amount")),en(DirectDamageEffectSpec.DamageType.class,v,"damage_type"),en(DirectDamageEffectSpec.NativeDefensePolicy.class,v,"defense_policy"));break;
		case PERCENT_MAX_HP_DAMAGE:result=new PercentMaxHpDamageEffectSpec(id,reqInt(v,"percent"),reqInt(v,"absolute_cap"),en(PercentMaxHpDamageEffectSpec.ProtectedTargetPolicy.class,v,"protected_target_policy"));break;
		case MISSING_HP_DAMAGE:result=new MissingHpDamageEffectSpec(id,readValue(req(v,"base_amount")),reqInt(v,"missing_hp_numerator"),reqInt(v,"missing_hp_denominator"),reqInt(v,"absolute_cap"),en(DirectDamageEffectSpec.DamageType.class,v,"damage_type"));break;
		case EXECUTE:{JsonValue fallback=req(v,"fallback_damage");result=new ExecuteEffectSpec(id,reqInt(v,"hp_percent_threshold"),fallback.isNull()?null:readValue(fallback),en(ExecuteEffectSpec.ProtectedTargetPolicy.class,v,"protected_target_policy"));break;}
		case APPLY_STATUS:result=new ApplyStatusEffectSpec(id,en(StatusRef.class,v,"status"),readValue(req(v,"intensity")),readDuration(req(v,"duration")),en(ApplyStatusEffectSpec.StatusStackingPolicy.class,v,"stacking"));break;
		case PUSH:result=new PushEffectSpec(id,reqInt(v,"distance"),en(MovementPolicies.CollisionPolicy.class,v,"collision_policy"));break;case PULL:result=new PullEffectSpec(id,reqInt(v,"distance"),en(MovementPolicies.CollisionPolicy.class,v,"collision_policy"));break;case THROW:result=new ThrowEffectSpec(id,reqInt(v,"distance"),en(MovementPolicies.CollisionPolicy.class,v,"collision_policy"));break;
		case DASH:result=new DashEffectSpec(id,reqInt(v,"maximum_distance"),en(MovementPolicies.PathPolicy.class,v,"path_policy"));break;case TELEPORT:result=new TeleportEffectSpec(id,reqInt(v,"maximum_range"),en(MovementPolicies.DestinationPolicy.class,v,"destination_policy"));break;case SWAP_POSITION:result=new SwapPositionEffectSpec(id,en(MovementPolicies.SwapLegalityPolicy.class,v,"legality_policy"));break;
		case HEAL:result=new HealEffectSpec(id,readValue(req(v,"amount")));break;case BARRIER:result=new BarrierEffectSpec(id,readValue(req(v,"amount")),en(BarrierEffectSpec.BarrierOverflowPolicy.class,v,"overflow_policy"));break;case TEMPORARY_HP:result=new TemporaryHpEffectSpec(id,readValue(req(v,"amount")),readDuration(req(v,"duration")),en(TemporaryHpEffectSpec.TemporaryHpStackingPolicy.class,v,"stacking"));break;
		case MITIGATE:result=new MitigateEffectSpec(id,reqInt(v,"percent"),readDuration(req(v,"duration")),en(MitigateEffectSpec.MitigationStackingPolicy.class,v,"stacking"));break;case REDIRECT_DAMAGE:result=new RedirectDamageEffectSpec(id,reqInt(v,"percent"),en(SubjectSelector.class,v,"recipient"),readDuration(req(v,"duration")));break;
		case CLEANSE:{JsonValue status=req(v,"status");StatusFilterSpec filter=en(StatusFilterSpec.Kind.class,v,"filter_kind")==StatusFilterSpec.Kind.ANY_NEGATIVE?StatusFilterSpec.anyNegative():StatusFilterSpec.specific(en(StatusRef.class,status.asString()));result=new CleanseEffectSpec(id,filter,reqInt(v,"maximum_count"));break;}
		case RESOURCE_OPERATION:result=new ResourceOperationEffectSpec(id,readResourceOperation(req(v,"operation")));break;default:throw new UnsupportedValue("effect variant unavailable in P04: "+key);}
		if(result.family()!=family)throw new UnsupportedValue(key+" family mismatch");return result;}
	private static ValueSpec readValue(JsonValue v){String key=reqString(v,"variant_key");if(FixedValueSpec.VARIANT.equals(key))return new FixedValueSpec(reqInt(v,"value"));if("SCALED".equals(key)){JsonValue source=req(v,"source");String sourceKey=reqString(source,"variant_key");ValueSourceSpec valueSource;if("BUILTIN_STAT".equals(sourceKey))valueSource=new BuiltinStatSource(en(SubjectSelector.class,source,"subject"),en(BuiltinStatRef.class,source,"stat"));else if("RESOURCE_VALUE".equals(sourceKey))valueSource=new ResourceValueSource(en(ResourceHolderSelector.class,source,"holder"),(ResourceRef)readRef(req(source,"resource"),RefKind.RESOURCE));else throw new UnsupportedValue("unknown value source "+sourceKey);return new ScaledValueSpec(reqInt(v,"base"),valueSource,reqInt(v,"numerator"),reqInt(v,"denominator"),reqInt(v,"minimum"),reqInt(v,"maximum"),en(ScaledValueSpec.RoundingMode.class,v,"rounding"));}throw new UnsupportedValue("unknown value variant "+key);}
	private static DurationSpec readDuration(JsonValue v){return new DurationSpec(en(DurationSpec.DurationKind.class,v,"kind"),reqInt(v,"turns"));}
	private static DeliverySpec readDelivery(JsonValue v){StableId id=id(v,"node_id");String key=reqString(v,"variant_key");if(UnconfiguredDeliverySpec.VARIANT.equals(key))return new UnconfiguredDeliverySpec(id);if(DirectDeliverySpec.VARIANT.equals(key))return new DirectDeliverySpec(id,reqBool(v,"requires_line_of_sight"));if("SELF".equals(key))return new SelfDeliverySpec(id);if("CONTACT".equals(key))return new ContactDeliverySpec(id);if("PROJECTILE".equals(key))return new ProjectileDeliverySpec(id,en(ProjectileDeliverySpec.ProjectilePathPolicy.class,v,"path_policy"),reqInt(v,"speed_class"),reqString(v,"presentation_key"));if("TRACE".equals(key))return new TraceDeliverySpec(id,reqInt(v,"width"),reqBool(v,"stops_at_first_blocking_cell"));if("GROUND".equals(key))return new GroundDeliverySpec(id,reqBool(v,"requires_visible_cell"));throw new UnsupportedValue("unknown delivery variant "+key);}
	private static TargetingSpec readTargeting(JsonValue v){StableId id=id(v,"node_id");String selectorKey=reqString(v,"selector");SelectorSpec selector;if(UnconfiguredSelectorSpec.VARIANT.equals(selectorKey))selector=new UnconfiguredSelectorSpec();else if(SelectedActorSelector.VARIANT.equals(selectorKey))selector=new SelectedActorSelector();else if(SelfSelector.VARIANT.equals(selectorKey))selector=new SelfSelector();else if(SelectedCellSelector.VARIANT.equals(selectorKey))selector=new SelectedCellSelector();else throw new UnsupportedValue("unknown selector variant "+selectorKey);String coverageKey=reqString(v,"coverage");CoverageSpec coverage;if(UnconfiguredCoverageSpec.VARIANT.equals(coverageKey))coverage=new UnconfiguredCoverageSpec();else if(SingleCoverageSpec.VARIANT.equals(coverageKey))coverage=new SingleCoverageSpec();else if("ADJACENT".equals(coverageKey))coverage=new AdjacentCoverageSpec();else if("RADIUS".equals(coverageKey))coverage=new RadiusCoverageSpec(reqInt(v,"coverage_radius"));else if("LINE".equals(coverageKey))coverage=new LineCoverageSpec(reqInt(v,"coverage_length"),reqInt(v,"coverage_width"));else throw new UnsupportedValue("unknown coverage variant "+coverageKey);String filterKey=reqString(v,"filter");EntityFilterExpr filter;if(UnconfiguredEntityFilterSpec.VARIANT.equals(filterKey))filter=new UnconfiguredEntityFilterSpec();else if(RelationFilterSpec.VARIANT.equals(filterKey))filter=new RelationFilterSpec(en(RelationFilterSpec.RelationAlignment.class,v,"filter_relation"),reqBool(v,"filter_include_self"));else if("ANY_ACTOR".equals(filterKey))filter=new AnyActorFilterSpec();else if("SELF".equals(filterKey))filter=new SelfFilterSpec();else throw new UnsupportedValue("unknown filter variant "+filterKey);return new TargetingSpec(id,selector,coverage,filter,reqInt(v,"range"),reqInt(v,"maximum_targets"),en(TargetingSpec.LineOfSightPolicy.class,v,"line_of_sight"),en(TargetingSpec.TargetOrdering.class,v,"ordering"));}
	private static ModifierSpec readModifier(JsonValue v){if(v.isNull())return null;String key=reqString(v,"variant_key");StableId id=id(v,"node_id");if(UnconfiguredModifierSpec.VARIANT.equals(key))return new UnconfiguredModifierSpec(id);if("REPEAT".equals(key))return new RepeatModifierSpec(id,reqInt(v,"repeat_count"),en(RepeatModifierSpec.RepeatTargetPolicy.class,v,"target_policy"));if("INTENSITY".equals(key))return new IntensityModifierSpec(id,reqInt(v,"numerator"),reqInt(v,"denominator"));if("EXTEND_DURATION".equals(key))return new ExtendDurationModifierSpec(id,reqInt(v,"additional_turns"));if("PIERCE".equals(key))return new PierceModifierSpec(id,reqInt(v,"additional_targets"));if("BOUNCE".equals(key))return new BounceModifierSpec(id,reqInt(v,"bounces"),reqInt(v,"bounce_range"));throw new UnsupportedValue("unknown modifier variant "+key);}
	private static CostSpec readCost(JsonValue v){String key=reqString(v,"variant_key");StableId id=id(v,"node_id");if(UnconfiguredCostSpec.VARIANT.equals(key))return new UnconfiguredCostSpec(id);if(NoCostSpec.VARIANT.equals(key))return new NoCostSpec(id);if("RESOURCE".equals(key))return new ResourceCostSpec(id,en(ResourceHolderSelector.class,v,"holder"),(ResourceRef)readRef(req(v,"resource"),RefKind.RESOURCE),reqInt(v,"amount"));if("HP".equals(key))return new HpCostSpec(id,reqInt(v,"amount"),en(HpCostSpec.HpLethalPolicy.class,v,"lethal_policy"),reqInt(v,"minimum_remaining_hp"));if("ACTION_TIME".equals(key))return new ActionTimeCostSpec(id,reqInt(v,"turns"));if("COOLDOWN".equals(key))return new CooldownCostSpec(id,reqInt(v,"turns"));if("ITEM".equals(key))return new ItemCostSpec(id,new ItemFilterSpec(en(ItemFilterSpec.ItemCategory.class,v,"item_category")),reqInt(v,"count"));throw new UnsupportedValue("unknown cost variant "+key);}
	private static ResourceOperationSpec readResourceOperation(JsonValue v){StableId id=id(v,"operation_id");ResourceOperationSpec.Variant variant=en(ResourceOperationSpec.Variant.class,v,"variant_key");ResourceHolderSelector holder=en(ResourceHolderSelector.class,v,"holder");switch(variant){case GAIN:return new GainResourceSpec(id,holder,(ResourceRef)readRef(req(v,"resource"),RefKind.RESOURCE),readValue(req(v,"amount")),en(ResourceSpec.ResourceOverflowPolicy.class,v,"overflow_policy"));case DRAIN:return new DrainResourceSpec(id,holder,(ResourceRef)readRef(req(v,"resource"),RefKind.RESOURCE),readValue(req(v,"amount")),en(DrainResourceSpec.InsufficientResourcePolicy.class,v,"insufficient_policy"));case SET:return new SetResourceSpec(id,holder,(ResourceRef)readRef(req(v,"resource"),RefKind.RESOURCE),readValue(req(v,"value")));case CLEAR:return new ClearResourceSpec(id,holder,(ResourceRef)readRef(req(v,"resource"),RefKind.RESOURCE));case CONVERT:return new ConvertResourceSpec(id,holder,(ResourceRef)readRef(req(v,"source"),RefKind.RESOURCE),reqInt(v,"source_amount"),(ResourceRef)readRef(req(v,"target"),RefKind.RESOURCE),reqInt(v,"target_amount"),en(ConvertResourceSpec.ConversionPolicy.class,v,"conversion_policy"),en(ResourceSpec.ResourceOverflowPolicy.class,v,"target_overflow_policy"));case RESERVE:return new ReserveResourceSpec(id,holder,(ResourceRef)readRef(req(v,"resource"),RefKind.RESOURCE),reqInt(v,"amount"),reqInt(v,"duration_turns"),en(ReserveResourceSpec.ReservationExpiryPolicy.class,v,"expiry_policy"));case SUPPRESS:return new SuppressResourceSpec(id,holder,(ResourceRef)readRef(req(v,"resource"),RefKind.RESOURCE),reqInt(v,"duration_turns"),en(SuppressResourceSpec.ResourceSuppressionMode.class,v,"mode"));default:throw new UnsupportedValue("unknown resource operation "+variant);}}
	private static SkillConstraintSpec readConstraint(JsonValue v){if(v.isNull())return null;String key=reqString(v,"variant_key");if(UnconfiguredSkillConstraintSpec.VARIANT.equals(key))return new UnconfiguredSkillConstraintSpec(id(v,"node_id"));throw new UnsupportedValue("unknown skill constraint variant "+key);}
	private static DeferredSectionSpec readSection(JsonValue v){ImplementationState state=en(ImplementationState.class,v,"implementation_state");return new DeferredSectionSpec(reqString(v,"section_key"),state);}
	private static TypedRef readRef(JsonValue v,RefKind expected){RefKind kind=en(RefKind.class,v,"ref_kind");if(kind!=expected)throw new UnsupportedValue("reference kind mismatch: expected "+expected+" got "+kind);StableId id=id(v,"target_id");String name=reqString(v,"last_known_display_name");switch(kind){case RESOURCE:return new ResourceRef(id,name);case MARK:return new MarkRef(id,name);case MODE_GROUP:return new ModeGroupRef(id,name);case MODE:return new ModeRef(id,name);case ENTITY:return new EntitySpecRef(id,name);case CAPACITY:return new CapacityRef(id,name);case COMPONENT:return new ComponentRef(id,name);case ABILITY_POOL:return new AbilityPoolRef(id,name);case PROPERTY:return new PropertyRef(id,name);case RECIPE:return new SynthesisRecipeRef(id,name);default:throw new UnsupportedValue("unknown reference kind "+kind);}}
	private static void variant(JsonValue v,String expected){String actual=reqString(v,"variant");if(!expected.equals(actual))throw new UnsupportedValue("unknown declaration variant "+actual+", expected "+expected);}
	private static ImplementationState state(JsonValue v,ImplementationState expected){ImplementationState actual=en(ImplementationState.class,v,"implementation_state");if(expected!=null&&actual!=expected)throw new UnsupportedValue("unexpected implementation state "+actual);return actual;}
	private static StableId id(JsonValue v,String key){return StableId.fromStored(reqString(v,key));}private static DisplayName name(JsonValue v,String key){return DisplayName.of(reqString(v,key));}
	private static JsonValue req(JsonValue v,String key){JsonValue result=v.get(key);if(result==null)throw new IllegalArgumentException("missing field "+key);return result;}
	private static String reqString(JsonValue v,String key){return req(v,key).asString();}private static int reqInt(JsonValue v,String key){return req(v,key).asInt();}private static boolean reqBool(JsonValue v,String key){return req(v,key).asBoolean();}
	private static<T extends Enum<T>>T en(Class<T> type,JsonValue v,String key){return en(type,reqString(v,key));}private static<T extends Enum<T>>T en(Class<T> type,String value){try{return Enum.valueOf(type,value);}catch(IllegalArgumentException error){throw new UnsupportedValue("unknown "+type.getSimpleName()+" variant "+value);}}
	private static List<JsonValue> array(JsonValue v,String key){JsonValue a=req(v,key);if(!a.isArray())throw new IllegalArgumentException(key+" is not an array");List<JsonValue> result=new ArrayList<>();for(JsonValue item=a.child;item!=null;item=item.next)result.add(item);return result;}
	private static final class UnsupportedValue extends RuntimeException{UnsupportedValue(String message){super(message);}}
}
