package com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.dependency;

import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.identity.StableId;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.spec.*;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.spec.component.*;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.spec.resource.ResourceOperationSpec;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.spec.skill.*;
import java.util.ArrayList;import java.util.HashMap;import java.util.List;import java.util.Map;

/** Build-wide namespace validation, including every executable nested node ID. */
public final class GlobalNodeIdentityValidator {
	public DependencyReport validate(ClassBuildSpec build){List<DependencyDiagnostic> out=new ArrayList<>();Map<StableId,String> seen=new HashMap<>();add(out,seen,build.buildId(),"build","build");
		for(StableTarget node:build.allTargets())add(out,seen,node.id(),path(node),expected(node));
		for(int i=0;i<build.skills().size();i++)collectSkill(out,seen,build.skills().get(i),"skills["+i+"]");
		for(int i=0;i<build.classComponents().size();i++)collectComponent(out,seen,build.classComponents().get(i),"class_components["+i+"]");
		for(int i=0;i<build.classOperations().size();i++)collectOperationNode(out,seen,build.classOperations().get(i),"class_operations["+i+"]");
		return new DependencyReport(out);
	}
	private static void collectSkill(List<DependencyDiagnostic> out,Map<StableId,String> seen,SkillSpec s,String path){if(!s.typed())return;add(out,seen,s.activation().nodeId(),path+".activation","trigger");collectCondition(out,seen,s.condition(),path+".condition");add(out,seen,s.effects().chainId(),path+".effects.chain","chain");collectEffect(out,seen,s.effects().primary(),path+".effects.primary");if(s.effects().secondary()!=null)collectEffect(out,seen,s.effects().secondary().effect(),path+".effects.secondary");add(out,seen,s.delivery().nodeId(),path+".delivery","delivery");add(out,seen,s.targeting().nodeId(),path+".targeting","targeting");if(s.modifier()!=null)add(out,seen,s.modifier().nodeId(),path+".modifier","modifier");add(out,seen,s.cost().nodeId(),path+".cost","cost");if(s.constraint()!=null)add(out,seen,s.constraint().constraintId(),path+".constraint","constraint");}
	private static void collectCondition(List<DependencyDiagnostic> out,Map<StableId,String> seen,ConditionExpr c,String path){if(c instanceof AllOfCondition){int i=0;for(ConditionExpr child:((AllOfCondition)c).children())collectCondition(out,seen,child,path+"["+(i++)+"]");}else if(c instanceof BuiltinStatCompareCondition)add(out,seen,((BuiltinStatCompareCondition)c).nodeId(),path,"condition");else if(c instanceof ResourceCompareCondition)add(out,seen,((ResourceCompareCondition)c).nodeId(),path,"condition");}
	private static void collectEffect(List<DependencyDiagnostic> out,Map<StableId,String> seen,EffectSpec e,String path){add(out,seen,e.effectId(),path+".effect_id","effect");if(e instanceof ResourceOperationEffectSpec)add(out,seen,((ResourceOperationEffectSpec)e).operation().operationId(),path+".operation_id","op");}
	private static void collectComponent(List<DependencyDiagnostic> out,Map<StableId,String> seen,ContractNodeSpec node,String path){if(node instanceof ResourceFlowComponentSpec){ResourceFlowComponentSpec x=(ResourceFlowComponentSpec)node;add(out,seen,x.trigger().nodeId(),path+".trigger","trigger");collectCondition(out,seen,x.condition(),path+".condition");add(out,seen,x.operation().operationId(),path+".operation","op");}else if(node instanceof ActiveResourceOperationComponentSpec){ActiveResourceOperationComponentSpec x=(ActiveResourceOperationComponentSpec)node;add(out,seen,x.operation().operationId(),path+".resource_operation","op");add(out,seen,x.cost().nodeId(),path+".cost","cost");}}
	private static void collectOperationNode(List<DependencyDiagnostic> out,Map<StableId,String> seen,ContractNodeSpec node,String path){if(node instanceof ResourceClassOperationSpec){ResourceClassOperationSpec x=(ResourceClassOperationSpec)node;add(out,seen,x.activation().nodeId(),path+".activation","trigger");collectCondition(out,seen,x.condition(),path+".condition");add(out,seen,x.cost().nodeId(),path+".cost","cost");add(out,seen,x.operation().operationId(),path+".payload.operation","op");}}
	private static void add(List<DependencyDiagnostic> out,Map<StableId,String> seen,StableId id,String path,String prefix){if(id==null)return;if(StableId.isCanonical(id.value())&&!prefix.equals(id.prefix()))out.add(new DependencyDiagnostic(id,path,DependencyState.HARD_CONFLICT,id,"identity.prefix_mismatch"));String prior=seen.put(id,path);if(prior!=null)out.add(new DependencyDiagnostic(id,path,DependencyState.HARD_CONFLICT,id,"dependency.duplicate_id"));}
	private static String path(StableTarget target){return target.id().value();}private static String expected(StableTarget target){if(target instanceof SkillSpec)return"skill";if(target instanceof ContractNodeSpec){switch(((ContractNodeSpec)target).nodeKind()){case COMPONENT:return"component";case CONSTRAINT:return"constraint";case OPERATION:return"op";case SKILL:return"skill";default:throw new AssertionError();}}switch(target.refKind()){case RESOURCE:return"res";case MARK:return"mark";case MODE_GROUP:return"modegrp";case MODE:return"mode";case ENTITY:return"entity";case CAPACITY:return"capacity";case ABILITY_POOL:return"abilitypool";case PROPERTY:return"property";case RECIPE:return"recipe";case COMPONENT:return"component";default:throw new AssertionError();}}
}
