package com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.runtime;

import com.shatteredpixel.shatteredpixeldungeon.Dungeon;
import com.shatteredpixel.shatteredpixeldungeon.actors.Actor;
import com.shatteredpixel.shatteredpixeldungeon.actors.Char;
import com.shatteredpixel.shatteredpixeldungeon.actors.buffs.*;
import com.shatteredpixel.shatteredpixeldungeon.items.scrolls.ScrollOfTeleportation;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.compile.CompiledSkill;

import java.util.ArrayList;

/** Package-private typed P04 executors. Authoring classes never cross this boundary. */
final class P04EffectExecutors {
	private P04EffectExecutors() {}
	static EffectPreflightResult target(Char target,String key){return target!=null&&target.isAlive()?EffectPreflightResult.ready():EffectPreflightResult.failed(EffectPreflightResult.Status.TARGET_UNAVAILABLE,key+".target_unavailable");}
	static int positive(CompiledSkill.Value value,RuntimeExecutionContext context){return Math.max(0,context.resolve(value));}
	static EffectResult nativeDamage(int amount,Char target,RuntimeExecutionContext context,RuntimeTrace trace,String variant,String id){RuntimeExecutionContext.DamageOutcome out=context.applyNativeDamage(amount,target);trace.record("effect","variant="+variant+" effect="+id+" requested="+amount+" hp_before="+out.hpBefore()+" hp_after="+out.hpAfter()+" applied="+out.appliedAmount());return EffectResult.applied(out.appliedAmount());}

	static final class PercentMaxHp implements EffectExecutor<CompiledSkill.PercentMaxHpDamageEffect>{public CompiledSkill.EffectVariant variant(){return CompiledSkill.EffectVariant.PERCENT_MAX_HP_DAMAGE;}public Class<CompiledSkill.PercentMaxHpDamageEffect> effectType(){return CompiledSkill.PercentMaxHpDamageEffect.class;}public EffectPreflightResult preflight(CompiledSkill.PercentMaxHpDamageEffect e,Char t,RuntimeExecutionContext c){if(e.percent()<1||e.percent()>100||e.absoluteCap()<0)return EffectPreflightResult.failed(EffectPreflightResult.Status.UNSUPPORTED_PARAMETERS,"percent_max_hp.parameters");if(protectedTarget(t)&&e.protectedTargetPolicy()==CompiledSkill.ProtectedTargetPolicy.BLOCK)return EffectPreflightResult.failed(EffectPreflightResult.Status.IMMUNE,"percent_max_hp.protected");return target(t,"percent_max_hp");}public EffectResult execute(CompiledSkill.PercentMaxHpDamageEffect e,Char t,RuntimeExecutionContext c,RuntimeTrace tr){EffectPreflightResult p=preflight(e,t,c);if(!p.readyForExecute())return EffectExecutorRegistry.failed(p);int amount=Math.max(1,t.HT*e.percent()/100);if(e.absoluteCap()>0)amount=Math.min(amount,e.absoluteCap());return nativeDamage(amount,t,c,tr,"PERCENT_MAX_HP_DAMAGE",e.effectId().value());}}
	static final class MissingHp implements EffectExecutor<CompiledSkill.MissingHpDamageEffect>{public CompiledSkill.EffectVariant variant(){return CompiledSkill.EffectVariant.MISSING_HP_DAMAGE;}public Class<CompiledSkill.MissingHpDamageEffect> effectType(){return CompiledSkill.MissingHpDamageEffect.class;}public EffectPreflightResult preflight(CompiledSkill.MissingHpDamageEffect e,Char t,RuntimeExecutionContext c){if(e.denominator()<1||e.numerator()<0||e.absoluteCap()<0)return EffectPreflightResult.failed(EffectPreflightResult.Status.UNSUPPORTED_PARAMETERS,"missing_hp.parameters");return target(t,"missing_hp");}public EffectResult execute(CompiledSkill.MissingHpDamageEffect e,Char t,RuntimeExecutionContext c,RuntimeTrace tr){EffectPreflightResult p=preflight(e,t,c);if(!p.readyForExecute())return EffectExecutorRegistry.failed(p);long amount=(long)positive(e.value(),c)+(long)Math.max(0,t.HT-t.HP)*e.numerator()/e.denominator();if(e.absoluteCap()>0)amount=Math.min(amount,e.absoluteCap());return nativeDamage((int)Math.min(Integer.MAX_VALUE,amount),t,c,tr,"MISSING_HP_DAMAGE",e.effectId().value());}}
	static final class Execute implements EffectExecutor<CompiledSkill.ExecuteEffect>{public CompiledSkill.EffectVariant variant(){return CompiledSkill.EffectVariant.EXECUTE;}public Class<CompiledSkill.ExecuteEffect> effectType(){return CompiledSkill.ExecuteEffect.class;}public EffectPreflightResult preflight(CompiledSkill.ExecuteEffect e,Char t,RuntimeExecutionContext c){if(e.threshold()<1||e.threshold()>100)return EffectPreflightResult.failed(EffectPreflightResult.Status.UNSUPPORTED_PARAMETERS,"execute.threshold");return target(t,"execute");}public EffectResult execute(CompiledSkill.ExecuteEffect e,Char t,RuntimeExecutionContext c,RuntimeTrace tr){EffectPreflightResult p=preflight(e,t,c);if(!p.readyForExecute())return EffectExecutorRegistry.failed(p);boolean threshold=t.HT>0&&t.HP*100<=t.HT*e.threshold();boolean protectedValue=protectedTarget(t);if(threshold&&!protectedValue)return nativeDamage(t.HP,t,c,tr,"EXECUTE",e.effectId().value());if(protectedValue&&e.protectedTargetPolicy()==CompiledSkill.ProtectedTargetPolicy.BLOCK)return EffectResult.failed(EffectResult.Status.IMMUNE,"execute.protected");int fallback=e.fallback()==null?0:positive(e.fallback(),c);return nativeDamage(fallback,t,c,tr,"EXECUTE_FALLBACK",e.effectId().value());}}

	static final class ApplyStatus implements EffectExecutor<CompiledSkill.ApplyStatusEffect>{public CompiledSkill.EffectVariant variant(){return CompiledSkill.EffectVariant.APPLY_STATUS;}public Class<CompiledSkill.ApplyStatusEffect> effectType(){return CompiledSkill.ApplyStatusEffect.class;}public EffectPreflightResult preflight(CompiledSkill.ApplyStatusEffect e,Char t,RuntimeExecutionContext c){if(e.duration().kind()!=CompiledSkill.DurationKind.TURN_BASED||c.duration(e.duration())<1||positive(e.value(),c)<1)return EffectPreflightResult.failed(EffectPreflightResult.Status.UNSUPPORTED_PARAMETERS,"status.parameters");return target(t,"status");}public EffectResult execute(CompiledSkill.ApplyStatusEffect e,Char t,RuntimeExecutionContext c,RuntimeTrace tr){EffectPreflightResult p=preflight(e,t,c);if(!p.readyForExecute())return EffectExecutorRegistry.failed(p);int turns=c.duration(e.duration()),intensity=positive(e.value(),c);applyStatus(t,e.status(),turns,intensity);tr.record("effect","variant=APPLY_STATUS effect="+e.effectId().value()+" status="+e.status()+" turns="+turns+" intensity="+intensity);return EffectResult.applied(intensity);}}

	abstract static class Distance<E extends CompiledSkill.DistanceEffect> implements EffectExecutor<E>{public EffectPreflightResult preflight(E e,Char t,RuntimeExecutionContext c){EffectPreflightResult live=target(t,"movement");if(!live.readyForExecute())return live;if(e.distance()<1||Char.hasProp(t,Char.Property.IMMOVABLE))return EffectPreflightResult.failed(EffectPreflightResult.Status.UNSUPPORTED_PARAMETERS,"movement.parameters");if(c.classOwner()==null||Dungeon.level==null||prospectiveMoveCount(t,c.classOwner().pos,e.distance(),e.variant()==CompiledSkill.EffectVariant.PULL)<1)return EffectPreflightResult.failed(EffectPreflightResult.Status.TARGET_UNAVAILABLE,"movement.no_legal_destination");return EffectPreflightResult.ready();}public EffectResult execute(E e,Char t,RuntimeExecutionContext c,RuntimeTrace tr){EffectPreflightResult p=preflight(e,t,c);if(!p.readyForExecute())return EffectExecutorRegistry.failed(p);Char source=c.classOwner();boolean pull=e.variant()==CompiledSkill.EffectVariant.PULL;int from=t.pos,moved=moveRelative(t,source.pos,e.distance(),pull);tr.record("effect","variant="+e.variant()+" effect="+e.effectId().value()+" from="+from+" to="+t.pos+" distance="+moved);return moved>0?EffectResult.applied(moved):EffectResult.failed(EffectResult.Status.TARGET_UNAVAILABLE,"movement.no_legal_destination");}}
	static final class Push extends Distance<CompiledSkill.PushEffect>{public CompiledSkill.EffectVariant variant(){return CompiledSkill.EffectVariant.PUSH;}public Class<CompiledSkill.PushEffect> effectType(){return CompiledSkill.PushEffect.class;}}
	static final class Pull extends Distance<CompiledSkill.PullEffect>{public CompiledSkill.EffectVariant variant(){return CompiledSkill.EffectVariant.PULL;}public Class<CompiledSkill.PullEffect> effectType(){return CompiledSkill.PullEffect.class;}}
	static final class ThrowValue extends Distance<CompiledSkill.ThrowEffect>{public CompiledSkill.EffectVariant variant(){return CompiledSkill.EffectVariant.THROW;}public Class<CompiledSkill.ThrowEffect> effectType(){return CompiledSkill.ThrowEffect.class;}}
	static final class Dash implements EffectExecutor<CompiledSkill.DashEffect>{public CompiledSkill.EffectVariant variant(){return CompiledSkill.EffectVariant.DASH;}public Class<CompiledSkill.DashEffect> effectType(){return CompiledSkill.DashEffect.class;}public EffectPreflightResult preflight(CompiledSkill.DashEffect e,Char t,RuntimeExecutionContext c){if(c.classOwner()==null||Dungeon.level==null||e.maximumDistance()<1)return EffectPreflightResult.failed(EffectPreflightResult.Status.TARGET_UNAVAILABLE,"dash.unavailable");int from=c.classOwner().pos,to=c.event().selectedCell();if(!validDestination(to)||Dungeon.level.distance(from,to)>e.maximumDistance())return EffectPreflightResult.failed(EffectPreflightResult.Status.TARGET_UNAVAILABLE,"dash.destination_invalid");return EffectPreflightResult.ready();}public EffectResult execute(CompiledSkill.DashEffect e,Char t,RuntimeExecutionContext c,RuntimeTrace tr){EffectPreflightResult p=preflight(e,t,c);if(!p.readyForExecute())return EffectExecutorRegistry.failed(p);Char owner=c.classOwner();int from=owner.pos,to=c.event().selectedCell();owner.move(to,false);Dungeon.level.occupyCell(owner);tr.record("effect","variant=DASH effect="+e.effectId().value()+" from="+from+" to="+to);return EffectResult.applied(Dungeon.level.distance(from,to));}}
	static final class Teleport implements EffectExecutor<CompiledSkill.TeleportEffect>{public CompiledSkill.EffectVariant variant(){return CompiledSkill.EffectVariant.TELEPORT;}public Class<CompiledSkill.TeleportEffect> effectType(){return CompiledSkill.TeleportEffect.class;}public EffectPreflightResult preflight(CompiledSkill.TeleportEffect e,Char t,RuntimeExecutionContext c){if(c.classOwner()==null||Dungeon.level==null||e.maximumRange()<1)return EffectPreflightResult.failed(EffectPreflightResult.Status.TARGET_UNAVAILABLE,"teleport.unavailable");int from=c.classOwner().pos,to=c.event().selectedCell();if(!validDestination(to)||Dungeon.level.distance(from,to)>e.maximumRange())return EffectPreflightResult.failed(EffectPreflightResult.Status.TARGET_UNAVAILABLE,"teleport.destination_invalid");return EffectPreflightResult.ready();}public EffectResult execute(CompiledSkill.TeleportEffect e,Char t,RuntimeExecutionContext c,RuntimeTrace tr){EffectPreflightResult p=preflight(e,t,c);if(!p.readyForExecute())return EffectExecutorRegistry.failed(p);Char owner=c.classOwner();int from=owner.pos,to=c.event().selectedCell();ScrollOfTeleportation.appear(owner,to);Dungeon.level.occupyCell(owner);tr.record("effect","variant=TELEPORT effect="+e.effectId().value()+" from="+from+" to="+to);return EffectResult.applied(1);}}
	static final class Swap implements EffectExecutor<CompiledSkill.SwapPositionEffect>{public CompiledSkill.EffectVariant variant(){return CompiledSkill.EffectVariant.SWAP_POSITION;}public Class<CompiledSkill.SwapPositionEffect> effectType(){return CompiledSkill.SwapPositionEffect.class;}public EffectPreflightResult preflight(CompiledSkill.SwapPositionEffect e,Char t,RuntimeExecutionContext c){Char owner=c.classOwner();if(owner==null||t==null||t==owner||Dungeon.level==null||!passable(owner.pos)||!passable(t.pos))return EffectPreflightResult.failed(EffectPreflightResult.Status.TARGET_UNAVAILABLE,"swap.unavailable");return target(t,"swap");}public EffectResult execute(CompiledSkill.SwapPositionEffect e,Char t,RuntimeExecutionContext c,RuntimeTrace tr){EffectPreflightResult p=preflight(e,t,c);if(!p.readyForExecute())return EffectExecutorRegistry.failed(p);Char owner=c.classOwner();int a=owner.pos,b=t.pos;owner.pos=b;t.pos=a;Dungeon.level.occupyCell(owner);Dungeon.level.occupyCell(t);tr.record("effect","variant=SWAP_POSITION effect="+e.effectId().value()+" first="+a+"->"+b+" second="+b+"->"+a);return EffectResult.applied(1);}}

	static final class Heal implements EffectExecutor<CompiledSkill.HealEffect>{public CompiledSkill.EffectVariant variant(){return CompiledSkill.EffectVariant.HEAL;}public Class<CompiledSkill.HealEffect> effectType(){return CompiledSkill.HealEffect.class;}public EffectPreflightResult preflight(CompiledSkill.HealEffect e,Char t,RuntimeExecutionContext c){if(positive(e.value(),c)<1)return EffectPreflightResult.failed(EffectPreflightResult.Status.UNSUPPORTED_PARAMETERS,"heal.amount");return target(t,"heal");}public EffectResult execute(CompiledSkill.HealEffect e,Char t,RuntimeExecutionContext c,RuntimeTrace tr){EffectPreflightResult p=preflight(e,t,c);if(!p.readyForExecute())return EffectExecutorRegistry.failed(p);int before=t.HP;t.HP=Math.min(t.HT,t.HP+positive(e.value(),c));int amount=t.HP-before;tr.record("effect","variant=HEAL effect="+e.effectId().value()+" hp_before="+before+" hp_after="+t.HP+" applied="+amount);return EffectResult.applied(amount);}}
	static final class BarrierValue implements EffectExecutor<CompiledSkill.BarrierEffect>{public CompiledSkill.EffectVariant variant(){return CompiledSkill.EffectVariant.BARRIER;}public Class<CompiledSkill.BarrierEffect> effectType(){return CompiledSkill.BarrierEffect.class;}public EffectPreflightResult preflight(CompiledSkill.BarrierEffect e,Char t,RuntimeExecutionContext c){if(positive(e.value(),c)<1)return EffectPreflightResult.failed(EffectPreflightResult.Status.UNSUPPORTED_PARAMETERS,"barrier.amount");return target(t,"barrier");}public EffectResult execute(CompiledSkill.BarrierEffect e,Char t,RuntimeExecutionContext c,RuntimeTrace tr){EffectPreflightResult p=preflight(e,t,c);if(!p.readyForExecute())return EffectExecutorRegistry.failed(p);Barrier b=Buff.affect(t,Barrier.class);int before=b.shielding(),amount=positive(e.value(),c);if(e.overflowPolicy()==CompiledSkill.BarrierOverflowPolicy.CLAMP_TO_MAX_HP)amount=Math.min(amount,Math.max(0,t.HT-before));b.incShield(amount);tr.record("effect","variant=BARRIER effect="+e.effectId().value()+" applied="+amount);return EffectResult.applied(amount);}}
	static final class TemporaryHp implements EffectExecutor<CompiledSkill.TemporaryHpEffect>{public CompiledSkill.EffectVariant variant(){return CompiledSkill.EffectVariant.TEMPORARY_HP;}public Class<CompiledSkill.TemporaryHpEffect> effectType(){return CompiledSkill.TemporaryHpEffect.class;}public EffectPreflightResult preflight(CompiledSkill.TemporaryHpEffect e,Char t,RuntimeExecutionContext c){if(positive(e.value(),c)<1||e.duration().kind()!=CompiledSkill.DurationKind.TURN_BASED||c.duration(e.duration())<1)return EffectPreflightResult.failed(EffectPreflightResult.Status.UNSUPPORTED_PARAMETERS,"temporary_hp.parameters");return target(t,"temporary_hp");}public EffectResult execute(CompiledSkill.TemporaryHpEffect e,Char t,RuntimeExecutionContext c,RuntimeTrace tr){EffectPreflightResult p=preflight(e,t,c);if(!p.readyForExecute())return EffectExecutorRegistry.failed(p);int amount=positive(e.value(),c),turns=c.duration(e.duration());RuleTemporaryHP b=Buff.affect(t,RuleTemporaryHP.class);b.grant(amount,turns,e.stacking().ordinal());tr.record("effect","variant=TEMPORARY_HP effect="+e.effectId().value()+" applied="+amount+" turns="+turns);return EffectResult.applied(amount);}}
	static final class Mitigate implements EffectExecutor<CompiledSkill.MitigateEffect>{public CompiledSkill.EffectVariant variant(){return CompiledSkill.EffectVariant.MITIGATE;}public Class<CompiledSkill.MitigateEffect> effectType(){return CompiledSkill.MitigateEffect.class;}public EffectPreflightResult preflight(CompiledSkill.MitigateEffect e,Char t,RuntimeExecutionContext c){if(e.percent()<1||e.percent()>75||e.duration().kind()!=CompiledSkill.DurationKind.TURN_BASED||c.duration(e.duration())<1)return EffectPreflightResult.failed(EffectPreflightResult.Status.UNSUPPORTED_PARAMETERS,"mitigate.parameters");return target(t,"mitigate");}public EffectResult execute(CompiledSkill.MitigateEffect e,Char t,RuntimeExecutionContext c,RuntimeTrace tr){EffectPreflightResult p=preflight(e,t,c);if(!p.readyForExecute())return EffectExecutorRegistry.failed(p);Buff.affect(t,RuleMitigation.class).set(e.percent(),c.duration(e.duration()));tr.record("effect","variant=MITIGATE effect="+e.effectId().value()+" percent="+e.percent());return EffectResult.applied(e.percent());}}
	static final class Redirect implements EffectExecutor<CompiledSkill.RedirectDamageEffect>{public CompiledSkill.EffectVariant variant(){return CompiledSkill.EffectVariant.REDIRECT_DAMAGE;}public Class<CompiledSkill.RedirectDamageEffect> effectType(){return CompiledSkill.RedirectDamageEffect.class;}public EffectPreflightResult preflight(CompiledSkill.RedirectDamageEffect e,Char t,RuntimeExecutionContext c){Char recipient=c.subject(e.recipient());if(recipient==null||recipient==t||e.percent()<1||e.percent()>75||e.duration().kind()!=CompiledSkill.DurationKind.TURN_BASED||c.duration(e.duration())<1)return EffectPreflightResult.failed(EffectPreflightResult.Status.UNSUPPORTED_PARAMETERS,"redirect.parameters");return target(t,"redirect");}public EffectResult execute(CompiledSkill.RedirectDamageEffect e,Char t,RuntimeExecutionContext c,RuntimeTrace tr){EffectPreflightResult p=preflight(e,t,c);if(!p.readyForExecute())return EffectExecutorRegistry.failed(p);int turns=c.duration(e.duration());Buff.affect(t,RuleDamageRedirect.class).set(c.subject(e.recipient()),e.percent(),turns);tr.record("effect","variant=REDIRECT_DAMAGE effect="+e.effectId().value()+" percent="+e.percent()+" turns="+turns+" recipient="+c.subject(e.recipient()).id());return EffectResult.applied(e.percent());}}
	static final class Cleanse implements EffectExecutor<CompiledSkill.CleanseEffect>{public CompiledSkill.EffectVariant variant(){return CompiledSkill.EffectVariant.CLEANSE;}public Class<CompiledSkill.CleanseEffect> effectType(){return CompiledSkill.CleanseEffect.class;}public EffectPreflightResult preflight(CompiledSkill.CleanseEffect e,Char t,RuntimeExecutionContext c){if(e.maximumCount()<1)return EffectPreflightResult.failed(EffectPreflightResult.Status.UNSUPPORTED_PARAMETERS,"cleanse.count");return target(t,"cleanse");}public EffectResult execute(CompiledSkill.CleanseEffect e,Char t,RuntimeExecutionContext c,RuntimeTrace tr){EffectPreflightResult p=preflight(e,t,c);if(!p.readyForExecute())return EffectExecutorRegistry.failed(p);int removed=0;for(Buff b:new ArrayList<>(t.buffs())){if(removed>=e.maximumCount())break;if(matches(b,e.filter())){b.detach();removed++;}}tr.record("effect","variant=CLEANSE effect="+e.effectId().value()+" removed="+removed);return EffectResult.applied(removed);}}
	static final class ResourceOperationValue implements EffectExecutor<CompiledSkill.ResourceOperationEffect>{public CompiledSkill.EffectVariant variant(){return CompiledSkill.EffectVariant.RESOURCE_OPERATION;}public Class<CompiledSkill.ResourceOperationEffect> effectType(){return CompiledSkill.ResourceOperationEffect.class;}private ResourceTransaction tx(CompiledSkill.ResourceOperationEffect e,RuntimeExecutionContext c){String id="tx-"+c.event().eventId()+"-"+e.operation().operationId().value();return new ResourceTransaction(c.plan(),c.state(),e.operation(),c::resolve,id);}public EffectPreflightResult preflight(CompiledSkill.ResourceOperationEffect e,Char t,RuntimeExecutionContext c){ResourceTransaction.Result r=tx(e,c).preflight();return r.status()==ResourceTransaction.Status.READY?EffectPreflightResult.ready():EffectPreflightResult.failed(EffectPreflightResult.Status.UNSUPPORTED_PARAMETERS,r.diagnostic());}public EffectResult execute(CompiledSkill.ResourceOperationEffect e,Char t,RuntimeExecutionContext c,RuntimeTrace tr){ResourceTransaction.Result r=tx(e,c).commit();tr.record("resource_transaction","transaction_id="+r.transactionId()+" operation="+e.operation().operationId().value()+" "+ResourceTransaction.traceDetails(e.operation(),c::resolve)+" status="+r.status()+" diagnostic="+r.diagnostic());if(r.status()!=ResourceTransaction.Status.COMMITTED)return EffectResult.failed(EffectResult.Status.UNSUPPORTED_PARAMETERS,r.diagnostic());c.publishState(r.state());return EffectResult.applied(resourceMagnitude(e.operation(),c));}}

	private static int resourceMagnitude(CompiledSkill.ResourceOperation operation,RuntimeExecutionContext context){return operation.variant()==CompiledSkill.ResourceOperationVariant.CONVERT?operation.secondAmount():operation.value()==null?operation.firstAmount():Math.abs(context.resolve(operation.value()));}
	private static boolean protectedTarget(Char target){return target!=null&&(Char.hasProp(target,Char.Property.BOSS)||Char.hasProp(target,Char.Property.MINIBOSS));}
	private static boolean validDestination(int cell){return Dungeon.level!=null&&cell>=0&&cell<Dungeon.level.length()&&Dungeon.level.passable[cell]&&!Dungeon.level.solid[cell]&&Actor.findChar(cell)==null;}
	private static boolean passable(int cell){return Dungeon.level!=null&&cell>=0&&cell<Dungeon.level.length()&&Dungeon.level.passable[cell]&&!Dungeon.level.solid[cell];}
	private static int prospectiveMoveCount(Char target,int origin,int distance,boolean toward){int width=Dungeon.level.width();int tx=target.pos%width,ty=target.pos/width,ox=origin%width,oy=origin/width;int dx=Integer.signum(toward?ox-tx:tx-ox),dy=Integer.signum(toward?oy-ty:ty-oy),cell=target.pos,moved=0;for(int i=0;i<distance;i++){int next=cell+dx+dy*width;if(!validDestination(next))break;cell=next;moved++;}return moved;}
	private static int moveRelative(Char target,int origin,int distance,boolean toward){int width=Dungeon.level.width();int tx=target.pos%width,ty=target.pos/width,ox=origin%width,oy=origin/width;int dx=Integer.signum(toward?ox-tx:tx-ox),dy=Integer.signum(toward?oy-ty:ty-oy);int moved=0;for(int i=0;i<distance;i++){int next=target.pos+dx+dy*width;if(!validDestination(next))break;target.move(next,false);Dungeon.level.occupyCell(target);moved++;}return moved;}
	private static void applyStatus(Char target,CompiledSkill.Status status,int turns,int intensity){switch(status){case POISON:Buff.affect(target,Poison.class).set(Math.max(turns,intensity));break;case BURNING:Buff.affect(target,Burning.class).reignite(target,turns);break;case BLEEDING:Buff.affect(target,Bleeding.class).set(Math.max(turns,intensity));break;case SLOW:Buff.prolong(target,Slow.class,turns);break;case HASTE:Buff.prolong(target,Haste.class,turns);break;case PARALYSIS:Buff.prolong(target,Paralysis.class,turns);break;case ROOTS:Buff.prolong(target,Roots.class,turns);break;case AMOK:Buff.prolong(target,Amok.class,turns);break;case TERROR:Buff.prolong(target,Terror.class,turns);break;case VULNERABLE:Buff.prolong(target,Vulnerable.class,turns);break;default:throw new IllegalArgumentException("status not whitelisted");}}
	private static boolean matches(Buff buff,CompiledSkill.StatusFilter filter){if(filter.kind()==CompiledSkill.StatusFilterKind.ANY_NEGATIVE)return buff.type==Buff.buffType.NEGATIVE;switch(filter.status()){case POISON:return buff instanceof Poison;case BURNING:return buff instanceof Burning;case BLEEDING:return buff instanceof Bleeding;case SLOW:return buff instanceof Slow;case HASTE:return buff instanceof Haste;case PARALYSIS:return buff instanceof Paralysis;case ROOTS:return buff instanceof Roots;case AMOK:return buff instanceof Amok;case TERROR:return buff instanceof Terror;case VULNERABLE:return buff instanceof Vulnerable;default:return false;}}
}
