package com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.runtime;

import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.ref.ResourceRef;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.spec.ClassBuildSpec;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.spec.ResourceSpec;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.spec.resource.*;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.state.ClassRuntimeState;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.state.ResourceState;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.compile.ClassCompilePlan;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.compile.CompiledResource;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.compile.CompiledSkill;
import java.util.ArrayList;import java.util.LinkedHashMap;import java.util.List;import java.util.Map;

/** Plans all resource mutations first and publishes one immutable state only on success. */
public final class ResourceTransaction {
	public interface ValueResolver { int resolve(com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.spec.skill.ValueSpec value); }
	public interface CompiledValueResolver { int resolve(CompiledSkill.Value value); }
	public enum Status { READY, COMMITTED, BLOCKED }
	public static final class Result {private final Status status;private final ClassRuntimeState state;private final String diagnostic,transactionId;private Result(Status status,ClassRuntimeState state,String diagnostic,String id){this.status=status;this.state=state;this.diagnostic=diagnostic;transactionId=id;}public Status status(){return status;}public ClassRuntimeState state(){return state;}public String diagnostic(){return diagnostic;}public String transactionId(){return transactionId;}}
	private final ClassBuildSpec build;private final ClassRuntimeState before;private final ResourceOperationSpec operation;private final ValueResolver values;private final String transactionId;
	private final ClassCompilePlan compiledPlan; private final CompiledSkill.ResourceOperation compiledOperation; private final CompiledValueResolver compiledValues;
	public ResourceTransaction(ClassBuildSpec build,ClassRuntimeState before,ResourceOperationSpec operation,ValueResolver values,String transactionId){if(build==null||before==null||operation==null||values==null||transactionId==null||transactionId.isEmpty())throw new IllegalArgumentException("resource transaction fields required");this.build=build;this.before=before;this.operation=operation;this.values=values;this.transactionId=transactionId;compiledPlan=null;compiledOperation=null;compiledValues=null;}
	public ResourceTransaction(ClassCompilePlan plan,ClassRuntimeState before,CompiledSkill.ResourceOperation operation,CompiledValueResolver values,String transactionId){if(plan==null||before==null||operation==null||values==null||transactionId==null||transactionId.isEmpty())throw new IllegalArgumentException("compiled resource transaction fields required");this.compiledPlan=plan;this.before=before;this.compiledOperation=operation;this.compiledValues=values;this.transactionId=transactionId;build=null;this.operation=null;this.values=null;}
	public Result preflight(){return compute(false);}
	public Result commit(){return compute(true);}
	private Result compute(boolean commit){if(compiledPlan!=null)return computeCompiled(commit);Map<ResourceRef,ResourceState> next=new LinkedHashMap<>(before.resources());String incompatible=ResourceRuntimeStateFactory.incompatibility(build,before);if(!incompatible.isEmpty())return blocked(incompatible);try{switch(operation.variant()){
		case GAIN:gain(next,(GainResourceSpec)operation);break;case DRAIN:drain(next,(DrainResourceSpec)operation);break;case SET:set(next,(SetResourceSpec)operation);break;case CLEAR:clear(next,(ClearResourceSpec)operation);break;case CONVERT:convert(next,(ConvertResourceSpec)operation);break;case RESERVE:reserve(next,(ReserveResourceSpec)operation);break;case SUPPRESS:suppress(next,(SuppressResourceSpec)operation);break;default:return blocked("resource.operation_unsupported");}
	}catch(Blocked failure){return blocked(failure.getMessage());}
	ClassRuntimeState state=commit?before.toBuilder().resources(next).nextPayloadInstanceId(before.nextPayloadInstanceId()+1).build():before;return new Result(commit?Status.COMMITTED:Status.READY,state,commit?"resource.transaction_committed":"resource.transaction_ready",transactionId);}
	private Result computeCompiled(boolean commit){Map<ResourceRef,ResourceState> next=new LinkedHashMap<>(before.resources());String incompatible=ResourceRuntimeStateFactory.incompatibility(compiledPlan,before);if(!incompatible.isEmpty())return blocked(incompatible);try{switch(compiledOperation.variant()){
		case GAIN:compiledGain(next);break;case DRAIN:compiledDrain(next);break;case SET:compiledSet(next);break;case CLEAR:compiledClear(next);break;case CONVERT:compiledConvert(next);break;case RESERVE:compiledReserve(next);break;case SUPPRESS:compiledSuppress(next);break;default:return blocked("resource.operation_unsupported");
	}}catch(Blocked failure){return blocked(failure.getMessage());}ClassRuntimeState state=commit?before.toBuilder().resources(next).nextPayloadInstanceId(before.nextPayloadInstanceId()+1).build():before;return new Result(commit?Status.COMMITTED:Status.READY,state,commit?"resource.transaction_committed":"resource.transaction_ready",transactionId);}
	private void compiledGain(Map<ResourceRef,ResourceState> next){CompiledResource spec=compiledDeclaration(compiledOperation.firstResource());ResourceState old=compiledState(next,compiledOperation.firstResource());ensureGainAllowed(old);int amount=positive(compiledValues.resolve(compiledOperation.value()),"resource.amount_not_positive");long raw=(long)old.current()+amount;int value;if(raw<=spec.maximum())value=(int)raw;else if(compiledOperation.overflow()==CompiledSkill.ResourceOverflowPolicy.FAIL)throw new Blocked("resource.target_space_insufficient");else value=spec.maximum();replace(next,old,value,old.reservations(),old.suppressions());}
	private void compiledDrain(Map<ResourceRef,ResourceState> next){CompiledResource spec=compiledDeclaration(compiledOperation.firstResource());ResourceState old=compiledState(next,compiledOperation.firstResource());int amount=positive(compiledValues.resolve(compiledOperation.value()),"resource.amount_not_positive");int available=old.current()-spec.minimum();if(available<amount&&compiledOperation.insufficient()==CompiledSkill.InsufficientResourcePolicy.FAIL)throw new Blocked("resource.source_insufficient");replace(next,old,old.current()-Math.min(available,amount),old.reservations(),old.suppressions());}
	private void compiledSet(Map<ResourceRef,ResourceState> next){CompiledResource spec=compiledDeclaration(compiledOperation.firstResource());ResourceState old=compiledState(next,compiledOperation.firstResource());int value=compiledValues.resolve(compiledOperation.value());if(value<spec.minimum()||value>spec.maximum())throw new Blocked("resource.set_out_of_bounds");replace(next,old,value,old.reservations(),old.suppressions());}
	private void compiledClear(Map<ResourceRef,ResourceState> next){CompiledResource spec=compiledDeclaration(compiledOperation.firstResource());ResourceState old=compiledState(next,compiledOperation.firstResource());replace(next,old,spec.minimum(),old.reservations(),old.suppressions());}
	private void compiledConvert(Map<ResourceRef,ResourceState> next){if(compiledOperation.conversion()!=CompiledSkill.ConversionPolicy.EXACT_ATOMIC||compiledOperation.overflow()!=CompiledSkill.ResourceOverflowPolicy.FAIL)throw new Blocked("resource.convert_policy_unsupported");CompiledResource sourceSpec=compiledDeclaration(compiledOperation.firstResource()),targetSpec=compiledDeclaration(compiledOperation.secondResource());ResourceState source=compiledState(next,compiledOperation.firstResource()),target=compiledState(next,compiledOperation.secondResource());if(source.current()-compiledOperation.firstAmount()<sourceSpec.minimum())throw new Blocked("resource.source_insufficient");if((long)target.current()+compiledOperation.secondAmount()>targetSpec.maximum())throw new Blocked("resource.target_space_insufficient");ensureGainAllowed(target);replace(next,source,source.current()-compiledOperation.firstAmount(),source.reservations(),source.suppressions());replace(next,target,target.current()+compiledOperation.secondAmount(),target.reservations(),target.suppressions());}
	private void compiledReserve(Map<ResourceRef,ResourceState> next){CompiledResource spec=compiledDeclaration(compiledOperation.firstResource());ResourceState old=compiledState(next,compiledOperation.firstResource());int amount=compiledOperation.firstAmount();if(old.current()-amount<spec.minimum())throw new Blocked("resource.source_insufficient");List<ResourceState.Reservation> reservations=new ArrayList<>(old.reservations());reservations.add(new ResourceState.Reservation(before.nextPayloadInstanceId(),amount,compiledOperation.durationTurns()));replace(next,old,old.current()-amount,reservations,old.suppressions());}
	private void compiledSuppress(Map<ResourceRef,ResourceState> next){ResourceState old=compiledState(next,compiledOperation.firstResource());compiledDeclaration(compiledOperation.firstResource());List<ResourceState.Suppression> suppressions=new ArrayList<>(old.suppressions());suppressions.add(new ResourceState.Suppression(before.nextPayloadInstanceId(),compiledOperation.durationTurns(),compiledOperation.suppression().name()));replace(next,old,old.current(),old.reservations(),suppressions);}
	private CompiledResource compiledDeclaration(com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.identity.StableId id){CompiledResource result=compiledPlan.findResource(id);if(result==null)throw new Blocked("resource.reference_unresolved:"+id.value());return result;}
	private static ResourceState compiledState(Map<ResourceRef,ResourceState> values,com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.identity.StableId id){ResourceState state=values.get(new ResourceRef(id,""));if(state==null)throw new Blocked("resource.state_missing:"+id.value());return state;}
	private static void ensureGainAllowed(ResourceState old){for(ResourceState.Suppression suppression:old.suppressions())if(suppression.remainingTurns()>0&&"BLOCK_GAIN".equals(suppression.modeKey()))throw new Blocked("resource.gain_suppressed");}
	private void gain(Map<ResourceRef,ResourceState> next,GainResourceSpec op){ResourceSpec spec=declaration(op.resource());ResourceState old=state(next,op.resource());for(ResourceState.Suppression suppression:old.suppressions())if(suppression.remainingTurns()>0&&"BLOCK_GAIN".equals(suppression.modeKey()))throw new Blocked("resource.gain_suppressed");int amount=positive(values.resolve(op.amount()),"resource.amount_not_positive");long raw=(long)old.current()+amount;int value;if(raw<=spec.maximum())value=(int)raw;else if(op.overflowPolicy()==ResourceSpec.ResourceOverflowPolicy.FAIL)throw new Blocked("resource.target_space_insufficient");else value=spec.maximum();replace(next,old,value,old.reservations(),old.suppressions());}
	private void drain(Map<ResourceRef,ResourceState> next,DrainResourceSpec op){ResourceSpec spec=declaration(op.resource());ResourceState old=state(next,op.resource());int amount=positive(values.resolve(op.amount()),"resource.amount_not_positive");int available=old.current()-spec.minimum();if(available<amount&&op.insufficientPolicy()==DrainResourceSpec.InsufficientResourcePolicy.FAIL)throw new Blocked("resource.source_insufficient");replace(next,old,old.current()-Math.min(available,amount),old.reservations(),old.suppressions());}
	private void set(Map<ResourceRef,ResourceState> next,SetResourceSpec op){ResourceSpec spec=declaration(op.resource());ResourceState old=state(next,op.resource());int value=values.resolve(op.value());if(value<spec.minimum()||value>spec.maximum())throw new Blocked("resource.set_out_of_bounds");replace(next,old,value,old.reservations(),old.suppressions());}
	private void clear(Map<ResourceRef,ResourceState> next,ClearResourceSpec op){ResourceSpec spec=declaration(op.resource());ResourceState old=state(next,op.resource());replace(next,old,spec.minimum(),old.reservations(),old.suppressions());}
	private void convert(Map<ResourceRef,ResourceState> next,ConvertResourceSpec op){if(op.conversionPolicy()!=ConvertResourceSpec.ConversionPolicy.EXACT_ATOMIC||op.targetOverflowPolicy()!=ResourceSpec.ResourceOverflowPolicy.FAIL)throw new Blocked("resource.convert_policy_unsupported");ResourceSpec sourceSpec=declaration(op.source()),targetSpec=declaration(op.target());ResourceState source=state(next,op.source()),target=state(next,op.target());if(source.current()-op.sourceAmount()<sourceSpec.minimum())throw new Blocked("resource.source_insufficient");if((long)target.current()+op.targetAmount()>targetSpec.maximum())throw new Blocked("resource.target_space_insufficient");for(ResourceState.Suppression suppression:target.suppressions())if(suppression.remainingTurns()>0&&"BLOCK_GAIN".equals(suppression.modeKey()))throw new Blocked("resource.gain_suppressed");replace(next,source,source.current()-op.sourceAmount(),source.reservations(),source.suppressions());replace(next,target,target.current()+op.targetAmount(),target.reservations(),target.suppressions());}
	private void reserve(Map<ResourceRef,ResourceState> next,ReserveResourceSpec op){ResourceSpec spec=declaration(op.resource());ResourceState old=state(next,op.resource());if(old.current()-op.amount()<spec.minimum())throw new Blocked("resource.source_insufficient");List<ResourceState.Reservation> reservations=new ArrayList<>(old.reservations());reservations.add(new ResourceState.Reservation(before.nextPayloadInstanceId(),op.amount(),op.durationTurns()));replace(next,old,old.current()-op.amount(),reservations,old.suppressions());}
	private void suppress(Map<ResourceRef,ResourceState> next,SuppressResourceSpec op){ResourceState old=state(next,op.resource());declaration(op.resource());List<ResourceState.Suppression> suppressions=new ArrayList<>(old.suppressions());suppressions.add(new ResourceState.Suppression(before.nextPayloadInstanceId(),op.durationTurns(),op.mode().name()));replace(next,old,old.current(),old.reservations(),suppressions);}
	private ResourceSpec declaration(ResourceRef ref){for(ResourceSpec spec:build.resources())if(spec.id().equals(ref.targetId()))return spec;throw new Blocked("resource.reference_unresolved:"+ref.targetId().value());}
	private static ResourceState state(Map<ResourceRef,ResourceState> values,ResourceRef ref){ResourceState state=values.get(ref);if(state==null)throw new Blocked("resource.state_missing:"+ref.targetId().value());return state;}
	private static void replace(Map<ResourceRef,ResourceState> values,ResourceState old,int current,List<ResourceState.Reservation> reservations,List<ResourceState.Suppression> suppressions){values.put(old.resource(),new ResourceState(old.resource(),current,reservations,suppressions));}
	private static int positive(int value,String diagnostic){if(value<1)throw new Blocked(diagnostic);return value;}
	/** Stable trace projection shared by Skill Effects, Resource Flows and Class Operations. */
	public static String traceDetails(CompiledSkill.ResourceOperation operation,CompiledValueResolver values){if(operation.variant()==CompiledSkill.ResourceOperationVariant.CONVERT)return "variant=CONVERT source_id="+operation.firstResource().value()+" source_delta=-"+operation.firstAmount()+" target_id="+operation.secondResource().value()+" target_delta=+"+operation.secondAmount();String id=operation.firstResource()==null?"":operation.firstResource().value();String amount=operation.value()==null?Integer.toString(operation.firstAmount()):Integer.toString(values.resolve(operation.value()));return "variant="+operation.variant()+" resource_id="+id+" amount="+amount+" duration_turns="+operation.durationTurns();}
	private Result blocked(String diagnostic){return new Result(Status.BLOCKED,before,diagnostic,transactionId);}
	private static final class Blocked extends RuntimeException{Blocked(String message){super(message);}}
}
