package com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.spec.resource;

import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.identity.StableId;import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.ref.ResourceRef;import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.spec.ResourceSpec.ResourceOverflowPolicy;import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.spec.skill.ResourceHolderSelector;import java.util.Arrays;import java.util.List;
public final class ConvertResourceSpec implements ResourceOperationSpec {
	public enum ConversionPolicy { EXACT_ATOMIC }
	private final StableId operationId;private final ResourceHolderSelector holder;private final ResourceRef source,target;private final int sourceAmount,targetAmount;private final ConversionPolicy conversionPolicy;private final ResourceOverflowPolicy targetOverflowPolicy;
	public ConvertResourceSpec(StableId operationId,ResourceHolderSelector holder,ResourceRef source,int sourceAmount,ResourceRef target,int targetAmount,ConversionPolicy conversionPolicy,ResourceOverflowPolicy targetOverflowPolicy){if(operationId==null||holder==null||source==null||target==null||conversionPolicy==null||targetOverflowPolicy==null)throw new IllegalArgumentException("convert resource fields required");if(source.equals(target)||sourceAmount<1||targetAmount<1)throw new IllegalArgumentException("convert requires distinct resources and positive amounts");if(conversionPolicy!=ConversionPolicy.EXACT_ATOMIC)throw new IllegalArgumentException("only EXACT_ATOMIC is supported");if(targetOverflowPolicy!=ResourceOverflowPolicy.FAIL)throw new IllegalArgumentException("P04 convert target policy must be FAIL");this.operationId=operationId;this.holder=holder;this.source=source;this.sourceAmount=sourceAmount;this.target=target;this.targetAmount=targetAmount;this.conversionPolicy=conversionPolicy;this.targetOverflowPolicy=targetOverflowPolicy;}
	@Override public StableId operationId(){return operationId;}@Override public Variant variant(){return Variant.CONVERT;}@Override public List<ResourceRef> referencedResources(){return Arrays.asList(source,target);}public ResourceHolderSelector holder(){return holder;}public ResourceRef source(){return source;}public int sourceAmount(){return sourceAmount;}public ResourceRef target(){return target;}public int targetAmount(){return targetAmount;}public ConversionPolicy conversionPolicy(){return conversionPolicy;}public ResourceOverflowPolicy targetOverflowPolicy(){return targetOverflowPolicy;}
}
