package com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.edit;

import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.identity.DisplayName;import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.identity.IdGenerator;import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.identity.StableId;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.ref.PropertyRef;import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.ref.TypedRef;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.spec.*;
import com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.spec.skill.SkillSpec;
import java.util.ArrayList;import java.util.List;

/** Pure edits return a new immutable graph. Delete is never cascading; rebind is always explicit. */
public final class BuildEditService {
	public ClassBuildSpec rename(ClassBuildSpec build,StableId id,DisplayName name){if(build.buildId().equals(id))return build.toBuilder().displayName(name).build();ClassBuildSpec.Builder out=build.toBuilder();replace(out,build,id,name,null,null);return out.build();}
	public ClassBuildSpec delete(ClassBuildSpec build,StableId id){ClassBuildSpec.Builder out=build.toBuilder();replace(out,build,id,null,null,Boolean.TRUE);return out.build();}
	public ClassBuildSpec duplicate(ClassBuildSpec build,StableId id,IdGenerator ids){StableTarget source=find(build,id);if(source==null)throw new IllegalArgumentException("declaration not found: "+id);if(source instanceof SkillSpec&&((SkillSpec)source).typed())throw new IllegalArgumentException("typed skill duplication requires a fresh CreateSkill command path");String prefix=prefix(source);StableId newId=null;for(int attempt=0;attempt<1024;attempt++){StableId candidate=ids.nextId(prefix);if(find(build,candidate)==null){newId=candidate;break;}}if(newId==null)throw new IllegalStateException("id generator did not produce a unique id");ClassBuildSpec.Builder out=build.toBuilder();add(out,copy(source,newId,source.displayName()));return out.build();}
	public ClassBuildSpec rebind(ClassBuildSpec build,StableId ownerId,String fieldPath,StableTarget target){ClassBuildSpec.Builder out=build.toBuilder();ReferenceEditService refs=new ReferenceEditService();boolean changed=false;
		List<ModeSpec> modes=new ArrayList<>();for(ModeSpec value:build.modes()){if(value.id().equals(ownerId)&&"group".equals(fieldPath)){modes.add(value.withGroup((com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.ref.ModeGroupRef)refs.rebind(value.group(),target)));changed=true;}else modes.add(value);}out.modes(modes);
		List<EntitySpec> entities=new ArrayList<>();for(EntitySpec value:build.entities()){if(value.id().equals(ownerId)&&"capacity".equals(fieldPath)&&value.capacity()!=null){entities.add(value.withCapacity((com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.ref.CapacityRef)refs.rebind(value.capacity(),target)));changed=true;}else if(value.id().equals(ownerId)&&fieldPath.matches("capabilities\\[[0-9]+]\\.slots\\[[0-9]+]\\.resource")){int capabilityIndex=Integer.parseInt(fieldPath.substring(13,fieldPath.indexOf(']')));int slotStart=fieldPath.indexOf("slots[")+6;int slotIndex=Integer.parseInt(fieldPath.substring(slotStart,fieldPath.indexOf(']',slotStart)));if(capabilityIndex<0||capabilityIndex>=value.capabilities().size()||!(value.capabilities().get(capabilityIndex) instanceof ResourceStorageCapability))throw new IllegalArgumentException("resource storage capability index out of bounds");List<EntityCapabilitySpec> capabilities=new ArrayList<>(value.capabilities());ResourceStorageCapability storage=(ResourceStorageCapability)capabilities.get(capabilityIndex);if(slotIndex<0||slotIndex>=storage.slots().size())throw new IllegalArgumentException("resource slot index out of bounds");List<EntityResourceSlotSpec> slots=new ArrayList<>(storage.slots());EntityResourceSlotSpec old=slots.get(slotIndex);slots.set(slotIndex,old.withResource((com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.ref.ResourceRef)refs.rebind(old.resource(),target)));capabilities.set(capabilityIndex,storage.withSlots(slots));entities.add(value.withCapabilities(capabilities));changed=true;}else entities.add(value);}out.entities(entities);
		List<SynthesisRecipeSpec> recipes=new ArrayList<>();for(SynthesisRecipeSpec value:build.recipes()){if(value.id().equals(ownerId)&&fieldPath.matches("inputs\\[[0-9]+]\\.property")){int index=Integer.parseInt(fieldPath.substring(7,fieldPath.indexOf(']')));if(index<0||index>=value.inputs().size())throw new IllegalArgumentException("recipe input index out of bounds");List<SynthesisRecipeSpec.PropertyInput> inputs=new ArrayList<>(value.inputs());PropertyRef old=inputs.get(index).property();inputs.set(index,new SynthesisRecipeSpec.PropertyInput((PropertyRef)refs.rebind(old,target),inputs.get(index).amount()));recipes.add(new SynthesisRecipeSpec(value.id(),value.displayName(),inputs,value.outputVariantKey(),value.implementationState()));changed=true;}else recipes.add(value);}out.recipes(recipes);
		if(!changed)throw new IllegalArgumentException("unknown rebind field "+ownerId+"."+fieldPath);return out.build();}
	private static StableTarget find(ClassBuildSpec build,StableId id){for(StableTarget value:build.allTargets())if(value.id().equals(id))return value;return null;}
	private static String prefix(StableTarget value){if(value instanceof SkillSpec)return"skill";if(value instanceof ContractNodeSpec){switch(((ContractNodeSpec)value).nodeKind()){case COMPONENT:return"component";case CONSTRAINT:return"constraint";case OPERATION:return"op";case SKILL:return"skill";default:throw new AssertionError();}}switch(value.refKind()){case RESOURCE:return"res";case MARK:return"mark";case MODE_GROUP:return"modegrp";case MODE:return"mode";case ENTITY:return"entity";case CAPACITY:return"capacity";case ABILITY_POOL:return"abilitypool";case PROPERTY:return"property";case RECIPE:return"recipe";case COMPONENT:return"component";default:throw new AssertionError();}}
	private static StableTarget copy(StableTarget v,StableId id,DisplayName name){if(v instanceof ResourceSpec)return((ResourceSpec)v).withIdentity(id).withDisplayName(name);if(v instanceof MarkSpec)return((MarkSpec)v).withIdentity(id).withDisplayName(name);if(v instanceof ModeGroupSpec)return((ModeGroupSpec)v).withIdentity(id).withDisplayName(name);if(v instanceof ModeSpec)return((ModeSpec)v).withIdentity(id).withDisplayName(name);if(v instanceof EntityCapacitySpec)return((EntityCapacitySpec)v).withIdentity(id).withDisplayName(name);if(v instanceof EntitySpec)return((EntitySpec)v).withIdentity(id).withDisplayName(name);if(v instanceof AbilityPoolSpec)return((AbilityPoolSpec)v).withIdentity(id).withDisplayName(name);if(v instanceof PropertySpec)return((PropertySpec)v).withIdentity(id).withDisplayName(name);if(v instanceof SynthesisRecipeSpec)return((SynthesisRecipeSpec)v).withIdentity(id).withDisplayName(name);if(v instanceof SkillSpec)return((SkillSpec)v).withIdentity(id).withDisplayName(name);if(v instanceof ContractNodeSpec)return((ContractNodeSpec)v).withIdentity(id).withDisplayName(name);throw new IllegalArgumentException("unsupported declaration");}
	private static void replace(ClassBuildSpec.Builder out,ClassBuildSpec b,StableId id,DisplayName name,StableId unused,Boolean delete){out.resources(map(b.resources(),id,name,delete));out.marks(map(b.marks(),id,name,delete));out.modeGroups(map(b.modeGroups(),id,name,delete));out.modes(map(b.modes(),id,name,delete));out.capacities(map(b.capacities(),id,name,delete));out.entities(map(b.entities(),id,name,delete));out.abilityPools(map(b.abilityPools(),id,name,delete));out.properties(map(b.properties(),id,name,delete));out.recipes(map(b.recipes(),id,name,delete));out.classComponents(map(b.classComponents(),id,name,delete));out.classConstraints(map(b.classConstraints(),id,name,delete));out.classOperations(map(b.classOperations(),id,name,delete));out.skills(map(b.skills(),id,name,delete));}
	@SuppressWarnings("unchecked")private static<T extends StableTarget>List<T> map(List<T> values,StableId id,DisplayName name,Boolean delete){List<T> out=new ArrayList<>();for(T value:values){if(!value.id().equals(id))out.add(value);else if(!Boolean.TRUE.equals(delete))out.add((T)copy(value,value.id(),name));}return out;}
	private static void add(ClassBuildSpec.Builder out,StableTarget v){if(v instanceof ResourceSpec)out.addResource((ResourceSpec)v);else if(v instanceof MarkSpec)out.addMark((MarkSpec)v);else if(v instanceof ModeGroupSpec)out.addModeGroup((ModeGroupSpec)v);else if(v instanceof ModeSpec)out.addMode((ModeSpec)v);else if(v instanceof EntityCapacitySpec)out.addCapacity((EntityCapacitySpec)v);else if(v instanceof EntitySpec)out.addEntity((EntitySpec)v);else if(v instanceof AbilityPoolSpec)out.addAbilityPool((AbilityPoolSpec)v);else if(v instanceof PropertySpec)out.addProperty((PropertySpec)v);else if(v instanceof SynthesisRecipeSpec)out.addRecipe((SynthesisRecipeSpec)v);else if(v instanceof SkillSpec)out.addSkill((SkillSpec)v);else if(v instanceof ContractNodeSpec){ContractNodeSpec n=(ContractNodeSpec)v;switch(n.nodeKind()){case COMPONENT:out.addClassComponent(n);break;case CONSTRAINT:out.addClassConstraint(n);break;case OPERATION:out.addClassOperation(n);break;case SKILL:out.addSkill(n);break;}}else throw new IllegalArgumentException("unsupported declaration");}
}
