package com.shatteredpixel.shatteredpixeldungeon.rules.contract.v6.spec.skill;

/** Contract effect keys. UNCONFIGURED exists only for editable drafts and is never executable. */
public enum EffectVariantKey {
	UNCONFIGURED,
	DIRECT_DAMAGE, PERCENT_MAX_HP_DAMAGE, MISSING_HP_DAMAGE, EXECUTE,
	APPLY_STATUS,
	PUSH, PULL, THROW, DASH, TELEPORT, SWAP_POSITION,
	HEAL, BARRIER, TEMPORARY_HP, MITIGATE, REDIRECT_DAMAGE, CLEANSE,
	RESOURCE_OPERATION,
	ADD_MARK, SET_MARK, CONSUME_MARK, REMOVE_MARK,
	CREATE_ENTITY,
	CREATE_TERRAIN, DESTROY_TERRAIN, CREATE_HAZARD, CLEAR_HAZARD,
	ASSIGN_OWNERSHIP, BREAK_OWNERSHIP, CREATE_LINK, BREAK_LINK, COMMAND_ENTITY, INHERIT_CAPABILITY,
	TRANSFER_RESOURCE, COPY_STATUS, TRANSFER_MARK, SWAP_BARRIER, CAPTURE_SNAPSHOT, RESTORE_SNAPSHOT,
	CAPTURE_ABILITY, GRANT_LEARNED_ABILITY, EXTRACT_PROPERTY, TRANSFER_PROPERTY,
	MODE_SHIFT, CAPABILITY_OVERRIDE, BEHAVIOR_OVERRIDE, DECOMPOSE, SYNTHESIZE, IMBUE
}
