package com.shatteredpixel.shatteredpixeldungeon.qa;

import com.shatteredpixel.shatteredpixeldungeon.rules.ClassBuild;
import com.shatteredpixel.shatteredpixeldungeon.rules.ClassLaw;
import com.shatteredpixel.shatteredpixeldungeon.rules.CoreRuleVocabulary;
import com.shatteredpixel.shatteredpixeldungeon.rules.ResourceSpec;
import com.shatteredpixel.shatteredpixeldungeon.rules.RuleCost;
import com.shatteredpixel.shatteredpixeldungeon.rules.SkillConstraint;
import com.shatteredpixel.shatteredpixeldungeon.rules.SkillSpec;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.LinkedHashMap;

/** Aggregates behavior, component use, constraint effectiveness, and conservative dominance hints. */
public final class ArchetypeStressAnalyzer {
	public static class Result {
		public ArchetypeStressReport.Summary summary=new ArchetypeStressReport.Summary();
		public final ArrayList<ArchetypeStressReport.RunResult> runs=new ArrayList<>();
		public final ArrayList<ArchetypeStressReport.ScenarioAggregate> scenarioAggregates=new ArrayList<>();
		public final ArrayList<ArchetypeStressReport.DominanceFinding> dominance=new ArrayList<>();
		public final ArrayList<ArchetypeStressReport.ComponentUsage> componentUsage=new ArrayList<>();
		public final ArrayList<ArchetypeStressReport.ConstraintResult> constraints=new ArrayList<>();
		public final ArrayList<ArchetypeStressReport.SpecialtyReport> specialties=new ArrayList<>();
		public final ArrayList<ArchetypeStressReport.ComponentValueAttribution> componentValues=new ArrayList<>();
		public final ArrayList<ArchetypeStressReport.MissingCapability> missingCapabilities=new ArrayList<>();
	}

	private ArchetypeStressAnalyzer() {}

	public static Result run(int seeds,long baseSeed){
		long started=System.nanoTime();Result result=new Result();int seedCount=Math.max(1,seeds);
		ArrayList<ArchetypeReferenceBuilds.Id> ids=ArchetypeReferenceBuilds.allIds();
		for(ArchetypeReferenceBuilds.Id id:ids)for(ArchetypeStressHarness.ScenarioId scenario:ArchetypeStressHarness.ScenarioId.values())for(int i=0;i<seedCount;i++){
			long seed=baseSeed+id.ordinal()*100000L+scenario.ordinal()*1000L+i;
			result.runs.add(new ArchetypeStressHarness().run(id,scenario,seed));
		}
		ArrayList<ArchetypeReferenceBuilds.Id> primaryIds=ArchetypeReferenceBuilds.primaryIds();
		result.summary.archetypes=ids.size();result.summary.primaryArchetypes=primaryIds.size();result.summary.scenarios=ArchetypeStressHarness.ScenarioId.values().length;result.summary.seedsPerScenario=seedCount;result.summary.totalRuns=result.runs.size();
		int min=Integer.MAX_VALUE,max=Integer.MIN_VALUE,primaryMin=Integer.MAX_VALUE,primaryMax=Integer.MIN_VALUE;
		for(ArchetypeReferenceBuilds.Id id:ids){ArchetypeStressReport.BuildSummary summary=summarize(id,result.runs);result.summary.builds.add(summary);min=Math.min(min,summary.usedBudget);max=Math.max(max,summary.usedBudget);if(primaryIds.contains(id)){primaryMin=Math.min(primaryMin,summary.usedBudget);primaryMax=Math.max(primaryMax,summary.usedBudget);}result.summary.victories+=summary.victories;result.summary.survivalFailures+=summary.survivalFailures;result.summary.runtimeFailures+=summary.runtimeFailures;result.componentUsage.add(componentUsage(id,result.runs));result.componentValues.add(componentValue(id,result.runs));result.constraints.addAll(constraints(id,result.runs));}
		result.summary.minimumBudget=min;result.summary.maximumBudget=max;result.summary.budgetSpreadPercent=min<=0?0:(max-min)*100.0/min;
		result.summary.primaryMinimumBudget=primaryMin;result.summary.primaryMaximumBudget=primaryMax;result.summary.primaryBudgetSpreadPercent=primaryMin<=0?0:(primaryMax-primaryMin)*100.0/primaryMin;
		result.scenarioAggregates.addAll(scenarioAggregates(ids,result.runs));
		for(ArchetypeReferenceBuilds.Id id:primaryIds)result.specialties.add(specialty(id,result.summary.builds));
		result.dominance.addAll(dominance(result.summary.builds));addMissingCapabilities(result);
		if(result.summary.runtimeFailures>0)result.summary.conclusion="B";
		else if(result.summary.primaryBudgetSpreadPercent>11||primaryWithoutVictory(result.summary.builds))result.summary.conclusion="B";
		else result.summary.conclusion=foundationReady(result)?"D":"C";
		result.summary.findings.add("All builds use the same ClassBuild/SkillSpec runtime and one shared semantic policy.");
		result.summary.findings.add("NON-BROKEN does not mean balanced; dominance entries are balance leads, not integrity failures.");
		result.summary.elapsedMillis=(System.nanoTime()-started)/1_000_000L;return result;
	}

	private static ArrayList<ArchetypeStressReport.ScenarioAggregate> scenarioAggregates(ArrayList<ArchetypeReferenceBuilds.Id> ids,ArrayList<ArchetypeStressReport.RunResult> runs){
		ArrayList<ArchetypeStressReport.ScenarioAggregate> result=new ArrayList<>();
		for(ArchetypeReferenceBuilds.Id id:ids)for(ArchetypeStressHarness.ScenarioId scenario:ArchetypeStressHarness.ScenarioId.values()){
			ArchetypeStressReport.ScenarioAggregate row=new ArchetypeStressReport.ScenarioAggregate();row.buildId=id.name();row.scenarioId=scenario.name();ArrayList<Integer> victoryTurns=new ArrayList<>();
			for(ArchetypeStressReport.RunResult run:runs)if(run.buildId.equals(row.buildId)&&run.scenarioId.equals(row.scenarioId)){row.seeds++;if(run.victory){row.victories++;victoryTurns.add(run.turnsToVictory);}if(!run.survived)row.survivalFailures++;if(run.runtimeFailure)row.runtimeFailures++;add(row.mean,run.metrics);}
			row.victoryRate=row.seeds==0?0:row.victories/(double)row.seeds;divide(row.mean,Math.max(1,row.seeds));Collections.sort(victoryTurns);
			if(victoryTurns.isEmpty())row.meanTurnsToVictory=row.medianTurnsToVictory=row.minTurnsToVictory=row.maxTurnsToVictory=-1;else{double sum=0;for(int value:victoryTurns)sum+=value;row.meanTurnsToVictory=sum/victoryTurns.size();int middle=victoryTurns.size()/2;row.medianTurnsToVictory=victoryTurns.size()%2==1?victoryTurns.get(middle):(victoryTurns.get(middle-1)+victoryTurns.get(middle))/2.0;row.minTurnsToVictory=victoryTurns.get(0);row.maxTurnsToVictory=victoryTurns.get(victoryTurns.size()-1);}
			result.add(row);
		}
		return result;
	}

	private static ArchetypeStressReport.BuildSummary summarize(ArchetypeReferenceBuilds.Id id,ArrayList<ArchetypeStressReport.RunResult> runs){
		ClassBuild build=ArchetypeReferenceBuilds.build(id);ArchetypeStressReport.BuildSummary result=new ArchetypeStressReport.BuildSummary();result.buildId=id.name();result.displayName=ArchetypeReferenceBuilds.displayName(id);result.playstyle=ArchetypeReferenceBuilds.playstyle(id);result.usedBudget=build.usedBudget();result.maxBudget=build.maxBudget();BuildAnalysis analysis=new RuleBuildAnalyzer().analyze(RuleBuild.from(build));result.integrityClassification=analysis.classification.name();ArrayList<Integer> victoryTurns=new ArrayList<>();
		for(ArchetypeStressHarness.ScenarioId scenario:ArchetypeStressHarness.ScenarioId.values()){int count=0,wins=0;for(ArchetypeStressReport.RunResult run:runs)if(run.buildId.equals(id.name())&&run.scenarioId.equals(scenario.name())){count++;result.runs++;if(run.victory){wins++;result.victories++;victoryTurns.add(run.turnsToVictory);}if(!run.survived)result.survivalFailures++;if(run.runtimeFailure)result.runtimeFailures++;add(result.mean,run.metrics);}result.scenarioVictoryRate.put(scenario.name(),count==0?0:wins/(double)count);}
		result.victoryRate=result.runs==0?0:result.victories/(double)result.runs;divide(result.mean,Math.max(1,result.runs));Collections.sort(victoryTurns);if(victoryTurns.isEmpty()){result.meanTurnsToVictory=result.medianTurnsToVictory=result.minTurnsToVictory=result.maxTurnsToVictory=-1;}else{double sum=0;for(int value:victoryTurns)sum+=value;result.meanTurnsToVictory=sum/victoryTurns.size();int middle=victoryTurns.size()/2;result.medianTurnsToVictory=victoryTurns.size()%2==1?victoryTurns.get(middle):(victoryTurns.get(middle-1)+victoryTurns.get(middle))/2.0;result.minTurnsToVictory=victoryTurns.get(0);result.maxTurnsToVictory=victoryTurns.get(victoryTurns.size()-1);}signature(result);return result;
	}

	private static void signature(ArchetypeStressReport.BuildSummary b){ArchetypeStressReport.BehaviorMetrics m=b.mean;
		if(m.entityDamage>m.playerDirectDamage/2||m.entityLifetimeTurns>5)b.signature.add("entity-led damage and persistent ally uptime");
		if(m.carrierDamage>0||m.entitiesCreated>1)b.signature.add("deployment and automated carrier contribution");
		if(m.statusDamage>0||m.controlTurns>2)b.signature.add("status/control network contribution");
		if(m.terrainCellsAltered>0)b.signature.add("terrain manipulation changes positioning value");
		if(m.forcedMovementCells>0)b.signature.add("forced movement controls distance and lanes");
		if(m.temporaryHpConsumed>0||m.barrierConsumed>0)b.signature.add("defense absorbs incoming pressure");
		if(m.modeSwitches>0)b.signature.add("mode switches alter skill availability");
		if(m.actionCostTurns>0)b.signature.add("committed actions create downtime");
		if(m.resourceSpent>0)b.signature.add("resource spending gates its strongest actions");
		if(m.normalAttackCount>m.skillUsageCount)b.signature.add("ordinary contact attacks remain a major action");
		if(b.signature.isEmpty())b.signature.add("low-signal build; inspect component utilization");
	}

	private static ArchetypeStressReport.ComponentUsage componentUsage(ArchetypeReferenceBuilds.Id id,ArrayList<ArchetypeStressReport.RunResult> runs){ClassBuild build=ArchetypeReferenceBuilds.build(id);ArchetypeStressReport.ComponentUsage result=new ArchetypeStressReport.ComponentUsage();result.buildId=id.name();
		for(ArchetypeStressReport.RunResult run:runs)if(run.buildId.equals(id.name())){merge(result.skillUses,run.metrics.skillUsage);merge(result.resourceGenerated,run.metrics.resourceGeneratedByPool);merge(result.resourceSpent,run.metrics.resourceSpentByPool);merge(result.componentSignals,run.metrics.componentSignals);merge(result.costPayments,run.metrics.costPayments);}
		for(SkillSpec skill:build.skills){int uses=value(result.skillUses,skill.id);String classification;if(uses==0)classification="RARELY_TRIGGERED";else{int contribution=skillContribution(id,skill,runs);classification=contribution>0?"USED_AND_VALUABLE":uses<Math.max(2,runs.size()/10)?"RARELY_TRIGGERED":"USED_BUT_WEAK";}result.classifications.put("SKILL:"+skill.id,classification);if(!"USED_AND_VALUABLE".equals(classification))result.deadOrLowValueComponents.add("SKILL:"+skill.id+":"+classification);}
		for(ResourceSpec resource:build.resources){if(value(result.resourceGenerated,resource.id)==0)result.deadOrLowValueComponents.add("RESOURCE_NO_SOURCE:"+resource.id);if(value(result.resourceSpent,resource.id)==0)result.deadOrLowValueComponents.add("RESOURCE_NO_SINK:"+resource.id);}
		for(com.shatteredpixel.shatteredpixeldungeon.rules.TraitSpec trait:build.traits){String signal=signal(trait.type);if(signal!=null){String classification=value(result.componentSignals,signal)>0?"USED_AND_VALUABLE":"RARELY_TRIGGERED";result.classifications.put("TRAIT:"+trait.stableId(),classification);if(!"USED_AND_VALUABLE".equals(classification))result.deadOrLowValueComponents.add("TRAIT:"+trait.stableId()+":"+classification);}}
		for(ClassLaw law:build.laws)if(law==ClassLaw.WATER_AFFINITY){String classification=value(result.componentSignals,"WATER_AFFINITY_CONTEXT")>0?"USED_AND_VALUABLE":"RARELY_TRIGGERED";result.classifications.put("LAW:"+law.name(),classification);if(!"USED_AND_VALUABLE".equals(classification))result.deadOrLowValueComponents.add("LAW:"+law.name()+":"+classification);}return result;}

	private static int skillContribution(ArchetypeReferenceBuilds.Id id,SkillSpec skill,ArrayList<ArchetypeStressReport.RunResult> runs){int result=0;for(ArchetypeStressReport.RunResult run:runs)if(run.buildId.equals(id.name())){result+=value(run.metrics.componentDamage,skill.id);switch(skill.primary.family){case RECOVERY_DEFENSE:result+=sum(run.metrics.componentMitigation);break;case STATUS:result+=run.metrics.statusDamage+run.metrics.controlTurns;break;case MOVEMENT:result+=run.metrics.forcedMovementCells;break;case RESOURCE_OPERATION:result+=run.metrics.resourceGenerated;break;case MARK_ACCUMULATION:result+=run.metrics.marksApplied+run.metrics.marksConsumed;break;case CREATE_ENTITY:result+=run.metrics.entityDamage+run.metrics.carrierDamage+run.metrics.entityLifetimeTurns;break;case WORLD_TERRAIN:result+=run.metrics.terrainCellsAltered+run.metrics.statusDamage;break;case TRANSFORM:result+=run.metrics.modeSwitches;break;default:break;}}return result;}
	private static int sum(LinkedHashMap<String,Integer> values){int result=0;for(int value:values.values())result+=value;return result;}

	private static ArchetypeStressReport.ComponentValueAttribution componentValue(ArchetypeReferenceBuilds.Id id,ArrayList<ArchetypeStressReport.RunResult> runs){ArchetypeStressReport.ComponentValueAttribution result=new ArchetypeStressReport.ComponentValueAttribution();result.buildId=id.name();for(ArchetypeStressReport.RunResult run:runs)if(run.buildId.equals(id.name())){merge(result.damage,run.metrics.componentDamage);merge(result.mitigation,run.metrics.componentMitigation);merge(result.control,run.metrics.componentControl);merge(result.resource,run.metrics.componentResource);merge(result.entity,run.metrics.componentEntity);merge(result.terrain,run.metrics.componentTerrain);}return result;}

	private static ArchetypeStressReport.SpecialtyReport specialty(ArchetypeReferenceBuilds.Id id,ArrayList<ArchetypeStressReport.BuildSummary> builds){ArchetypeStressReport.BuildSummary build=findSummary(builds,id.name());ArchetypeStressReport.SpecialtyReport result=new ArchetypeStressReport.SpecialtyReport();result.buildId=id.name();ArrayList<String> scenarios=new ArrayList<>(build.scenarioVictoryRate.keySet());Collections.sort(scenarios,new Comparator<String>(){@Override public int compare(String a,String b){int c=Double.compare(rate(build.scenarioVictoryRate,b),rate(build.scenarioVictoryRate,a));return c!=0?c:a.compareTo(b);}});for(int i=0;i<Math.min(3,scenarios.size());i++)result.bestScenarios.add(scenarios.get(i));for(int i=Math.max(0,scenarios.size()-3);i<scenarios.size();i++)result.worstScenarios.add(scenarios.get(i));for(String scenario:scenarios){double delta=rate(build.scenarioVictoryRate,scenario)-build.victoryRate;if(delta>=.15)result.relativeStrengths.add(scenario+" +"+Math.round(delta*100)+"pp");else if(delta<=-.15)result.relativeWeaknesses.add(scenario+" "+Math.round(delta*100)+"pp");}result.uniqueBehaviorSignals.addAll(build.signature);return result;}

	private static ArchetypeStressReport.BuildSummary findSummary(ArrayList<ArchetypeStressReport.BuildSummary> builds,String id){for(ArchetypeStressReport.BuildSummary build:builds)if(build.buildId.equals(id))return build;throw new IllegalArgumentException(id);}

	private static ArrayList<ArchetypeStressReport.ConstraintResult> constraints(ArchetypeReferenceBuilds.Id id,ArrayList<ArchetypeStressReport.RunResult> runs){ClassBuild build=ArchetypeReferenceBuilds.build(id);ArrayList<ArchetypeStressReport.ConstraintResult> result=new ArrayList<>();for(SkillSpec skill:build.skills){if(skill.constraint!=null&&skill.constraint.variant!=SkillConstraint.Variant.NONE){ArchetypeStressReport.ConstraintResult row=new ArchetypeStressReport.ConstraintResult();row.buildId=id.name();row.skillId=skill.id;row.constraint=skill.constraint.variant.name();row.nominalValue=skill.constraint.nominalRebate();row.effectiveValue=skill.constraint.effectiveRebate(build,skill);row.automaticallySatisfied=skill.constraint.automaticallySatisfied(build,skill);collectConstraintMetrics(row,id,skill,runs);result.add(row);}if(skill.cost!=null&&(skill.cost.type==RuleCost.Type.ACTION||skill.cost.type==RuleCost.Type.COOLDOWN)){ArchetypeStressReport.ConstraintResult row=new ArchetypeStressReport.ConstraintResult();row.buildId=id.name();row.skillId=skill.id;row.constraint="COST_"+skill.cost.type.name();row.nominalValue=skill.cost.budgetRebate();row.effectiveValue=skill.cost.effectiveBudgetRebate(skill.primary);collectConstraintMetrics(row,id,skill,runs);result.add(row);}}return result;}

	private static void collectConstraintMetrics(ArchetypeStressReport.ConstraintResult row,ArchetypeReferenceBuilds.Id id,SkillSpec skill,ArrayList<ArchetypeStressReport.RunResult> runs){int interval=0,samples=0;for(ArchetypeStressReport.RunResult run:runs)if(run.buildId.equals(id.name())){row.successfulUses+=value(run.metrics.skillUsage,skill.id);row.blockedAttempts+=value(run.metrics.skillFailures,skill.id);row.desiredButCooldownBlocked+=value(run.metrics.cooldownBlockedOpportunities,skill.id);row.legalButNotSelected+=value(run.metrics.cooldownLegalNotSelected,skill.id);row.cooldownUptime+=value(run.metrics.componentSignals,"COOLDOWN_UPTIME:"+skill.id);interval+=value(run.metrics.cooldownReuseIntervalTotal,skill.id);samples+=value(run.metrics.cooldownReuseSamples,skill.id);}row.actualReuseInterval=samples==0?0:interval/(double)samples;}

	private static ArrayList<ArchetypeStressReport.DominanceFinding> dominance(ArrayList<ArchetypeStressReport.BuildSummary> builds){ArrayList<ArchetypeStressReport.DominanceFinding> result=new ArrayList<>();ArrayList<String> primary=new ArrayList<>();for(ArchetypeReferenceBuilds.Id id:ArchetypeReferenceBuilds.primaryIds())primary.add(id.name());for(ArchetypeStressReport.BuildSummary a:builds)for(ArchetypeStressReport.BuildSummary b:builds)if(!a.buildId.equals(b.buildId)&&primary.contains(a.buildId)&&primary.contains(b.buildId)&&a.usedBudget<=b.usedBudget*1.05&&a.usedBudget>=b.usedBudget*.95){int wins=0,losses=0;for(String scenario:a.scenarioVictoryRate.keySet()){double av=a.scenarioVictoryRate.get(scenario),bv=b.scenarioVictoryRate.get(scenario);if(av>=bv+.2)wins++;else if(bv>=av+.2)losses++;}double singleA=averageRate(a,"SINGLE_NORMAL","HIGH_HP_SINGLE"),singleB=averageRate(b,"SINGLE_NORMAL","HIGH_HP_SINGLE"),crowdA=averageRate(a,"ENEMY_SWARM","MIXED_THREAT"),crowdB=averageRate(b,"ENEMY_SWARM","MIXED_THREAT");double sustainA=sustainability(a),sustainB=sustainability(b),controlA=control(a),controlB=control(b),efficiencyA=efficiency(a),efficiencyB=efficiency(b);boolean faster=a.meanTurnsToVictory>0&&(b.meanTurnsToVictory<0||a.meanTurnsToVictory<=b.meanTurnsToVictory*.9);boolean safer=a.mean.damageReceived<=b.mean.damageReceived*.9;boolean noMeasuredTradeoff=singleA+.1>=singleB&&crowdA+.1>=crowdB&&sustainA+.2>=sustainB;boolean dominant=a.victoryRate>=b.victoryRate+.2&&wins>=6&&losses<=2&&faster&&safer&&noMeasuredTradeoff;if(dominant){ArchetypeStressReport.DominanceFinding row=dominanceRow(a,b,wins,losses,singleA,singleB,crowdA,crowdB,controlA,controlB,sustainA,sustainB,efficiencyA,efficiencyB);row.classification="POTENTIALLY_DOMINANT";row.reason="higher scenario coverage, faster victories, and lower incoming damage without a measured single-target, crowd, or resource tradeoff";result.add(row);ArchetypeStressReport.DominanceFinding paired=dominanceRow(a,b,wins,losses,singleA,singleB,crowdA,crowdB,controlA,controlB,sustainA,sustainB,efficiencyA,efficiencyB);paired.classification="POTENTIALLY_DOMINATED";paired.reason=b.buildId+" shows no unique measured advantage over "+a.buildId+" in this standardized matrix";result.add(paired);}}return result;}

	private static ArchetypeStressReport.DominanceFinding dominanceRow(ArchetypeStressReport.BuildSummary a,ArchetypeStressReport.BuildSummary b,int wins,int losses,double singleA,double singleB,double crowdA,double crowdB,double controlA,double controlB,double sustainA,double sustainB,double efficiencyA,double efficiencyB){ArchetypeStressReport.DominanceFinding row=new ArchetypeStressReport.DominanceFinding();row.stronger=a.buildId;row.weaker=b.buildId;row.comparableScenarioWins=wins;row.comparableScenarioLosses=losses;row.strongerVictoryRate=a.victoryRate;row.weakerVictoryRate=b.victoryRate;row.strongerMeanTurns=a.meanTurnsToVictory;row.weakerMeanTurns=b.meanTurnsToVictory;row.strongerSingleTarget=singleA;row.weakerSingleTarget=singleB;row.strongerCrowd=crowdA;row.weakerCrowd=crowdB;row.strongerDamageReceived=a.mean.damageReceived;row.weakerDamageReceived=b.mean.damageReceived;row.strongerControl=controlA;row.weakerControl=controlB;row.strongerResourceSustainability=sustainA;row.weakerResourceSustainability=sustainB;row.strongerActionEfficiency=efficiencyA;row.weakerActionEfficiency=efficiencyB;return row;}
	private static double averageRate(ArchetypeStressReport.BuildSummary b,String a,String c){return(rate(b.scenarioVictoryRate,a)+rate(b.scenarioVictoryRate,c))/2.0;}
	private static double rate(LinkedHashMap<String,Double> values,String key){Double value=values.get(key);return value==null?0:value;}
	private static double sustainability(ArchetypeStressReport.BuildSummary b){return Math.min(2,(b.mean.resourceGenerated+1.0)/(b.mean.resourceSpent+1.0));}
	private static double control(ArchetypeStressReport.BuildSummary b){return b.mean.controlTurns+b.mean.forcedMovementCells*.5;}
	private static double efficiency(ArchetypeStressReport.BuildSummary b){return(b.mean.playerDirectDamage+b.mean.statusDamage+b.mean.entityDamage+b.mean.carrierDamage)/(double)Math.max(1,b.mean.skillUsageCount+b.mean.normalAttackCount+b.mean.actionCostTurns);}

	private static void addMissingCapabilities(Result result){ArchetypeStressReport.MissingCapability manual=new ArchetypeStressReport.MissingCapability();manual.capability="FINITE_MANUAL_RESOURCE_POOL";manual.status="IMPLEMENTED";manual.evidence="Ammo Gunner could not express finite ammunition because every old non-Blood pool had an automatic source or event-specific semantics.";manual.reusableUses="ammunition; device fuel; spell charges";manual.implementation="ResourceEngine.MANUAL plus ordinary RESOURCE_GAIN reload skill";result.missingCapabilities.add(manual);ArchetypeStressReport.MissingCapability limit=new ArchetypeStressReport.MissingCapability();limit.capability="SAVED_LIMITED_USE_CONSTRAINT";limit.status="IMPLEMENTED";limit.evidence="The frozen constraint existed in ClassBuild and budget data but SkillSpec rejected it, so effective limited-use QA was impossible.";limit.reusableUses="limited deployment; high-impact control; per-run emergency defense";limit.implementation="SkillConstraint.LIMITED_USE compiles to saved RuleDefinition useLimit";result.missingCapabilities.add(limit);ArchetypeStressReport.MissingCapability attribution=new ArchetypeStressReport.MissingCapability();attribution.capability="TRAP_DAMAGE_ATTRIBUTION";attribution.status="METRIC_LIMITATION";attribution.evidence="RuleCarrierTrap preserves owner provenance but its untyped damage source is the Hero, so trap damage cannot always be separated from other direct rule damage.";attribution.reusableUses="QA profiles; combat log; balance telemetry";attribution.implementation="not added; carrier deployment/use is still measured and gameplay is correct";result.missingCapabilities.add(attribution);}

	private static boolean foundationReady(Result result){ArchetypeStressReport.BuildSummary terrain=findSummary(result.summary.builds,"TERRAIN_CONTROLLER"),engineer=findSummary(result.summary.builds,"DEVICE_ENGINEER");double poor=rate(terrain.scenarioVictoryRate,"TERRAIN_POOR"),rich=rate(terrain.scenarioVictoryRate,"TERRAIN_RICH");boolean terrainIdentity=rich>=poor+.20&&Math.max(Math.max(rate(terrain.scenarioVictoryRate,"ENEMY_SWARM"),rate(terrain.scenarioVictoryRate,"NARROW_CORRIDOR")),Math.max(rich,rate(terrain.scenarioVictoryRate,"MIXED_THREAT")))>=terrain.victoryRate+.15;double engineerBest=0;for(double value:engineer.scenarioVictoryRate.values())engineerBest=Math.max(engineerBest,value);boolean automationSpecialty=engineerBest>=engineer.victoryRate+.15;int executes=0;LinkedHashMap<String,Integer> modeDamage=new LinkedHashMap<>(),modeMitigation=new LinkedHashMap<>();for(ArchetypeStressReport.RunResult run:result.runs){if(run.buildId.equals("MARK_ASSASSIN"))executes+=run.metrics.executeUsedTurns;if(run.buildId.equals("MODE_SHIFTER")){merge(modeDamage,run.metrics.damageByMode);merge(modeMitigation,run.metrics.mitigationByMode);}}boolean modesDistinct=positiveKeys(modeDamage)>=1&&positiveKeys(modeMitigation)>=1;return terrainIdentity&&automationSpecialty&&executes>0&&modesDistinct&&result.dominance.isEmpty()&&result.summary.runtimeFailures==0;}
	private static int positiveKeys(LinkedHashMap<String,Integer> values){int result=0;for(int value:values.values())if(value>0)result++;return result;}

	private static boolean primaryWithoutVictory(ArrayList<ArchetypeStressReport.BuildSummary> values){ArrayList<String> ids=new ArrayList<>();for(ArchetypeReferenceBuilds.Id id:ArchetypeReferenceBuilds.primaryIds())ids.add(id.name());for(ArchetypeStressReport.BuildSummary value:values)if(ids.contains(value.buildId)&&value.victories==0)return true;return false;}
	private static String signal(CoreRuleVocabulary trait){switch(trait){case PROPAGATION:return"PROPAGATION";case PHASE_SHIFT:return"PHASE_SHIFT";case SHIELD_BACKLASH:return"SHIELD_BACKLASH";case TRANSLOCATION_BACKLASH:return"TRANSLOCATION_BACKLASH";case INERTIA_BRIDGE:case TRANSLOCATION_BRIDGE:return"BRIDGE";case COMPENSATION:return"COMPENSATION";case OVERFLOW:return"OVERFLOW";case OVERDRAW:return"OVERDRAW";case STATUS_FEEDBACK:return"STATUS_FEEDBACK";case WATER_FLOW:return"WATER_FLOW";case KILL_TEMPO:return"KILL_TEMPO";case KINETIC_MARK:return"KINETIC_MARK";case MOBILE_CHARGE:return"MOBILE_CHARGE";case TEMP_HP_PAYMENT:return"TEMP_HP_PAYMENT";case PIERCING_MARK:return"PIERCING_MARK";case OWNED_RESOURCE_FEEDBACK:return"OWNED_RESOURCE_FEEDBACK";case CARRIER_RESOURCE_FEEDBACK:return"CARRIER_RESOURCE_FEEDBACK";case HAZARD_FEEDBACK:return"HAZARD_FEEDBACK";case MODE_GUARD:return"MODE_GUARD";case TRANSFER_FEEDBACK:return"TRANSFER_FEEDBACK";case STATUS_CHAIN:return"STATUS_CHAIN";default:return null;}}
	private static int value(LinkedHashMap<String,Integer> map,String key){Integer value=map.get(key);return value==null?0:value;}
	private static void merge(LinkedHashMap<String,Integer> target,LinkedHashMap<String,Integer> values){for(String key:values.keySet())target.put(key,value(target,key)+values.get(key));}
	private static void add(ArchetypeStressReport.BehaviorMetrics a,ArchetypeStressReport.BehaviorMetrics b){a.turnsSurvived+=b.turnsSurvived;a.playerDirectDamage+=b.playerDirectDamage;a.statusDamage+=b.statusDamage;a.entityDamage+=b.entityDamage;a.carrierDamage+=b.carrierDamage;a.damageReceived+=b.damageReceived;a.damageMitigated+=b.damageMitigated;a.barrierConsumed+=b.barrierConsumed;a.temporaryHpConsumed+=b.temporaryHpConsumed;a.healing+=b.healing;a.forcedMovementCells+=b.forcedMovementCells;a.enemiesControlled+=b.enemiesControlled;a.controlTurns+=b.controlTurns;a.skillUsageCount+=b.skillUsageCount;a.normalAttackCount+=b.normalAttackCount;a.moveCount+=b.moveCount;a.waitCount+=b.waitCount;a.actionCostTurns+=b.actionCostTurns;a.resourceGenerated+=b.resourceGenerated;a.resourceSpent+=b.resourceSpent;a.resourceOverflowWaste+=b.resourceOverflowWaste;a.marksApplied+=b.marksApplied;a.marksConsumed+=b.marksConsumed;a.entitiesCreated+=b.entitiesCreated;a.entityLifetimeTurns+=b.entityLifetimeTurns;a.terrainCellsAltered+=b.terrainCellsAltered;a.modeSwitches+=b.modeSwitches;a.attachmentTriggers+=b.attachmentTriggers;a.failedSkillAttempts+=b.failedSkillAttempts;a.hpCostPaid+=b.hpCostPaid;a.executeLegalTurns+=b.executeLegalTurns;a.executeUsedTurns+=b.executeUsedTurns;a.executeMissedOpportunities+=b.executeMissedOpportunities;a.targetKilledBeforeExecute+=b.targetKilledBeforeExecute;a.executeOverkillValue+=b.executeOverkillValue;a.marksReadyButExecuteUnavailable+=b.marksReadyButExecuteUnavailable;a.switchActionCost+=b.switchActionCost;a.redundantModeSwitches+=b.redundantModeSwitches;a.immediateSwitchBacks+=b.immediateSwitchBacks;merge(a.skillUsage,b.skillUsage);merge(a.skillFailures,b.skillFailures);merge(a.resourceGeneratedByPool,b.resourceGeneratedByPool);merge(a.resourceSpentByPool,b.resourceSpentByPool);merge(a.componentSignals,b.componentSignals);merge(a.costPayments,b.costPayments);merge(a.cooldownBlockedOpportunities,b.cooldownBlockedOpportunities);merge(a.cooldownLegalNotSelected,b.cooldownLegalNotSelected);merge(a.cooldownReuseIntervalTotal,b.cooldownReuseIntervalTotal);merge(a.cooldownReuseSamples,b.cooldownReuseSamples);merge(a.modeUptime,b.modeUptime);merge(a.skillsUsedByMode,b.skillsUsedByMode);merge(a.damageByMode,b.damageByMode);merge(a.mitigationByMode,b.mitigationByMode);merge(a.movementByMode,b.movementByMode);merge(a.componentDamage,b.componentDamage);merge(a.componentMitigation,b.componentMitigation);merge(a.componentControl,b.componentControl);merge(a.componentResource,b.componentResource);merge(a.componentEntity,b.componentEntity);merge(a.componentTerrain,b.componentTerrain);}
	private static void divide(ArchetypeStressReport.BehaviorMetrics m,int n){m.turnsSurvived/=n;m.playerDirectDamage/=n;m.statusDamage/=n;m.entityDamage/=n;m.carrierDamage/=n;m.damageReceived/=n;m.damageMitigated/=n;m.barrierConsumed/=n;m.temporaryHpConsumed/=n;m.healing/=n;m.forcedMovementCells/=n;m.enemiesControlled/=n;m.controlTurns/=n;m.skillUsageCount/=n;m.normalAttackCount/=n;m.moveCount/=n;m.waitCount/=n;m.actionCostTurns/=n;m.resourceGenerated/=n;m.resourceSpent/=n;m.resourceOverflowWaste/=n;m.marksApplied/=n;m.marksConsumed/=n;m.entitiesCreated/=n;m.entityLifetimeTurns/=n;m.terrainCellsAltered/=n;m.modeSwitches/=n;m.attachmentTriggers/=n;m.failedSkillAttempts/=n;m.hpCostPaid/=n;m.executeLegalTurns/=n;m.executeUsedTurns/=n;m.executeMissedOpportunities/=n;m.targetKilledBeforeExecute/=n;m.executeOverkillValue/=n;m.marksReadyButExecuteUnavailable/=n;m.switchActionCost/=n;m.redundantModeSwitches/=n;m.immediateSwitchBacks/=n;divideMap(m.skillUsage,n);divideMap(m.skillFailures,n);divideMap(m.resourceGeneratedByPool,n);divideMap(m.resourceSpentByPool,n);divideMap(m.componentSignals,n);divideMap(m.costPayments,n);divideMap(m.cooldownBlockedOpportunities,n);divideMap(m.cooldownLegalNotSelected,n);divideMap(m.cooldownReuseIntervalTotal,n);divideMap(m.cooldownReuseSamples,n);divideMap(m.modeUptime,n);divideMap(m.skillsUsedByMode,n);divideMap(m.damageByMode,n);divideMap(m.mitigationByMode,n);divideMap(m.movementByMode,n);divideMap(m.componentDamage,n);divideMap(m.componentMitigation,n);divideMap(m.componentControl,n);divideMap(m.componentResource,n);divideMap(m.componentEntity,n);divideMap(m.componentTerrain,n);}
	private static void divideMap(LinkedHashMap<String,Integer> values,int n){for(String key:new ArrayList<>(values.keySet()))values.put(key,values.get(key)/n);}
}
