package com.shatteredpixel.shatteredpixeldungeon.qa;

import com.shatteredpixel.shatteredpixeldungeon.rules.*;

import java.util.ArrayList;
import java.util.Arrays;

import static com.shatteredpixel.shatteredpixeldungeon.qa.QaScenario.Action.Type.*;

/** Headless-only reference builds. These are coverage fixtures, never player class presets. */
public final class FullSkillReferenceBuilds {
	private FullSkillReferenceBuilds() {}
	public static ArrayList<QaScenario> scenarios(){return new ArrayList<>(Arrays.asList(
			ammoProjectile(),piercingBeam(),coneController(),chainStatus(),temporaryHpBruiser(),
			ownedSummon(),summonMark(),persistentField(),terrainControl(),modeShift(),statusCopy(),reactionOnly(),
			actionAttachment(),trapCarrier(),entityExpiry(),blobCreation(),ownedCommandInheritance()));}

	public static QaScenario ammoProjectile(){ClassBuild b=base("ref_ammo_projectile");ResourceSpec ammo=new ResourceSpec(ResourceEngine.MANA);ammo.id="ammo";b.resources.add(ammo);
		SkillSpec s=skill("shot",new EffectSpec(EffectFamily.DAMAGE,EffectSpec.Operation.DAMAGE_STANDARD,4),enemy(),SkillDelivery.PROJECTILE);s.cost=new RuleCost(RuleCost.Type.RESOURCE,1);s.cost.resourceId="ammo";s.cost.resourceEngine=ResourceEngine.MANA;b.skills.add(s);
		QaScenario q=scenario(b,91001);q.actions.add(QaScenario.Action.of(SET_RESOURCE).resource("ammo").value(10));q.actions.add(QaScenario.Action.of(SPAWN_MOB).mob("RAT").cell(26).value(12));q.actions.add(QaScenario.Action.of(SET_TILE).cell(25).tile("WALL"));q.actions.add(QaScenario.Action.of(USE_ACTIVE_RULE).skill("shot").cell(26));q.expectedFindings.add("PROJECTILE_WALL_BLOCK_OK");return q;}
	public static QaScenario piercingBeam(){ClassBuild b=base("ref_piercing_beam");SkillSpec s=skill("beam",new EffectSpec(EffectFamily.DAMAGE,EffectSpec.Operation.DAMAGE_STANDARD,3),enemy(),SkillDelivery.TRACE_BEAM);s.targeting.coverage=TargetingSpec.Coverage.LINE;s.modifier=new RuleModifier(RuleModifier.Type.PIERCE);s.modifier.magnitude=3;s.cost=new RuleCost(RuleCost.Type.ACTION,1);b.skills.add(s);
		QaScenario q=scenario(b,91002);q.actions.add(QaScenario.Action.of(SPAWN_MOB).mob("RAT").cell(25).value(10));q.actions.add(QaScenario.Action.of(SPAWN_MOB).mob("SNAKE").cell(26).value(10));q.actions.add(QaScenario.Action.of(USE_ACTIVE_RULE).skill("beam").cell(26));q.expectedFindings.add("BEAM_MULTI_HIT_OK");return q;}
	public static QaScenario coneController(){ClassBuild b=base("ref_cone_controller");TargetingSpec t=enemy();t.coverage=TargetingSpec.Coverage.CONE;t.maxTargets=6;SkillSpec s=skill("cone",new EffectSpec(EffectFamily.MOVEMENT,EffectSpec.Operation.MOVE_THROW,2),t,SkillDelivery.DIRECT_TARGET);s.cost=new RuleCost(RuleCost.Type.COOLDOWN,3);b.skills.add(s);
		QaScenario q=scenario(b,91003);q.actions.add(QaScenario.Action.of(SPAWN_MOB).mob("RAT").cell(17).value(10));q.actions.add(QaScenario.Action.of(SPAWN_MOB).mob("SNAKE").cell(25).value(10));q.actions.add(QaScenario.Action.of(USE_ACTIVE_RULE).skill("cone").cell(17));q.expectedFindings.add("CONE_TARGETING_OK");return q;}
	public static QaScenario chainStatus(){ClassBuild b=base("ref_chain_status");TargetingSpec t=enemy();t.coverage=TargetingSpec.Coverage.CHAIN;t.magnitude=3;t.maxTargets=3;SkillSpec s=skill("chain_poison",new EffectSpec(EffectFamily.STATUS,EffectSpec.Operation.STATUS_POISON,2),t,SkillDelivery.DIRECT_TARGET);s.cost=new RuleCost(RuleCost.Type.ACTION,1);b.skills.add(s);
		QaScenario q=scenario(b,91004);q.actions.add(QaScenario.Action.of(SPAWN_MOB).mob("RAT").cell(25).value(10));q.actions.add(QaScenario.Action.of(SPAWN_MOB).mob("SNAKE").cell(26).value(10));q.actions.add(QaScenario.Action.of(SPAWN_MOB).mob("RAT").cell(19).value(10));q.actions.add(QaScenario.Action.of(USE_ACTIVE_RULE).skill("chain_poison").cell(25));q.expectedFindings.add("CHAIN_STATUS_OK");return q;}
	public static QaScenario temporaryHpBruiser(){ClassBuild b=base("ref_temporary_hp");SkillSpec s=skill("temp_hp",new EffectSpec(EffectFamily.RECOVERY_DEFENSE,EffectSpec.Operation.DEFENSE_TEMP_HP,8),self(),SkillDelivery.SELF);s.primary.duration=3;s.cost=new RuleCost(RuleCost.Type.HP,2);b.skills.add(s);
		QaScenario q=scenario(b,91005);q.actions.add(QaScenario.Action.of(SET_HP).value(25));q.actions.add(QaScenario.Action.of(USE_ACTIVE_RULE).skill("temp_hp").cell(24));q.actions.add(QaScenario.Action.of(WAIT).repeat(4));q.expectedFindings.add("TEMP_HP_EXPIRY_OK");return q;}
	public static QaScenario ownedSummon(){ClassBuild b=owned(base("ref_owned_summon"),6,0);EffectSpec e=new EffectSpec(EffectFamily.CREATE_ENTITY,EffectSpec.Operation.CREATE_ACTOR,6);e.lifetime=10;SkillSpec s=skill("summon",e,cell(),SkillDelivery.GROUND_PLACEMENT);s.cost=new RuleCost(RuleCost.Type.ACTION,2);b.skills.add(s);
		QaScenario q=scenario(b,91006);q.actions.add(QaScenario.Action.of(SPAWN_MOB).mob("RAT").cell(26).value(20));q.actions.add(QaScenario.Action.of(USE_ACTIVE_RULE).skill("summon").cell(25));q.actions.add(QaScenario.Action.of(WAIT));q.actions.add(QaScenario.Action.of(SAVE_RELOAD));q.expectedFindings.add("OWNED_SUMMON_SAVE_OK");return q;}
	public static QaScenario summonMark(){ClassBuild b=owned(base("ref_summon_mark"),6,0);EffectSpec e=new EffectSpec(EffectFamily.CREATE_ENTITY,EffectSpec.Operation.CREATE_ACTOR,2);e.lifetime=5;SkillSpec summon=skill("summon",e,cell(),SkillDelivery.GROUND_PLACEMENT);summon.cost=new RuleCost(RuleCost.Type.ACTION,1);b.skills.add(summon);TargetingSpec owned=new TargetingSpec();owned.selector=TargetingSpec.Selector.ALL_MATCHING;owned.filter=TargetingSpec.Filter.OWNED_ENTITY;SkillSpec mark=skill("mark_owned",new EffectSpec(EffectFamily.MARK_ACCUMULATION,EffectSpec.Operation.MARK_APPLY,2),owned,SkillDelivery.DIRECT_TARGET);mark.primary.stateId="HUNTED";mark.cost=new RuleCost(RuleCost.Type.COOLDOWN,2);b.skills.add(mark);
		QaScenario q=scenario(b,91007);q.actions.add(QaScenario.Action.of(USE_ACTIVE_RULE).skill("summon").cell(25));q.actions.add(QaScenario.Action.of(USE_ACTIVE_RULE).skill("mark_owned").cell(25));q.expectedFindings.add("SUMMON_MARK_OK");return q;}
	public static QaScenario persistentField(){ClassBuild b=owned(base("ref_persistent_field"),0,6);EffectSpec e=new EffectSpec(EffectFamily.STATUS,EffectSpec.Operation.STATUS_POISON,1);e.lifetime=6;e.period=1;SkillSpec s=skill("field",e,cell(),SkillDelivery.PERSISTENT_CARRIER);s.cost=new RuleCost(RuleCost.Type.ACTION,2);b.skills.add(s);
		QaScenario q=scenario(b,91008);q.actions.add(QaScenario.Action.of(SPAWN_MOB).mob("RAT").cell(26).value(10));q.actions.add(QaScenario.Action.of(USE_ACTIVE_RULE).skill("field").cell(25));q.actions.add(QaScenario.Action.of(WAIT).repeat(2));q.actions.add(QaScenario.Action.of(SAVE_RELOAD));q.expectedFindings.add("PERSISTENT_FIELD_OK");return q;}
	public static QaScenario terrainControl(){ClassBuild b=base("ref_terrain_control");EffectSpec e=new EffectSpec(EffectFamily.WORLD_TERRAIN,EffectSpec.Operation.WORLD_WATER,1);SkillSpec s=skill("water",e,cell(),SkillDelivery.GROUND_PLACEMENT);s.cost=new RuleCost(RuleCost.Type.COOLDOWN,2);b.skills.add(s);
		QaScenario q=scenario(b,91009);q.actions.add(QaScenario.Action.of(USE_ACTIVE_RULE).skill("water").cell(25));q.expectedFindings.add("TERRAIN_CONTROL_OK");return q;}
	public static QaScenario modeShift(){ClassBuild b=base("ref_mode_shift");addModes(b,"assault","guard");SkillSpec guard=skill("mode_guard",new EffectSpec(RuleEffect.Type.SHIELD,3),self(),SkillDelivery.SELF);guard.activation=RuleEvent.ON_WAIT;guard.conditions.clear();RuleCondition condition=new RuleCondition(RuleCondition.Type.MODE_IS);condition.reference="assault";guard.conditions.add(condition);guard.cost=new RuleCost(RuleCost.Type.COOLDOWN,2);b.skills.add(guard);
		QaScenario q=scenario(b,91010);q.actions.add(QaScenario.Action.of(USE_CLASS_OPERATION).operation("mode_switch").cell(24));q.actions.add(QaScenario.Action.of(WAIT));q.actions.add(QaScenario.Action.of(SAVE_RELOAD));q.expectedFindings.add("MODE_SHIFT_OK");return q;}
	public static QaScenario statusCopy(){ClassBuild b=base("ref_status_copy");EffectSpec copy=new EffectSpec(EffectFamily.TRANSFER_COPY,EffectSpec.Operation.COPY_STATUS,1);SkillSpec s=skill("copy_status",copy,enemy(),SkillDelivery.DIRECT_TARGET);s.cost=new RuleCost(RuleCost.Type.ACTION,1);b.skills.add(s);
		QaScenario q=scenario(b,91011);q.actions.add(QaScenario.Action.of(APPLY_STATUS).status("POISON").value(5));q.actions.add(QaScenario.Action.of(SPAWN_MOB).mob("RAT").cell(25).value(10));q.actions.add(QaScenario.Action.of(USE_ACTIVE_RULE).skill("copy_status").cell(25));q.expectedFindings.add("STATUS_COPY_OK");return q;}
	public static QaScenario reactionOnly(){ClassBuild b=base("ref_reaction_only");SkillSpec s=skill("hit_bleed",new EffectSpec(EffectFamily.STATUS,EffectSpec.Operation.STATUS_BLEEDING,3),enemy(),SkillDelivery.CONTACT_ATTACK);s.activation=RuleEvent.ON_HIT;s.cost=new RuleCost(RuleCost.Type.COOLDOWN,2);b.skills.add(s);
		QaScenario q=scenario(b,91012);q.actions.add(QaScenario.Action.of(SPAWN_MOB).mob("RAT").cell(25).value(20));q.actions.add(QaScenario.Action.of(ATTACK));q.expectedFindings.add("REACTION_ONLY_RUNTIME_OK");return q;}
	public static QaScenario actionAttachment(){ClassBuild b=base("ref_attachment_save");EffectSpec poison=new EffectSpec(EffectFamily.STATUS,EffectSpec.Operation.STATUS_POISON,2);SkillSpec s=skill("venom_next_hit",poison,self(),SkillDelivery.ACTION_ATTACHMENT);s.secondary=new EffectSpec(EffectFamily.STATUS,EffectSpec.Operation.STATUS_SLOW,1);s.attachmentEvent=RuleEvent.ON_HIT;s.attachmentCharges=1;s.cost=new RuleCost(RuleCost.Type.ACTION,1);b.skills.add(s);
		QaScenario q=scenario(b,91013);q.actions.add(QaScenario.Action.of(SPAWN_MOB).mob("RAT").cell(25).value(30));q.actions.add(QaScenario.Action.of(USE_ACTIVE_RULE).skill("venom_next_hit").cell(24));q.actions.add(QaScenario.Action.of(SAVE_RELOAD));q.actions.add(QaScenario.Action.of(ATTACK));q.expectedFindings.add("ATTACHMENT_SAVE_CONSUME_OK");return q;}
	public static QaScenario trapCarrier(){ClassBuild b=base("ref_trap_carrier");EffectSpec trap=new EffectSpec(EffectFamily.CREATE_ENTITY,EffectSpec.Operation.CREATE_TRAP,2);trap.stateId="poison";SkillSpec s=skill("poison_trap",trap,cell(),SkillDelivery.GROUND_PLACEMENT);s.cost=new RuleCost(RuleCost.Type.ACTION,1);b.skills.add(s);
		QaScenario q=scenario(b,91014);q.actions.add(QaScenario.Action.of(USE_ACTIVE_RULE).skill("poison_trap").cell(25));q.actions.add(QaScenario.Action.of(MOVE).cell(25));q.expectedFindings.add("TRAP_CARRIER_TRIGGER_OK");return q;}
	public static QaScenario entityExpiry(){ClassBuild b=owned(base("ref_entity_expiry"),6,0);ResourceSpec scrap=new ResourceSpec();scrap.id="scrap";scrap.name="Scrap";scrap.initialValue=0;scrap.capacity=6;b.resources.add(scrap);b.gameplayComponents.add(ClassGameplayComponentSpec.resourceFlow("scrap_recycle","scrap",ResourceFlowSpec.Trigger.OWNED_ENTITY_REMOVED,ResourceFlowSpec.Operation.GAIN,2,1,0));EffectSpec actor=new EffectSpec(EffectFamily.CREATE_ENTITY,EffectSpec.Operation.CREATE_ACTOR,2);actor.lifetime=2;SkillSpec s=skill("brief_ally",actor,cell(),SkillDelivery.GROUND_PLACEMENT);s.cost=new RuleCost(RuleCost.Type.ACTION,1);b.skills.add(s);
		QaScenario q=scenario(b,91015);q.actions.add(QaScenario.Action.of(USE_ACTIVE_RULE).skill("brief_ally").cell(25));q.actions.add(QaScenario.Action.of(WAIT).repeat(4));q.expectedFindings.add("OWNED_ENTITY_EXPIRY_OK");return q;}
	public static QaScenario blobCreation(){ClassBuild b=base("ref_blob_creation");EffectSpec gas=new EffectSpec(EffectFamily.WORLD_TERRAIN,EffectSpec.Operation.WORLD_TOXIC_GAS,2);SkillSpec s=skill("gas",gas,cell(),SkillDelivery.GROUND_PLACEMENT);s.cost=new RuleCost(RuleCost.Type.COOLDOWN,2);b.skills.add(s);
		QaScenario q=scenario(b,91016);q.actions.add(QaScenario.Action.of(USE_ACTIVE_RULE).skill("gas").cell(25));q.expectedFindings.add("BLOB_CREATION_OK");return q;}
	public static QaScenario ownedCommandInheritance(){ClassBuild b=owned(base("ref_owned_command_inherit"),1,0);addModes(b,"assault","guard");ClassGameplayComponentSpec commandCapability=new ClassGameplayComponentSpec(ClassGameplayComponentSpec.Type.COMMAND,"command");commandCapability.entityFilter=ClassGameplayComponentSpec.EntityFilter.OWNED_ACTOR;b.gameplayComponents.add(commandCapability);EffectSpec actor=new EffectSpec(EffectFamily.CREATE_ENTITY,EffectSpec.Operation.CREATE_ACTOR,2);actor.lifetime=10;SkillSpec summon=skill("summon",actor,cell(),SkillDelivery.GROUND_PLACEMENT);summon.cost=new RuleCost(RuleCost.Type.ACTION,1);b.skills.add(summon);TargetingSpec owned=new TargetingSpec();owned.selector=TargetingSpec.Selector.ALL_MATCHING;owned.filter=TargetingSpec.Filter.OWNED_ENTITY;EffectSpec inherit=new EffectSpec(EffectFamily.RELATION_CONTROL,EffectSpec.Operation.RELATION_INHERIT,1);inherit.stateId="mode";SkillSpec inheritance=skill("inherit",inherit,owned,SkillDelivery.DIRECT_TARGET);inheritance.cost=new RuleCost(RuleCost.Type.COOLDOWN,2);b.skills.add(inheritance);
		QaScenario q=scenario(b,91017);q.actions.add(QaScenario.Action.of(USE_ACTIVE_RULE).skill("summon").cell(25));q.actions.add(QaScenario.Action.of(USE_CLASS_OPERATION).operation("mode_switch").cell(24));q.actions.add(QaScenario.Action.of(USE_ACTIVE_RULE).skill("inherit").cell(24));q.actions.add(QaScenario.Action.of(SPAWN_MOB).mob("RAT").cell(26).value(20));q.actions.add(QaScenario.Action.of(USE_CLASS_OPERATION).operation("command").cell(26));q.actions.add(QaScenario.Action.of(WAIT));q.actions.add(QaScenario.Action.of(SAVE_RELOAD));q.expectedFindings.add("OWNED_COMMAND_INHERIT_OK");return q;}

	private static ClassBuild base(String id){ClassBuild b=new ClassBuild();b.name=id;b.baseBudget=ClassBudgetPolicy.newBuildBudget();return b;}
	private static void addModes(ClassBuild b,String... ids){ClassGameplayComponentSpec c=new ClassGameplayComponentSpec(ClassGameplayComponentSpec.Type.MODE_ENGINE,"mode_engine");for(String id:ids)c.modes.add(id);b.gameplayComponents.add(c);}
	private static ClassBuild owned(ClassBuild b,int actors,int persistent){b.gameplayComponents.add(new ClassGameplayComponentSpec(ClassGameplayComponentSpec.Type.OWNERSHIP,"ownership"));if(actors>0){ClassGameplayComponentSpec c=new ClassGameplayComponentSpec(ClassGameplayComponentSpec.Type.ENTITY_CAPACITY,"actor_capacity");c.entityFilter=ClassGameplayComponentSpec.EntityFilter.OWNED_ACTOR;c.capacity=actors;b.gameplayComponents.add(c);}if(persistent>0){ClassGameplayComponentSpec c=new ClassGameplayComponentSpec(ClassGameplayComponentSpec.Type.ENTITY_CAPACITY,"persistent_capacity");c.entityFilter=ClassGameplayComponentSpec.EntityFilter.OWNED_ENTITY;c.capacity=persistent;b.gameplayComponents.add(c);}return b;}
	private static SkillSpec skill(String id,EffectSpec effect,TargetingSpec target,SkillDelivery delivery){SkillSpec s=new SkillSpec();s.id=id;s.activation=RuleEvent.ACTIVE;s.primary=effect;s.targeting=target;s.delivery=delivery;s.conditions.clear();s.conditions.add(new RuleCondition());s.cost=new RuleCost(RuleCost.Type.NONE,0);return s;}
	private static TargetingSpec self(){return new TargetingSpec();}
	private static TargetingSpec enemy(){TargetingSpec t=new TargetingSpec();t.selector=TargetingSpec.Selector.SELECTED_ACTOR;t.filter=TargetingSpec.Filter.ENEMY;return t;}
	private static TargetingSpec cell(){TargetingSpec t=new TargetingSpec();t.selector=TargetingSpec.Selector.SELECTED_CELL;t.filter=TargetingSpec.Filter.ANY;return t;}
	private static QaScenario scenario(ClassBuild b,long seed){QaScenario q=new QaScenario();q.id=b.name;q.seed=seed;q.hero.classBuild=b;return q;}
}
