package com.shatteredpixel.shatteredpixeldungeon.qa;

import com.shatteredpixel.shatteredpixeldungeon.rules.*;
import com.watabou.utils.Bundle;

import java.util.ArrayList;

/** Rebuilds the ten coverage archetypes solely through formal player selections, then runs combat. */
public final class PlayerArchetypeReconstructionAudit {
	public static final class BuildRow {public String id;public int used,max;public boolean constructible,roundtrip,runtimeVerified;public final ArrayList<String> resources=new ArrayList<>();public final ArrayList<String> gameplayComponents=new ArrayList<>();public final ArrayList<String> skills=new ArrayList<>();public final ArrayList<String> classOperations=new ArrayList<>();public final ArrayList<String> failures=new ArrayList<>();public final ArrayList<String> validationIssues=new ArrayList<>();}
	public static final class Result {public String schema="player-archetype-reconstruction-1";public int archetypes,qaBuildNotPlayerConstructible,discussedComponentNotPlayerExposed,dependencyMissingButDisabled,dependencyCopyValidationMismatch,runtimeFailures;public final ArrayList<BuildRow> builds=new ArrayList<>();public boolean passed;}
	private PlayerArchetypeReconstructionAudit() {}

	public static Result run(){Result r=new Result();GameplayComponentCoverageAudit.Result coverage=GameplayComponentCoverageAudit.run();r.discussedComponentNotPlayerExposed=coverage.discussedComponentNotPlayerExposed;
		for(ArchetypeReferenceBuilds.Id id:ArchetypeReferenceBuilds.primaryIds()){
			// This task's ten-item reconstruction contract uses a dedicated Defense/Support build;
			// STATUS_CONTROLLER remains in the independent stress matrix.
			if(id==ArchetypeReferenceBuilds.Id.STATUS_CONTROLLER)continue;
			auditBuild(r,id.name(),ArchetypeReferenceBuilds.build(id),91000L+id.ordinal());
		}
		auditBuild(r,"DEFENSE_SUPPORT",defenseSupport(),91999L);
		ClassBuild empty=new ClassBuild();for(ClassLaw law:LawTraitRegistry.laws()){ComponentDependency d=LawTraitRegistry.lawDependency(empty,law);if(d.state==ComponentDependency.State.UNRESOLVED&&!d.playerSelectable())r.dependencyMissingButDisabled++;}for(LawTraitRegistry.TraitOption option:LawTraitRegistry.traitOptions(empty))if(option.dependency.state==ComponentDependency.State.UNRESOLVED&&!option.playerSelectable())r.dependencyMissingButDisabled++;
		if(!overdraftDependencyMatches())r.dependencyCopyValidationMismatch++;
		if(!pendingResourceCostResolves())r.dependencyCopyValidationMismatch++;
		if(!pendingModeConditionResolves())r.dependencyCopyValidationMismatch++;
		if(!pendingConditionKindsRemainSelectable())r.dependencyMissingButDisabled++;
		r.passed=r.qaBuildNotPlayerConstructible==0&&r.discussedComponentNotPlayerExposed==0&&r.dependencyMissingButDisabled==0&&r.dependencyCopyValidationMismatch==0&&r.runtimeFailures==0;return r;}

	private static void auditBuild(Result r,String id,ClassBuild source,long seed){PlayerBuildAssembler assembler=PlayerBuildAssembler.reconstruct(source);ClassBuild player=assembler.build();BuildRow row=new BuildRow();row.id=id;row.used=player.usedBudget();row.max=player.maxBudget();for(ResourceSpec resource:player.resources)row.resources.add(resource.id+":"+resource.displayName()+" "+resource.initialValue+"/"+resource.capacity);for(ClassGameplayComponentSpec component:player.gameplayComponents)row.gameplayComponents.add(component.id+":"+component.type);for(SkillSpec skill:player.skills)row.skills.add(skill.id);for(ClassOperationSpec operation:player.operations)row.classOperations.add(operation.id+":"+operation.type+"<-"+operation.sourceComponentId);row.failures.addAll(assembler.failures());ArrayList<PlayerFacingValidationIssue> validation=PlayerFacingBuildValidator.classIssues(player);if(!validation.isEmpty()){row.failures.add("PLAYER_VALIDATION");for(PlayerFacingValidationIssue issue:validation)row.validationIssues.add(issue.code+":"+issue.affectedField+":"+issue.shortMessage);}row.roundtrip=roundtrip(player);if(!row.roundtrip)row.failures.add("ROUNDTRIP");ArchetypeStressReport.RunResult run=new ArchetypeStressHarness().run(player,"PLAYER_"+id,ArchetypeStressHarness.ScenarioId.SINGLE_NORMAL,seed);row.runtimeVerified=!run.runtimeFailure;if(run.runtimeFailure){row.failures.add("RUNTIME");r.runtimeFailures++;}row.constructible=row.failures.isEmpty();if(!row.constructible)r.qaBuildNotPlayerConstructible++;r.builds.add(row);r.archetypes++;}

	/** Ordinary player components only: a temporary ally is the legal redirect/link recipient. */
	private static ClassBuild defenseSupport(){ClassBuild b=new ClassBuild();b.name="defense_support";
		b.gameplayComponents.add(new ClassGameplayComponentSpec(ClassGameplayComponentSpec.Type.OWNERSHIP,"ownership"));ClassGameplayComponentSpec capacity=new ClassGameplayComponentSpec(ClassGameplayComponentSpec.Type.ENTITY_CAPACITY,"actor_capacity");capacity.entityFilter=ClassGameplayComponentSpec.EntityFilter.OWNED_ACTOR;capacity.capacity=1;b.gameplayComponents.add(capacity);
		// It gives up ordinary weapons and ordinary healing; owned actors and rule-based recovery are
		// the actual enemy-resolution/sustain loop, so these are real player tradeoffs, not QA budget.
		b.restrictions.add(Restriction.NO_ORDINARY_WEAPONS);b.restrictions.add(Restriction.NO_TRADITIONAL_HEALING);
		EffectSpec actor=new EffectSpec(EffectFamily.CREATE_ENTITY,EffectSpec.Operation.CREATE_ACTOR,2);actor.lifetime=8;SkillSpec summon=skill("support_ally",actor,cell(),SkillDelivery.GROUND_PLACEMENT,new RuleCost(RuleCost.Type.ACTION,1));b.skills.add(summon);
		b.skills.add(skill("mend_ally",new EffectSpec(EffectFamily.RECOVERY_DEFENSE,EffectSpec.Operation.RECOVER_HEAL,4),owned(),SkillDelivery.DIRECT_TARGET,new RuleCost(RuleCost.Type.ACTION,2)));
		EffectSpec temporary=new EffectSpec(EffectFamily.RECOVERY_DEFENSE,EffectSpec.Operation.DEFENSE_TEMP_HP,4);temporary.duration=4;b.skills.add(skill("temporary_guard",temporary,self(),SkillDelivery.SELF,new RuleCost(RuleCost.Type.COOLDOWN,3)));
		b.skills.add(skill("cleanse",new EffectSpec(EffectFamily.RECOVERY_DEFENSE,EffectSpec.Operation.DEFENSE_CLEANSE,2),self(),SkillDelivery.SELF,new RuleCost(RuleCost.Type.COOLDOWN,4)));
		EffectSpec redirect=new EffectSpec(EffectFamily.RECOVERY_DEFENSE,EffectSpec.Operation.DEFENSE_REDIRECT,3);redirect.duration=5;b.skills.add(skill("shared_guard",redirect,self(),SkillDelivery.SELF,new RuleCost(RuleCost.Type.COOLDOWN,4)));
		EffectSpec link=new EffectSpec(EffectFamily.RELATION_CONTROL,EffectSpec.Operation.RELATION_LINK,1);link.stateId="support";b.skills.add(skill("support_link",link,owned(),SkillDelivery.DIRECT_TARGET,new RuleCost(RuleCost.Type.COOLDOWN,3)));return b;}
	private static SkillSpec skill(String id,EffectSpec effect,TargetingSpec target,SkillDelivery delivery,RuleCost cost){SkillSpec s=new SkillSpec();s.id=id;s.activation=RuleEvent.ACTIVE;s.primary=effect;s.delivery=delivery;s.targeting=target;s.cost=cost;s.constraint=new SkillConstraint();s.conditions.clear();s.conditions.add(new RuleCondition());return s;}
	private static TargetingSpec self(){return new TargetingSpec();}
	private static TargetingSpec cell(){TargetingSpec t=new TargetingSpec();t.selector=TargetingSpec.Selector.SELECTED_CELL;t.filter=TargetingSpec.Filter.ANY;return t;}
	private static TargetingSpec owned(){TargetingSpec t=new TargetingSpec();t.selector=TargetingSpec.Selector.ALL_MATCHING;t.filter=TargetingSpec.Filter.OWNED_ENTITY;t.maxTargets=6;return t;}

	private static boolean overdraftDependencyMatches(){ClassBuild b=new ClassBuild();b.name="dependency";ResourceSpec pool=PlayerBuildAssembler.preset(ResourceEngine.MANUAL,"ammo","Ammo");b.resources.add(pool);b.laws.add(ClassLaw.RESOURCE_OVERDRAFT_USES_HP);ComponentDependency before=LawTraitRegistry.lawDependency(b,ClassLaw.RESOURCE_OVERDRAFT_USES_HP);boolean reported=hasUnresolved(PlayerFacingBuildValidator.classIssues(b));EffectSpec gain=new EffectSpec(EffectFamily.RESOURCE_OPERATION,EffectSpec.Operation.RESOURCE_GAIN,2);gain.resourceId="ammo";SkillSpec skill=new SkillSpec();skill.id="spend";skill.primary=new EffectSpec(EffectFamily.DAMAGE,EffectSpec.Operation.DAMAGE_STANDARD,2);skill.targeting.selector=TargetingSpec.Selector.SELECTED_ACTOR;skill.targeting.filter=TargetingSpec.Filter.ENEMY;skill.cost=new RuleCost(RuleCost.Type.RESOURCE,1);skill.cost.resourceId="ammo";skill.cost.resourceEngine=ResourceEngine.MANUAL;b.skills.add(skill);ComponentDependency after=LawTraitRegistry.lawDependency(b,ClassLaw.RESOURCE_OVERDRAFT_USES_HP);return before.state==ComponentDependency.State.UNRESOLVED&&reported&&after.resolvedState();}
	private static boolean pendingResourceCostResolves(){ClassBuild b=new ClassBuild();b.name="pending_resource";SkillSpec s=basicSkill("pending");s.cost=new RuleCost(RuleCost.Type.RESOURCE,2);s.cost.resourceEngine=ResourceEngine.MANUAL;ArrayList<PlayerFacingValidationIssue> before=PlayerFacingBuildValidator.skillIssues(b,s,-1);if(!onlyUnresolved(before))return false;b.skills.add(s);b.resources.add(PlayerBuildAssembler.preset(ResourceEngine.MANUAL,"ammo","Ammo"));b.resolvePendingBindings();return "ammo".equals(s.cost.resourceId)&&PlayerFacingBuildValidator.skillIssues(b,s,0).isEmpty();}
	private static boolean pendingModeConditionResolves(){ClassBuild b=new ClassBuild();b.name="pending_mode";SkillSpec gated=basicSkill("gated");gated.conditions.clear();gated.conditions.add(new RuleCondition(RuleCondition.Type.MODE_IS));if(!onlyUnresolved(PlayerFacingBuildValidator.skillIssues(b,gated,-1)))return false;b.skills.add(gated);ClassGameplayComponentSpec modes=new ClassGameplayComponentSpec(ClassGameplayComponentSpec.Type.MODE_ENGINE,"mode_engine");modes.modes.add("OFFENSE");modes.modes.add("DEFENSE");b.gameplayComponents.add(modes);b.resolvePendingBindings();return "OFFENSE".equals(gated.conditions.get(0).reference)&&PlayerFacingBuildValidator.skillIssues(b,gated,0).isEmpty();}
	private static boolean pendingConditionKindsRemainSelectable(){for(RuleCondition.Type type:new RuleCondition.Type[]{RuleCondition.Type.TARGET_OWNED,RuleCondition.Type.LINK_EXISTS,RuleCondition.Type.RESOURCE_AT_LEAST}){ClassBuild b=new ClassBuild();b.name="pending_condition";SkillSpec s=basicSkill("pending_"+type.name());s.conditions.clear();s.conditions.add(new RuleCondition(type));if(!onlyUnresolved(PlayerFacingBuildValidator.skillIssues(b,s,-1)))return false;}return true;}
	private static SkillSpec basicSkill(String id){SkillSpec s=new SkillSpec();s.id=id;s.activation=RuleEvent.ACTIVE;s.primary=new EffectSpec(EffectFamily.DAMAGE,EffectSpec.Operation.DAMAGE_STANDARD,2);s.delivery=SkillDelivery.DIRECT_TARGET;s.targeting.selector=TargetingSpec.Selector.SELECTED_ACTOR;s.targeting.coverage=TargetingSpec.Coverage.SINGLE;s.targeting.filter=TargetingSpec.Filter.ENEMY;s.cost=new RuleCost(RuleCost.Type.NONE,0);s.constraint=new SkillConstraint();return s;}
	private static boolean onlyUnresolved(ArrayList<PlayerFacingValidationIssue> issues){if(issues.isEmpty())return false;for(PlayerFacingValidationIssue issue:issues)if(issue.code!=PlayerFacingValidationIssue.Code.UNRESOLVED_DEPENDENCY)return false;return true;}
	private static boolean hasUnresolved(ArrayList<PlayerFacingValidationIssue> issues){for(PlayerFacingValidationIssue issue:issues)if(issue.code==PlayerFacingValidationIssue.Code.UNRESOLVED_DEPENDENCY)return true;return false;}
	private static boolean roundtrip(ClassBuild value){try{Bundle b=new Bundle();value.storeInBundle(b);ClassBuild x=new ClassBuild();x.restoreFromBundle(b);return RuleBuild.from(value).fingerprint().equals(RuleBuild.from(x).fingerprint());}catch(Throwable e){return false;}}
}
