package com.shatteredpixel.shatteredpixeldungeon.qa;

import com.shatteredpixel.shatteredpixeldungeon.rules.*;
import com.shatteredpixel.shatteredpixeldungeon.rules.legacy.v5.LegacyGameplayBoundary;
import com.watabou.utils.Bundle;

import java.util.ArrayList;
import java.util.LinkedHashMap;

/** Proves that QA fixtures use only choices and parameter ranges reachable from the player Builder. */
public final class PlayerBuildEquivalenceAudit {
	public static final class BuildResult { public String id;public int used,max;public boolean constructible,roundtrip;public final ArrayList<String> failures=new ArrayList<>(); }
	public static final class Result { public String schema="player-build-equivalence-1";public String evidenceClassification=LegacyGameplayBoundary.EVIDENCE_CLASSIFICATION;public boolean v6CompletionEligible=LegacyGameplayBoundary.V6_COMPLETION_ELIGIBLE;public int builds,qaBuildNotPlayerConstructible,budgetMismatches,roundtripFailures;public final ArrayList<BuildResult> results=new ArrayList<>();public boolean passed; }
	private PlayerBuildEquivalenceAudit() {}

	public static Result run(){Result result=new Result();LinkedHashMap<String,ClassBuild> builds=new LinkedHashMap<>();for(ArchetypeReferenceBuilds.Id id:ArchetypeReferenceBuilds.allIds())builds.put("ARCHETYPE:"+id.name(),ArchetypeReferenceBuilds.build(id));for(QaScenario scenario:FullSkillReferenceBuilds.scenarios())builds.put("RUNTIME:"+scenario.id,scenario.hero.classBuild);builds.putAll(LawTraitReferenceBuilds.all());for(String id:builds.keySet()){BuildResult row=check(id,builds.get(id));result.results.add(row);result.builds++;if(!row.constructible)result.qaBuildNotPlayerConstructible++;if(row.max!=ClassBudgetPolicy.newBuildBudget()+builds.get(id).progression.budgetBonus+restrictionBonus(builds.get(id)))result.budgetMismatches++;if(!row.roundtrip)result.roundtripFailures++;}result.passed=result.qaBuildNotPlayerConstructible==0&&result.budgetMismatches==0&&result.roundtripFailures==0;return result;}

	private static BuildResult check(String id,ClassBuild source){ClassBuild build=source.copy();build.normalizeLegacyComponents();build.resolvePendingBindings();BuildResult row=new BuildResult();row.id=id;row.used=build.usedBudget();row.max=build.maxBudget();if(build.baseBudget!=ClassBudgetPolicy.newBuildBudget())row.failures.add("BUDGET_AUTHORITY");for(ResourceSpec resource:build.resources)if(!PlayerBuildAssembler.resourceExposed(resource)||resource.engine!=ResourceEngine.MANUAL)row.failures.add("RESOURCE:"+resource.id);for(ClassGameplayComponentSpec component:build.gameplayComponents)if(!GameplayComponentRegistry.playerExposed(component))row.failures.add("COMPONENT:"+component.id);for(ClassLaw law:build.laws)if(!LawTraitRegistry.exposed(law))row.failures.add("LAW:"+law);for(TraitSpec trait:build.traits)if(!LawTraitRegistry.exposed(trait.type)||!LawTraitRegistry.traitDependency(build,trait).playerSelectable())row.failures.add("TRAIT:"+trait.stableId());for(SkillSpec skill:build.skills)checkSkill(build,skill,row.failures);PlayerBuildAssembler assembler=PlayerBuildAssembler.reconstruct(build);row.failures.addAll(assembler.failures());ClassBuild reconstructed=assembler.build();if(!RuleBuild.from(build).fingerprint().equals(RuleBuild.from(reconstructed).fingerprint()))row.failures.add("PLAYER_PATH_MISMATCH");row.roundtrip=roundtrip(build);if(!row.roundtrip)row.failures.add("ROUNDTRIP");row.constructible=row.failures.isEmpty();return row;}
	private static void checkSkill(ClassBuild build,SkillSpec skill,ArrayList<String> failures){if(!EffectVocabularyRegistry.exposed(skill.primary.operation))failures.add(skill.id+":PRIMARY");if(skill.secondary!=null&&!EffectVocabularyRegistry.exposed(skill.secondary.operation))failures.add(skill.id+":SECONDARY");if(!DeliveryRegistry.exposed().contains(skill.delivery))failures.add(skill.id+":DELIVERY");if(!TargetingRegistry.SELECTORS.contains(skill.targeting.selector)||!TargetingRegistry.COVERAGES.contains(skill.targeting.coverage)||!TargetingRegistry.FILTERS.contains(skill.targeting.filter)||skill.targeting.range<1||skill.targeting.range>10||skill.targeting.magnitude<1||skill.targeting.magnitude>4||skill.targeting.maxTargets<1||skill.targeting.maxTargets>8)failures.add(skill.id+":TARGET");boolean modifier=false;for(RuleModifier value:ModifierRegistry.options())if(equal(value,skill.modifier))modifier=true;if(!modifier)failures.add(skill.id+":MODIFIER");boolean cost=false;for(CostRegistry.Entry value:CostRegistry.exposed(build))if(equal(value.cost,skill.cost))cost=true;if(!cost)failures.add(skill.id+":COST");boolean constraint=false;for(SkillConstraint value:ConstraintRegistry.exposed())if(value.variant==skill.constraint.variant&&value.parameter==skill.constraint.parameter)constraint=true;if(!constraint)failures.add(skill.id+":CONSTRAINT");if(!effectParametersReachable(skill.primary,build)||(skill.secondary!=null&&!effectParametersReachable(skill.secondary,build)))failures.add(skill.id+":PARAMETERS");if(!PlayerFacingBuildValidator.skillIssues(buildWithout(build,skill),skill,-1).isEmpty())failures.add(skill.id+":VALIDATION");}
	private static boolean effectParametersReachable(EffectSpec value,ClassBuild build){return EffectVocabularyRegistry.playerReachable(value,build);}
	private static ClassBuild buildWithout(ClassBuild build,SkillSpec skill){ClassBuild copy=build.copy();for(int i=0;i<copy.skills.size();i++)if(copy.skills.get(i).id.equals(skill.id)){copy.skills.remove(i);break;}return copy;}
	private static boolean equal(RuleModifier a,RuleModifier b){return a.type==b.type&&a.magnitude==b.magnitude;}
	private static boolean equal(RuleCost a,RuleCost b){return a.type==b.type&&a.amount==b.amount&&same(a.resourceId,b.resourceId)&&same(a.reference,b.reference);}
	private static boolean same(String a,String b){return a==null?b==null:a.equals(b);}
	private static int restrictionBonus(ClassBuild build){int result=0;for(Restriction value:build.restrictions)result+=value.capacityBonus;return result;}
	private static boolean roundtrip(ClassBuild build){try{Bundle bundle=new Bundle();build.storeInBundle(bundle);ClassBuild restored=new ClassBuild();restored.restoreFromBundle(bundle);return RuleBuild.from(build).fingerprint().equals(RuleBuild.from(restored).fingerprint());}catch(Throwable ignored){return false;}}
}
